import type { Metadata } from "next";
import { LEGAL_ENTITY, LEGAL_ENTITY_ABN_LABEL, LEGAL_ENTITY_ACN_LABEL } from "@/lib/site/legal-entity";
import Link from "next/link";
import fs from "node:fs";
import path from "node:path";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { CtaBand, FOCUS_RING, MOTION, PageHero, Section, StatStrip } from "@/components/marketing/template";
import { pageMetadata } from "@/lib/seo/page-meta";
import { Building2, ExternalLink, MapPin, User } from "lucide-react";

// Force dynamic — team-roster.json is regenerated by the agent-activity
// cron (last30d_count, latest_activity_date). ISR would show stale counts
// until the next revalidate; dynamic keeps the fleet snapshot fresh.
export const dynamic = "force-dynamic";

// G17 P2-A: pageMetadata (canonical + OG image); rendered on the template —
// PageHero → Section (founder + entity) → Section (bench: StatStrip + the
// roster grid) → CtaBand.
export const metadata: Metadata = pageMetadata({
  title: "The BlockID team — a C-suite of AI agents",
  description:
    "BlockID.au is operated by a C-suite of AI agents. Each role self-upgrades the platform and powers customer reports. Founder-led, Sydney NSW.",
  path: "/team",
});

type RosterRow = {
  slug: string;
  role: string;
  tagline: string;
  last30d_count: number;
  latest_activity_date: string | null;
};

function readRoster(): RosterRow[] {
  const candidates = [
    path.join(process.cwd(), "web", "content", "team-roster.json"),
    path.join(process.cwd(), "content", "team-roster.json"),
    path.join(process.cwd(), "..", "web", "content", "team-roster.json"),
  ];
  for (const p of candidates) {
    try {
      const raw = fs.readFileSync(p, "utf-8");
      return JSON.parse(raw) as RosterRow[];
    } catch {
      // try next
    }
  }
  return [];
}

// Short one-line tagline extracted from the SKILL.md description
// (the front-matter blurb reads: "<role> — <tagline>. Use when '<...>'.").
function shortTagline(row: RosterRow): string {
  const stripped = row.tagline.split(". Use when")[0] ?? row.tagline;
  const em = stripped.indexOf("—");
  return (em >= 0 ? stripped.slice(em + 1) : stripped).trim();
}

export default function TeamPage() {
  const roster = readRoster();
  const totalShips = roster.reduce((s, r) => s + r.last30d_count, 0);
  const activeRoles = roster.filter((r) => r.last30d_count > 0).length;

  return (
    <MarketingShell>
      <PageHero
        eyebrow="The team"
        title="A C-suite of AI agents, one workflow"
        sub="Each role self-upgrades the platform and powers customer reports. Cards show live shipping activity from the last 30 days."
        ctas={[
          { href: "/changelog", label: "See what shipped", ctaId: "team_hero_changelog" },
          { href: "/about", label: "About BlockID" },
        ]}
        align="start"
      />

      {/* Founder + operating entity */}
      <Section id="founder" ariaLabel="Founder and operating entity" spacing="sm" tone="sunken">
        <div className="grid gap-4 sm:grid-cols-2 sm:gap-6">
          <div className="flex items-start gap-4 rounded-xl border border-line-subtle bg-surface p-6 shadow-1">
            <span
              aria-hidden="true"
              className="mt-1 inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-accent-soft text-accent"
            >
              <User className="h-5 w-5" strokeWidth={1.75} />
            </span>
            <div className="min-w-0">
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">
                Founder
              </p>
              <h2 className="mt-1 font-display text-lg font-semibold text-primary">
                Long DO — Founder
              </h2>
              <p className="mt-2 text-sm leading-relaxed text-secondary">
                Founder and product lead. Sets the roadmap, approves every
                ship, and owns the founder relationship. Execution is
                delivered by a cross-border team coordinated with{" "}
                <strong className="text-primary">{LEGAL_ENTITY.operator}</strong>{" "}
                in Australia (go-to-market, compliance, customer contracts)
                and the{" "}
                <strong className="text-primary">
                  tech team at Vietnam Blockchain Corporation
                </strong>{" "}
                (engineering, blockchain infrastructure, data platform), with
                every shipped change audited via the daily digest at{" "}
                <code className="rounded bg-surface-sunken px-1 py-0.5 text-[0.85em]">
                  /admin
                </code>
                .
              </p>
              <p className="mt-3">
                <a
                  href="https://www.linkedin.com/in/dovanlong/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className={`inline-flex min-h-11 items-center gap-1.5 rounded-md text-sm font-medium text-action underline-offset-4 hover:underline ${MOTION} ${FOCUS_RING}`}
                  aria-label="Long DO on LinkedIn (opens in new tab)"
                >
                  LinkedIn
                  <ExternalLink className="h-3.5 w-3.5" strokeWidth={1.75} aria-hidden="true" />
                </a>
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4 rounded-xl border border-line-subtle bg-surface p-6 shadow-1">
            <span
              aria-hidden="true"
              className="mt-1 inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-accent-soft text-accent"
            >
              <Building2 className="h-5 w-5" strokeWidth={1.75} />
            </span>
            <div className="min-w-0">
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">
                Operating entity
              </p>
              <h2 className="mt-1 font-display text-lg font-semibold text-primary">
                {LEGAL_ENTITY.marketingOperator}
              </h2>
              <p className="mt-2 text-sm leading-relaxed text-secondary">
                Australian proprietary company operating BlockID.au. Customer
                contracts, invoices and GST are issued by{" "}
                <strong className="text-primary">{LEGAL_ENTITY.operator}</strong>{" "}
                ({LEGAL_ENTITY_ACN_LABEL} · {LEGAL_ENTITY_ABN_LABEL}).
              </p>
              <p className="mt-2 inline-flex items-center gap-1.5 text-xs text-secondary">
                <MapPin className="h-3.5 w-3.5" aria-hidden="true" strokeWidth={1.75} />
                Sydney, NSW, Australia
              </p>
            </div>
          </div>
        </div>
      </Section>

      <Section
        id="bench"
        eyebrow="AI advisor bench"
        title="The C-suite of AI agents behind every report"
        lede="Each seat below is an AI agent with its own research + build cron, colocated tests, and audit trail. Cards show live shipping activity from the last 30 days."
      >
        <StatStrip
          ariaLabel="Fleet activity"
          stats={[
            { value: String(roster.length), label: "Roles staffed" },
            { value: String(activeRoles), label: "Active in last 30 days" },
            { value: String(totalShips), label: "Reports & ships (30d)" },
          ]}
          caption="Live from content/team-roster.json, regenerated by the agent-activity cron."
        />

        {/* Grid */}
        {roster.length === 0 ? (
          <p className="mt-10 text-sm text-secondary">
            Team roster not yet published for this environment. Run
            <code className="mx-1 rounded bg-surface-sunken px-1.5 py-0.5 text-[0.85em]">
              node scripts/docs/regenerate-team-page.mjs
            </code>
            to populate this page.
          </p>
        ) : (
          <ul className="mt-10 grid grid-cols-1 gap-4 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3" aria-label="AI advisor bench">
            {roster.map((r) => (
              <li key={r.slug} className="flex">
                <Link
                  href={`/team/${r.slug}`}
                  className={`flex h-full w-full flex-col rounded-xl border border-line-subtle bg-surface p-6 shadow-1 hover:border-line hover:shadow-2 ${MOTION} ${FOCUS_RING}`}
                >
                  <div className="flex items-baseline justify-between gap-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">
                      {r.slug === "customer-success"
                        ? "CS"
                        : r.slug.toUpperCase()}
                    </p>
                    <span className="rounded-full border border-line-subtle px-2 py-0.5 font-mono text-[10px] tabular-nums text-secondary">
                      {r.last30d_count} 30d
                    </span>
                  </div>
                  <h3 className="mt-2 font-display text-lg font-semibold tracking-tight text-primary">
                    {r.role}
                  </h3>
                  <p className="mt-3 line-clamp-4 text-sm leading-relaxed text-secondary">
                    {shortTagline(r)}
                  </p>
                  <p className="mt-auto pt-4 text-xs text-muted">
                    {r.latest_activity_date
                      ? `Last shipped ${r.latest_activity_date}`
                      : "No activity this window"}
                  </p>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </Section>

      <CtaBand
        title="See what shipped, and what's next."
        primary={{ href: "/changelog", label: "Changelog", ctaId: "team_final_changelog" }}
        secondary={{ href: "/roadmap", label: "Roadmap" }}
      />
    </MarketingShell>
  );
}
