import type { Metadata } from "next";
import Link from "next/link";
import fs from "node:fs";
import path from "node:path";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { MarketingHero } from "@/components/marketing/marketing-hero";
import { MarketingCtaStrip } from "@/components/marketing/marketing-cta-strip";
import { Building2, MapPin, User } from "lucide-react";

// Force dynamic — team-roster.json is regenerated by the agent-activity
// cron (last30d_count, latest_activity_date). ISR would show stale counts
// until the next revalidate; dynamic keeps the fleet snapshot fresh.
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "The BlockID Team — 11 AI-Agent C-Levels",
  description:
    "BlockID.au is operated by a fleet of AI C-Level agents. Each role self-upgrades the platform and powers customer reports.",
  robots: { index: true, follow: true },
  alternates: { canonical: "https://blockid.au/team" },
};

type RosterRow = {
  slug: string;
  role: string;
  tagline: string;
  last30d_count: number;
  latest_activity_date: string | null;
};

function readRoster(): RosterRow[] {
  const candidates = [
    path.join(process.cwd(), "web", "content", "team-roster.json"),
    path.join(process.cwd(), "content", "team-roster.json"),
    path.join(process.cwd(), "..", "web", "content", "team-roster.json"),
  ];
  for (const p of candidates) {
    try {
      const raw = fs.readFileSync(p, "utf-8");
      return JSON.parse(raw) as RosterRow[];
    } catch {
      // try next
    }
  }
  return [];
}

// Short one-line tagline extracted from the SKILL.md description
// (the front-matter blurb reads: "<role> — <tagline>. Use when '<...>'.").
function shortTagline(row: RosterRow): string {
  const stripped = row.tagline.split(". Use when")[0] ?? row.tagline;
  const em = stripped.indexOf("—");
  return (em >= 0 ? stripped.slice(em + 1) : stripped).trim();
}

export default function TeamPage() {
  const roster = readRoster();
  const totalShips = roster.reduce((s, r) => s + r.last30d_count, 0);
  const activeRoles = roster.filter((r) => r.last30d_count > 0).length;

  return (
    <MarketingShell>
      <MarketingHero
        eyebrow="The team"
        title={`${roster.length || 11} AI-agent C-Levels, one workflow`}
        subtitle="Each role self-upgrades the platform and powers customer reports. Cards show live shipping activity from the last 30 days."
      />

      {/* Founder + operating entity */}
      <section
        aria-label="Founder and operating entity"
        className="mx-auto max-w-6xl px-6 pt-10 sm:pt-14"
      >
        <div className="grid gap-4 rounded-3xl border border-[var(--fintech-border)] bg-[var(--fintech-bg-elevated)] p-6 sm:grid-cols-2 sm:p-8">
          <div className="flex items-start gap-4">
            <span
              aria-hidden="true"
              className="mt-1 inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-[var(--fintech-border)] bg-[var(--fintech-surface)] text-[var(--fintech-accent)]"
            >
              <User className="h-5 w-5" strokeWidth={1.75} />
            </span>
            <div className="min-w-0">
              <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[var(--fintech-accent)]">
                Founder
              </p>
              <h2 className="mt-1 text-lg font-semibold text-[var(--fintech-ink)]">
                Do Van Long — CEO
              </h2>
              <p className="mt-2 text-sm leading-relaxed text-[var(--fintech-ink-muted)]">
                Solo human founder. Sets the roadmap, approves every ship, and
                owns the founder relationship. All C-Level execution — build,
                research, reporting — is delegated to the AI advisor bench
                below and audited via the daily digest at{" "}
                <code className="rounded bg-[var(--fintech-surface)] px-1 py-0.5 text-[0.85em]">
                  /admin
                </code>
                .
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <span
              aria-hidden="true"
              className="mt-1 inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-[var(--fintech-border)] bg-[var(--fintech-surface)] text-[var(--fintech-accent)]"
            >
              <Building2 className="h-5 w-5" strokeWidth={1.75} />
            </span>
            <div className="min-w-0">
              <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[var(--fintech-accent)]">
                Operating entity
              </p>
              <h2 className="mt-1 text-lg font-semibold text-[var(--fintech-ink)]">
                Auschain Pty Ltd
              </h2>
              <p className="mt-2 text-sm leading-relaxed text-[var(--fintech-ink-muted)]">
                ACN 659 615 111 · ABN 79 659 615 111. Australian proprietary
                company; all customer contracts, invoices and GST are issued
                in this entity&apos;s name.
              </p>
              <p className="mt-2 inline-flex items-center gap-1.5 text-xs text-[var(--fintech-ink-muted)]">
                <MapPin className="h-3.5 w-3.5" aria-hidden="true" strokeWidth={1.75} />
                Sydney, NSW, Australia
              </p>
            </div>
          </div>
        </div>
      </section>

      <section
        aria-label="AI advisor bench"
        className="mx-auto max-w-6xl px-6 py-12 sm:py-16"
      >
        <div className="mb-8">
          <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[var(--fintech-accent)]">
            AI advisor bench
          </p>
          <h2 className="mt-2 text-2xl font-bold tracking-tight text-[var(--fintech-ink)] sm:text-3xl">
            {roster.length || 11} specialised C-Level agents
          </h2>
          <p className="mt-3 max-w-3xl text-sm leading-relaxed text-[var(--fintech-ink-muted)]">
            Each seat below is an AI agent with its own research + build cron,
            colocated tests, and audit trail. Cards show live shipping activity
            from the last 30 days.
          </p>
        </div>
        {/* Summary bar */}
        <div className="mb-10 rounded-2xl border border-[var(--fintech-border)] bg-[var(--fintech-bg-elevated)] px-6 py-5">
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <p className="font-mono text-2xl font-extrabold tabular-nums text-[var(--fintech-accent)]">
                {roster.length}
              </p>
              <p className="mt-1 text-xs text-[var(--fintech-ink-muted)]">
                Roles staffed
              </p>
            </div>
            <div>
              <p className="font-mono text-2xl font-extrabold tabular-nums text-[var(--fintech-accent)]">
                {activeRoles}
              </p>
              <p className="mt-1 text-xs text-[var(--fintech-ink-muted)]">
                Active in last 30 days
              </p>
            </div>
            <div>
              <p className="font-mono text-2xl font-extrabold tabular-nums text-[var(--fintech-accent)]">
                {totalShips}
              </p>
              <p className="mt-1 text-xs text-[var(--fintech-ink-muted)]">
                Reports & ships (30d)
              </p>
            </div>
          </div>
        </div>

        {/* Grid */}
        {roster.length === 0 ? (
          <p className="text-sm text-[var(--fintech-ink-muted)]">
            Team roster not yet published for this environment. Run
            <code className="mx-1 rounded bg-[var(--fintech-surface)] px-1.5 py-0.5 text-[0.85em]">
              node scripts/docs/regenerate-team-page.mjs
            </code>
            to populate this page.
          </p>
        ) : (
          <ul className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {roster.map((r) => (
              <li key={r.slug}>
                <Link
                  href={`/team/${r.slug}`}
                  className="group block h-full rounded-2xl border border-[var(--fintech-border)] bg-[var(--fintech-bg-elevated)] p-6 transition-colors hover:border-[var(--fintech-accent)]"
                >
                  <div className="flex items-baseline justify-between gap-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--fintech-accent)]">
                      {r.slug === "customer-success"
                        ? "CS"
                        : r.slug.toUpperCase()}
                    </p>
                    <span className="rounded-full border border-[var(--fintech-border)] px-2 py-0.5 font-mono text-[10px] tabular-nums text-[var(--fintech-ink-muted)]">
                      {r.last30d_count} 30d
                    </span>
                  </div>
                  <h3 className="mt-2 text-base font-semibold text-[var(--fintech-ink)]">
                    {r.role}
                  </h3>
                  <p className="mt-3 line-clamp-4 text-sm leading-relaxed text-[var(--fintech-ink-muted)]">
                    {shortTagline(r)}
                  </p>
                  <p className="mt-4 text-xs text-[var(--fintech-ink-muted)]">
                    {r.latest_activity_date
                      ? `Last shipped ${r.latest_activity_date}`
                      : "No activity this window"}
                  </p>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </section>

      <MarketingCtaStrip
        headline="See what shipped, and what's next."
        primary={{ href: "/changelog", label: "Changelog" }}
        secondary={{ href: "/roadmap", label: "Roadmap" }}
      />
    </MarketingShell>
  );
}
