ALTER TABLE svi_analyses ADD COLUMN IF NOT EXISTS rnd_report_json JSONB DEFAULT NULL;
ALTER TABLE svi_analyses ADD COLUMN IF NOT EXISTS input_type TEXT DEFAULT 'idea';
ALTER TABLE svi_analyses ADD COLUMN IF NOT EXISTS scraped_url TEXT DEFAULT NULL;
