-- 0292_oauth2_partners.sql
-- Phase 5 Batch I sub-task I3 — OAuth2 partner clients + access/refresh tokens.
--
-- Master Upgrade Plan §5.5 (Partner API OAuth2). Introduces two tables:
--
--   * oauth2_clients — registered partner apps (client_id + hashed client_secret,
--     redirect_uris whitelist, allowed_scopes cap). client_secret_hash uses
--     bcrypt today; the plan calls for Argon2id — see hashing note below.
--   * oauth2_tokens  — issued bearer tokens (both access and refresh kinds).
--     token_hash is SHA-256 of the raw bearer; the raw is shown once to the
--     partner and never persisted. Presented tokens are validated by hashing
--     and constant-time comparing against token_hash.
--
-- Hashing note (client_secret_hash column):
--   The Master Plan §5.5 specifies Argon2id for the client_secret hash. The
--   web workspace currently ships only bcryptjs (see package.json). To avoid
--   a fresh native-build dep at Phase-5 velocity, this migration stores a
--   bcrypt hash and the verify helper treats the column as an opaque
--   "password verifier" string — a follow-up can pepper-migrate to Argon2id
--   without touching the schema. Bearer tokens themselves already use
--   SHA-256 hashing per spec, which is what the hot-path partner-API auth
--   check exercises.
--
-- FK notes:
--   * partner_org_id references public.projects(id) — scaffolded until orgs.
--   * subject_user_id references public.app_users(id) — nullable for the
--     client-credentials grant (machine-to-machine, no end-user subject).
--   * subject_business_id references public.projects(id) — the business the
--     token is scoped to (nullable for org-wide tokens).
--
-- Idempotency: every DDL uses IF NOT EXISTS. Single BEGIN/COMMIT.
--
-- RLS: enabled defense-in-depth; the verify helper reads via service-role.
--
-- Reserved lane: 02xx spec lane per Master Upgrade Plan §5.2.

BEGIN;

-- ─── oauth2_clients ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.oauth2_clients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- URL-safe public identifier. 32 chars generated by the registration
  -- flow; unique globally so partners can share client_id in redirect URLs
  -- without collision.
  client_id text UNIQUE NOT NULL,

  -- Hashed client_secret. See "Hashing note" in the header — bcrypt today,
  -- Argon2id via pepper-migrate later. Never store or return the raw.
  client_secret_hash text NOT NULL,

  -- Owning partner org. Scaffolded on projects(id) until orgs table lands.
  partner_org_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,

  partner_name text NOT NULL,

  -- Whitelist. Authorization-code redirect targets MUST exact-match one
  -- entry in this array. Empty = client-credentials-only client.
  redirect_uris text[] NOT NULL DEFAULT '{}',

  -- Scopes the client is allowed to request. Legal values:
  --   evidence:read       — read the business's evidence library
  --   report:share        — issue a share_package on the business's behalf
  --   verification:write  — submit fresh evidence for re-verification
  --   profile:read        — read the private founder profile (with consent)
  --   id:public:read      — read the public /id/[slug] JSON view
  -- The token endpoint intersects this list with the requested scopes.
  allowed_scopes text[] NOT NULL DEFAULT '{}',

  active boolean NOT NULL DEFAULT true,

  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS oauth2_clients_partner_org_idx
  ON public.oauth2_clients (partner_org_id);

CREATE INDEX IF NOT EXISTS oauth2_clients_active_idx
  ON public.oauth2_clients (active);

ALTER TABLE public.oauth2_clients ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.oauth2_clients IS
  'Master Upgrade Plan §5.5 — registered OAuth2 partner clients. client_secret_hash is bcrypt today, Argon2id via pepper-migrate later. Bearer tokens themselves use SHA-256 (see oauth2_tokens.token_hash).';

-- ─── oauth2_tokens ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.oauth2_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  client_id text NOT NULL
    REFERENCES public.oauth2_clients(client_id) ON DELETE CASCADE,

  -- Subject the token is issued on behalf of. NULL for client-credentials
  -- grant (machine-to-machine, no end-user subject).
  subject_user_id uuid
    REFERENCES public.app_users(id) ON DELETE CASCADE,

  -- Business the token is scoped to. Nullable for org-wide tokens.
  subject_business_id uuid
    REFERENCES public.projects(id) ON DELETE CASCADE,

  -- SHA-256 of the raw bearer. Raw is shown once to the partner and never
  -- persisted; the verify helper hashes the presented bearer and
  -- constant-time compares against this column.
  token_hash text NOT NULL,

  -- 'access' tokens are short-lived (~1h), 'refresh' tokens long-lived.
  token_kind text NOT NULL
    CHECK (token_kind IN ('access','refresh')),

  -- Scopes granted at issue-time. Verify helper checks the requested
  -- resource against this intersection.
  scopes text[] NOT NULL DEFAULT '{}',

  issued_at   timestamptz NOT NULL DEFAULT now(),
  expires_at  timestamptz NOT NULL,
  revoked_at  timestamptz
);

-- Global uniqueness on token_hash — prevents collision + supports the
-- primary hot-path SELECT ... WHERE token_hash = $1.
CREATE UNIQUE INDEX IF NOT EXISTS oauth2_tokens_hash_uniq
  ON public.oauth2_tokens (token_hash);

-- Client-scoped expiry scans (cleanup cron, per-client usage dashboards).
CREATE INDEX IF NOT EXISTS oauth2_tokens_client_expires_idx
  ON public.oauth2_tokens (client_id, expires_at);

ALTER TABLE public.oauth2_tokens ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.oauth2_tokens IS
  'Master Upgrade Plan §5.5 — issued OAuth2 bearer tokens. token_hash = SHA-256 of the raw bearer (raw never persisted). Both access and refresh kinds land in this table; token_kind narrows.';

COMMIT;

-- After apply:
--   NOTIFY pgrst, 'reload schema';
