-- Migration: investor_pack_shares
-- T-1203 — one-click investor pack share tokens.
--
-- Each row represents a share link generated by a founder. The PDF is
-- regenerated on-demand when the share link is accessed (no blob storage
-- required). Shares expire after 30 days to limit stale data exposure.

CREATE TABLE IF NOT EXISTS investor_pack_shares (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        NOT NULL,
  project_id    uuid,
  share_id      text        NOT NULL UNIQUE,   -- opaque URL-safe token (nanoid 21)
  created_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  downloaded_at timestamptz,                   -- first download timestamp (nullable)
  download_count integer    NOT NULL DEFAULT 0,
  pack_meta     jsonb                          -- snapshot of startup name, SVI grade, etc.
);

-- Index for user-scoped look-ups (workspace tile query).
CREATE INDEX IF NOT EXISTS idx_investor_pack_shares_user_id
  ON investor_pack_shares (user_id, created_at DESC);

-- Index for the download route look-up by share_id.
CREATE INDEX IF NOT EXISTS idx_investor_pack_shares_share_id
  ON investor_pack_shares (share_id);

COMMENT ON TABLE investor_pack_shares IS
  'Share tokens for the one-click investor pack PDF (T-1203). Each row is one generated pack; the PDF is re-rendered on demand. Rows expire after 30 days.';
