// T0097 — AU-native equity document templates.
//
// All templates are AU-law-compliant boilerplate (general info, not legal
// advice — the rendered doc carries that disclaimer). They are designed to
// fill cleanly from the T0094 equity_plans / equity_members / esop_pools /
// equity_vesting_schedules schema.

export interface StartupCtx {
  startupName: string;
  incorporationDate?: string | null;
  jurisdiction?: string; // default "AU"
  totalShares: number;
  preMoneyValuationAud?: number | null;
}

export interface MemberCtx {
  name: string;
  email?: string | null;
  role: string;
  sharesIssued?: number;
  optionsGranted?: number;
  joinDate: string;
}

export interface VestingCtx {
  totalShares: number;
  cliffMonths: number;
  vestMonths: number;
  scheduleType: string;
  startDate: string;
  accelerateOnExit?: boolean;
}

export interface CapTableCtx {
  rows: Array<{
    name: string;
    role: string;
    shareClass: string;
    shares: number;
    options: number;
    ownershipPct: number;
    fullyDilutedPct: number;
    valueAud: number;
  }>;
  totalShares: number;
  esopPoolPct?: number;
  preMoneyValuationAud?: number | null;
}

const DISCLAIMER =
  "This document is generated by BlockID.au as general information only. " +
  "It is not legal, tax, or financial advice. Before relying on it, obtain " +
  "advice from a qualified Australian solicitor and a registered tax agent.";

function fmtDate(iso?: string | null): string {
  if (!iso) return "[date]";
  const d = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-AU", { day: "2-digit", month: "long", year: "numeric" });
}

function fmtAud(n?: number | null): string {
  if (n == null || Number.isNaN(n)) return "A$—";
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
    maximumFractionDigits: 0,
  }).format(n);
}

function fmtInt(n: number): string {
  return new Intl.NumberFormat("en-AU").format(Math.round(n));
}

// ---------------------------------------------------------------------------
// 1. ESOP Grant Letter (AU ESS / Division 83A ITAA 1997 compliant)
// ---------------------------------------------------------------------------

export function esopGrantLetter(
  startup: StartupCtx,
  member: MemberCtx,
  vesting: VestingCtx,
  exercisePriceAud: number,
): string {
  return `# Employee Share Scheme — Option Grant Letter

**${startup.startupName}** (ACN [insert]) — Issued ${fmtDate(new Date().toISOString().slice(0, 10))}

---

**Grantee:** ${member.name}${member.email ? `  \n**Email:** ${member.email}` : ""}
**Role:** ${member.role}
**Grant date:** ${fmtDate(member.joinDate)}

## 1. Grant

The Company grants you **${fmtInt(vesting.totalShares)} options** to subscribe for
ordinary shares in ${startup.startupName} at an exercise price of **${fmtAud(exercisePriceAud)} per share**.

This grant is made under the Company's Employee Share Scheme ("ESS"), which has
been adopted by the board and is intended to qualify as an ESS interest under
Division 83A of the *Income Tax Assessment Act 1997* (Cth).

## 2. Vesting

- **Cliff:** ${vesting.cliffMonths} months from ${fmtDate(vesting.startDate)}.
- **Total vesting period:** ${vesting.vestMonths} months.
- **Schedule:** ${vesting.scheduleType}.
- **Acceleration on exit:** ${vesting.accelerateOnExit ? "Yes — full acceleration on a Change of Control or qualifying sale." : "No."}

No options vest before the cliff date. On the cliff date, options earned up to
that date vest in a single tranche; the remainder vest in equal periods until
fully vested.

## 3. Exercise

Vested options may be exercised at any time prior to expiry (10 years from
grant) by delivering an exercise notice and payment of the exercise price to
the Company.

## 4. AU tax treatment

This ESS is intended to qualify for the **startup tax concession** in
section 83A-33 of the ITAA 1997. Where eligible (Company is an unlisted
Australian-resident company, less than 10 years old, aggregated turnover under
A$50M, etc.), the discount is *not* assessed at grant and CGT discount rules
apply on disposal.

The Company will issue an ESS Statement to you for each income year in which
a taxing event occurs and lodge an ESS Annual Report with the ATO.

## 5. Leaver provisions

- **Good leaver** (death, permanent disability, redundancy, retirement at NPA):
  vested options remain exercisable; unvested options lapse.
- **Bad leaver** (resignation < 12 months, summary dismissal for cause): all
  options (vested and unvested) lapse.

## 6. ASIC

The Company will rely on the ESS disclosure relief under section 1100W of the
*Corporations Act 2001* (Cth) and ASIC Class Order [CO 14/1000] /
ASIC Corporations (Employee Share Schemes) Instrument 2022/1021 where
applicable.

---

Signed for and on behalf of **${startup.startupName}**:

Director: ____________________ Date: ____________

Accepted by Grantee:

${member.name}: ____________________ Date: ____________

---

> ${DISCLAIMER}
`;
}

// ---------------------------------------------------------------------------
// 2. Vesting Agreement (4-yr / 1-yr cliff with leaver provisions)
// ---------------------------------------------------------------------------

export function vestingAgreement(
  startup: StartupCtx,
  member: MemberCtx,
  vesting: VestingCtx,
): string {
  return `# Vesting Agreement

**Between:** ${startup.startupName} (ACN [insert]) ("Company")
**And:** ${member.name} ("Holder")

**Effective date:** ${fmtDate(vesting.startDate)}

## 1. Subject shares

${fmtInt(vesting.totalShares)} ordinary shares (or option-equivalents) in the
Company held by the Holder ("Subject Shares").

## 2. Vesting schedule

- **Cliff:** ${vesting.cliffMonths} months.
- **Vesting period:** ${vesting.vestMonths} months from ${fmtDate(vesting.startDate)}.
- **Schedule type:** ${vesting.scheduleType}.

Until vested, the Subject Shares are subject to compulsory buy-back at the
lower of issue price and fair market value.

## 3. Acceleration

${vesting.accelerateOnExit
  ? "On a Change of Control (sale of >50% of voting shares, sale of business, listing), all unvested Subject Shares vest in full immediately prior to completion (single-trigger acceleration)."
  : "No automatic acceleration. The board may, in its sole discretion, accelerate vesting on a Change of Control."}

## 4. Leaver provisions

- **Good leaver** (death, permanent disability, redundancy, mutual separation):
  vested shares retained; unvested shares bought back at fair market value.
- **Bad leaver** (resignation without good reason within the vesting period,
  summary dismissal for cause, material breach): all unvested shares bought
  back at A$0.001 each; vested shares bought back at the lower of issue price
  and fair market value.

## 5. Restraints (AU law)

The Holder agrees not to, while holding Subject Shares and for 12 months after
ceasing to hold them, solicit Company customers or employees within Australia.
This restraint is intended to be reasonable and severable under the *Restraints
of Trade Act 1976* (NSW) and equivalent state law; if held unreasonable, it
applies for the shorter period / smaller area that is reasonable.

## 6. Governing law

This agreement is governed by the laws of New South Wales, Australia.

---

Signed by Company director: ____________________ Date: ____________

Signed by Holder (${member.name}): ____________________ Date: ____________

> ${DISCLAIMER}
`;
}

// ---------------------------------------------------------------------------
// 3. Founders Agreement (IP assignment + vesting + restraint)
// ---------------------------------------------------------------------------

export function foundersAgreement(
  startup: StartupCtx,
  founders: MemberCtx[],
): string {
  const founderList = founders
    .map(
      (f) =>
        `- **${f.name}**${f.email ? ` (${f.email})` : ""} — ${f.role}, joined ${fmtDate(f.joinDate)}` +
        (f.sharesIssued ? `, holding ${fmtInt(f.sharesIssued)} ordinary shares` : ""),
    )
    .join("\n");

  return `# Founders Agreement

**Company:** ${startup.startupName} (ACN [insert])
**Incorporated:** ${fmtDate(startup.incorporationDate)}
**Jurisdiction:** ${startup.jurisdiction ?? "AU"}

## 1. Founders

${founderList || "- [No founders recorded]"}

## 2. Roles and time commitment

Each Founder commits to working full-time on the Company's business and not
engaging in any competing activity. Material changes to role, title or time
commitment require unanimous Founder consent.

## 3. Equity and vesting

Founder shares vest over 4 years with a 12-month cliff from each Founder's
start date, in accordance with each Founder's individual Vesting Agreement.
Unvested shares are subject to buy-back as set out in those agreements.

## 4. Intellectual property assignment

Each Founder hereby irrevocably assigns to the Company all right, title and
interest in any intellectual property created by them, alone or with others,
that relates to the Company's business — whether created before, on or after
the date of this agreement. Each Founder agrees to execute such further
documents and do such further acts as the Company may reasonably require to
perfect this assignment.

This assignment is intended to cover copyright, patents, designs, trade marks,
trade secrets, confidential information, and any moral rights consent required
under the *Copyright Act 1968* (Cth) Part IX.

## 5. Decision making

Day-to-day decisions are made by the CEO. Decisions outside the ordinary
course (raising capital, issuing shares, hiring senior staff, changing the
business model, M&A) require approval of a majority of the Founders.

## 6. Restraint of trade

Each Founder agrees that while they hold shares in the Company and for 12
months after ceasing to do so, they will not:

(a) carry on or be involved in any business that competes with the Company in
Australia or any other jurisdiction in which the Company carries on business;

(b) solicit any customer, supplier or employee of the Company.

If a court finds this restraint unreasonable, the parties intend the restraint
to apply for the shorter period / smaller area that is reasonable
(cascading restraint, valid under *Restraints of Trade Act 1976* (NSW)).

## 7. Confidentiality

Each Founder must keep the Company's confidential information confidential
during and after their involvement with the Company.

## 8. Dispute resolution

The parties will attempt to resolve any dispute in good faith. Failing
resolution within 30 days, the dispute is referred to mediation under the
Resolution Institute Mediation Rules before litigation in the courts of NSW.

## 9. Governing law

This agreement is governed by the laws of New South Wales, Australia.

---

Signed by each Founder:

${founders.map((f) => `${f.name}: ____________________ Date: ____________`).join("\n\n")}

> ${DISCLAIMER}
`;
}

// ---------------------------------------------------------------------------
// 4. Cap Table Summary / Shareholder Register
// ---------------------------------------------------------------------------

export function capTableSummary(
  startup: StartupCtx,
  cap: CapTableCtx,
): string {
  const lines: string[] = [];
  lines.push(`# Shareholder Register & Cap Table Summary`);
  lines.push("");
  lines.push(`**${startup.startupName}** (ACN [insert])`);
  lines.push(`**As at:** ${fmtDate(new Date().toISOString().slice(0, 10))}`);
  lines.push(`**Jurisdiction:** ${startup.jurisdiction ?? "AU"}`);
  if (startup.preMoneyValuationAud) {
    lines.push(`**Implied pre-money valuation:** ${fmtAud(startup.preMoneyValuationAud)}`);
  }
  lines.push(`**Total issued shares:** ${fmtInt(cap.totalShares)}`);
  if (cap.esopPoolPct != null) {
    lines.push(`**ESOP pool:** ${cap.esopPoolPct.toFixed(2)}%`);
  }
  lines.push("");
  lines.push("## Register of members (Corporations Act 2001 s169)");
  lines.push("");
  lines.push("| Name | Role | Share class | Shares issued | Options | Ownership % | Fully-diluted % | Value (AUD) |");
  lines.push("|------|------|-------------|--------------:|--------:|------------:|----------------:|------------:|");
  for (const r of cap.rows) {
    lines.push(
      `| ${r.name} | ${r.role} | ${r.shareClass} | ${fmtInt(r.shares)} | ${fmtInt(r.options)} | ${r.ownershipPct.toFixed(2)}% | ${r.fullyDilutedPct.toFixed(2)}% | ${fmtAud(r.valueAud)} |`,
    );
  }
  const totalShares = cap.rows.reduce((s, r) => s + r.shares, 0);
  const totalOptions = cap.rows.reduce((s, r) => s + r.options, 0);
  lines.push("");
  lines.push(`**Totals:** ${fmtInt(totalShares)} shares, ${fmtInt(totalOptions)} options, issued capital ${fmtAud(totalShares * ((startup.preMoneyValuationAud ?? 0) / cap.totalShares))}.`);
  lines.push("");
  lines.push("This register satisfies the form requirements of section 169 of the");
  lines.push("*Corporations Act 2001* (Cth) and must be updated within 28 days of any change.");
  lines.push("");
  lines.push(`> ${DISCLAIMER}`);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export type DocumentKind =
  | "esop_grant"
  | "vesting_agreement"
  | "founders_agreement"
  | "cap_table_summary";

export const DOCUMENT_LABEL: Record<DocumentKind, string> = {
  esop_grant: "ESOP Grant Letter",
  vesting_agreement: "Vesting Agreement",
  founders_agreement: "Founders Agreement",
  cap_table_summary: "Cap Table Summary",
};
