import { describe, it, expect } from "vitest";
import {
  esopGrantLetter,
  vestingAgreement,
  foundersAgreement,
  capTableSummary,
  DOCUMENT_LABEL,
  type StartupCtx,
  type MemberCtx,
  type VestingCtx,
  type CapTableCtx,
  type DocumentKind,
} from "./au-templates";

// Colocated vitest for the pure AU-native equity-document template lib
// (T0097). Pins the AU-statute citations that make these documents
// defensible under the atlassian-standard-mapping-goal P1_dataroom_map
// exit criterion (phase 5 equity artefacts) so future edits cannot
// silently drop a Corporations Act 2001 / ITAA 1997 / Restraints of Trade
// Act 1976 / Copyright Act 1968 anchor without breaking a test.

const DISCLAIMER_ANCHOR =
  "This document is generated by BlockID.au as general information only.";

const STARTUP: StartupCtx = {
  startupName: "Acme Robotics Pty Ltd",
  incorporationDate: "2024-03-15",
  jurisdiction: "AU",
  totalShares: 10_000_000,
  preMoneyValuationAud: 5_000_000,
};

const MEMBER: MemberCtx = {
  name: "Alex Founder",
  email: "alex@acme.example",
  role: "CEO",
  sharesIssued: 4_000_000,
  optionsGranted: 0,
  joinDate: "2024-03-15",
};

const VESTING: VestingCtx = {
  totalShares: 100_000,
  cliffMonths: 12,
  vestMonths: 48,
  scheduleType: "4-year monthly with 12-month cliff",
  startDate: "2025-01-01",
  accelerateOnExit: true,
};

const CAP: CapTableCtx = {
  totalShares: 10_000_000,
  esopPoolPct: 12.5,
  preMoneyValuationAud: 5_000_000,
  rows: [
    {
      name: "Alex Founder",
      role: "CEO",
      shareClass: "Ordinary",
      shares: 4_000_000,
      options: 0,
      ownershipPct: 40,
      fullyDilutedPct: 35,
      valueAud: 2_000_000,
    },
    {
      name: "Sam Cofounder",
      role: "CTO",
      shareClass: "Ordinary",
      shares: 3_000_000,
      options: 250_000,
      ownershipPct: 30,
      fullyDilutedPct: 28.5,
      valueAud: 1_500_000,
    },
  ],
};

describe("esopGrantLetter", () => {
  const doc = esopGrantLetter(STARTUP, MEMBER, VESTING, 2);

  it("renders the startup name in the header", () => {
    expect(doc).toContain("**Acme Robotics Pty Ltd**");
  });

  it("stamps the grantee name, email, and role", () => {
    expect(doc).toContain("**Grantee:** Alex Founder");
    expect(doc).toContain("**Email:** alex@acme.example");
    expect(doc).toContain("**Role:** CEO");
  });

  it("renders total options in en-AU integer format", () => {
    // 100_000 → "100,000" under en-AU
    expect(doc).toContain("**100,000 options**");
  });

  it("renders exercise price in en-AU AUD (rounded to whole dollars)", () => {
    expect(doc).toContain("exercise price of **$2 per share**");
  });

  it("pins the ITAA 1997 Division 83A anchor", () => {
    expect(doc).toContain("Division 83A of the *Income Tax Assessment Act 1997* (Cth)");
  });

  it("pins the startup tax concession anchor (s83A-33)", () => {
    expect(doc).toContain("section 83A-33 of the ITAA 1997");
  });

  it("pins the Corporations Act s1100W ESS disclosure relief anchor", () => {
    expect(doc).toContain("section 1100W of the");
    expect(doc).toContain("*Corporations Act 2001* (Cth)");
  });

  it("pins the ASIC 2022/1021 ESS class instrument", () => {
    expect(doc).toContain("Instrument 2022/1021");
  });

  it("reflects cliff, vest period, and schedule type verbatim", () => {
    expect(doc).toContain("**Cliff:** 12 months");
    expect(doc).toContain("**Total vesting period:** 48 months");
    expect(doc).toContain("4-year monthly with 12-month cliff");
  });

  it("says 'Yes' for acceleration when accelerateOnExit is true", () => {
    expect(doc).toContain("**Acceleration on exit:** Yes");
  });

  it("says 'No.' for acceleration when accelerateOnExit is false", () => {
    const noAccel = esopGrantLetter(
      STARTUP,
      MEMBER,
      { ...VESTING, accelerateOnExit: false },
      0.5,
    );
    expect(noAccel).toContain("**Acceleration on exit:** No.");
  });

  it("omits the email line when grantee has no email", () => {
    const noEmail = esopGrantLetter(
      STARTUP,
      { ...MEMBER, email: null },
      VESTING,
      0.5,
    );
    expect(noEmail).not.toContain("**Email:**");
  });

  it("carries the general-information disclaimer footer", () => {
    expect(doc).toContain(DISCLAIMER_ANCHOR);
  });

  it("renders the grant date in en-AU long format", () => {
    // joinDate 2024-03-15 → "15 March 2024" under en-AU
    expect(doc).toContain("**Grant date:** 15 March 2024");
  });
});

describe("vestingAgreement", () => {
  const doc = vestingAgreement(STARTUP, MEMBER, VESTING);

  it("names both parties in the preamble", () => {
    expect(doc).toContain("**Between:** Acme Robotics Pty Ltd");
    expect(doc).toContain('**And:** Alex Founder ("Holder")');
  });

  it("renders the effective date in en-AU long format", () => {
    // startDate 2025-01-01 → "01 January 2025"
    expect(doc).toContain("**Effective date:** 01 January 2025");
  });

  it("renders total subject shares in en-AU integer format", () => {
    expect(doc).toContain("100,000 ordinary shares");
  });

  it("renders single-trigger acceleration clause when accelerateOnExit is true", () => {
    expect(doc).toContain("single-trigger acceleration");
  });

  it("renders discretionary-only acceleration clause when accelerateOnExit is false", () => {
    const noAccel = vestingAgreement(STARTUP, MEMBER, {
      ...VESTING,
      accelerateOnExit: false,
    });
    expect(noAccel).toContain("No automatic acceleration");
    expect(noAccel).not.toContain("single-trigger acceleration");
  });

  it("pins the Restraints of Trade Act 1976 (NSW) anchor", () => {
    // Source template line-wraps between 'Restraints' and 'of Trade Act 1976'
    expect(doc).toMatch(/\*Restraints\s+of Trade Act 1976\* \(NSW\)/);
  });

  it("prescribes NSW governing law", () => {
    expect(doc).toContain("laws of New South Wales, Australia");
  });

  it("distinguishes good-leaver and bad-leaver buy-back mechanics", () => {
    expect(doc).toContain("**Good leaver**");
    expect(doc).toContain("**Bad leaver**");
    expect(doc).toContain("A$0.001");
  });

  it("carries the general-information disclaimer footer", () => {
    expect(doc).toContain(DISCLAIMER_ANCHOR);
  });
});

describe("foundersAgreement", () => {
  const founders: MemberCtx[] = [
    { ...MEMBER },
    {
      name: "Sam Cofounder",
      email: "sam@acme.example",
      role: "CTO",
      sharesIssued: 3_000_000,
      joinDate: "2024-03-15",
    },
  ];
  const doc = foundersAgreement(STARTUP, founders);

  it("lists every founder in the founder list", () => {
    expect(doc).toContain("**Alex Founder** (alex@acme.example) — CEO");
    expect(doc).toContain("**Sam Cofounder** (sam@acme.example) — CTO");
  });

  it("shows shares issued when present", () => {
    expect(doc).toContain("holding 4,000,000 ordinary shares");
    expect(doc).toContain("holding 3,000,000 ordinary shares");
  });

  it("omits shares clause when sharesIssued is missing / zero", () => {
    const noShares = foundersAgreement(STARTUP, [
      { name: "Dana", role: "Advisor", joinDate: "2024-04-01" },
    ]);
    expect(noShares).not.toContain("holding ");
  });

  it("falls back to '[No founders recorded]' when founder list is empty", () => {
    const empty = foundersAgreement(STARTUP, []);
    expect(empty).toContain("[No founders recorded]");
  });

  it("defaults jurisdiction to AU when unspecified", () => {
    const noJur = foundersAgreement({ ...STARTUP, jurisdiction: undefined }, founders);
    expect(noJur).toContain("**Jurisdiction:** AU");
  });

  it("respects a non-default jurisdiction", () => {
    const nz = foundersAgreement({ ...STARTUP, jurisdiction: "NZ" }, founders);
    expect(nz).toContain("**Jurisdiction:** NZ");
  });

  it("renders the incorporation date in en-AU long format", () => {
    expect(doc).toContain("**Incorporated:** 15 March 2024");
  });

  it("renders '[date]' when incorporationDate is missing", () => {
    const noDate = foundersAgreement(
      { ...STARTUP, incorporationDate: null },
      founders,
    );
    expect(noDate).toContain("**Incorporated:** [date]");
  });

  it("pins the Copyright Act 1968 Part IX moral rights anchor", () => {
    expect(doc).toContain("*Copyright Act 1968* (Cth) Part IX");
  });

  it("pins the Restraints of Trade Act 1976 (NSW) anchor with cascading language", () => {
    expect(doc).toContain("*Restraints of Trade Act 1976* (NSW)");
    expect(doc).toContain("cascading restraint");
  });

  it("prescribes NSW governing law with mediation before litigation", () => {
    expect(doc).toContain("Resolution Institute Mediation Rules");
    expect(doc).toContain("laws of New South Wales, Australia");
  });

  it("emits a signature block for every founder", () => {
    for (const f of founders) {
      expect(doc).toContain(`${f.name}: ____________________ Date: ____________`);
    }
  });

  it("carries the general-information disclaimer footer", () => {
    expect(doc).toContain(DISCLAIMER_ANCHOR);
  });
});

describe("capTableSummary", () => {
  const doc = capTableSummary(STARTUP, CAP);

  it("renders the shareholder register header and startup name", () => {
    expect(doc).toContain("# Shareholder Register & Cap Table Summary");
    expect(doc).toContain("**Acme Robotics Pty Ltd**");
  });

  it("pins the Corporations Act 2001 s169 register-of-members anchor", () => {
    expect(doc).toContain("Corporations Act 2001 s169");
    expect(doc).toContain("*Corporations Act 2001* (Cth)");
  });

  it("prescribes the 28-day update window from s169", () => {
    expect(doc).toContain("28 days");
  });

  it("renders total issued shares in en-AU integer format", () => {
    expect(doc).toContain("**Total issued shares:** 10,000,000");
  });

  it("renders the ESOP pool percentage with 2dp", () => {
    expect(doc).toContain("**ESOP pool:** 12.50%");
  });

  it("omits the ESOP pool line when esopPoolPct is undefined", () => {
    const noEsop = capTableSummary(STARTUP, { ...CAP, esopPoolPct: undefined });
    expect(noEsop).not.toContain("**ESOP pool:**");
  });

  it("renders the pre-money valuation in en-AU AUD", () => {
    expect(doc).toContain("**Implied pre-money valuation:** $5,000,000");
  });

  it("omits the pre-money line when preMoneyValuationAud is null", () => {
    const noVal = capTableSummary(
      { ...STARTUP, preMoneyValuationAud: null },
      { ...CAP, preMoneyValuationAud: null },
    );
    expect(noVal).not.toContain("**Implied pre-money valuation:**");
  });

  it("emits a table row for every cap-table entry", () => {
    for (const r of CAP.rows) {
      expect(doc).toContain(`| ${r.name} | ${r.role} | ${r.shareClass} |`);
    }
  });

  it("emits the markdown table header + alignment row", () => {
    expect(doc).toContain(
      "| Name | Role | Share class | Shares issued | Options | Ownership % | Fully-diluted % | Value (AUD) |",
    );
    expect(doc).toContain("|------|------|-------------|");
  });

  it("carries the general-information disclaimer footer", () => {
    expect(doc).toContain(DISCLAIMER_ANCHOR);
  });

  it("defaults jurisdiction to AU when unspecified", () => {
    const noJur = capTableSummary(
      { ...STARTUP, jurisdiction: undefined },
      CAP,
    );
    expect(noJur).toContain("**Jurisdiction:** AU");
  });

  it("respects a non-default jurisdiction", () => {
    const uk = capTableSummary({ ...STARTUP, jurisdiction: "UK" }, CAP);
    expect(uk).toContain("**Jurisdiction:** UK");
  });

  it("handles an empty rows list without throwing", () => {
    const empty = capTableSummary(STARTUP, { ...CAP, rows: [] });
    expect(empty).toContain("**Totals:** 0 shares, 0 options");
  });
});

describe("DOCUMENT_LABEL registry", () => {
  it("covers every DocumentKind union member", () => {
    const kinds: DocumentKind[] = [
      "esop_grant",
      "vesting_agreement",
      "founders_agreement",
      "cap_table_summary",
    ];
    for (const k of kinds) {
      expect(DOCUMENT_LABEL[k]).toBeTruthy();
      expect(typeof DOCUMENT_LABEL[k]).toBe("string");
    }
  });

  it("has exactly 4 registered document kinds (no orphans, no missing)", () => {
    expect(Object.keys(DOCUMENT_LABEL).sort()).toEqual([
      "cap_table_summary",
      "esop_grant",
      "founders_agreement",
      "vesting_agreement",
    ]);
  });

  it("pins the four human-readable labels", () => {
    expect(DOCUMENT_LABEL.esop_grant).toBe("ESOP Grant Letter");
    expect(DOCUMENT_LABEL.vesting_agreement).toBe("Vesting Agreement");
    expect(DOCUMENT_LABEL.founders_agreement).toBe("Founders Agreement");
    expect(DOCUMENT_LABEL.cap_table_summary).toBe("Cap Table Summary");
  });
});
