// "What investors said" email — pure renderer (G14-S34). Plain text + HTML
// from the stored letter markdown (feedback-letter.ts renderLetter) and the
// three next actions; the send wrapper is `sendFounderFeedbackLetter` in
// lib/email.ts (compliance footer + List-Unsubscribe + provider chain).
//
// No `server-only`, no I/O: the cron route test and this module's own
// test render it without Supabase / SMTP. The markdown → HTML step is a
// deliberately tiny subset (##/### headings, `-` bullets, **bold**, _em_) —
// the letter is generated by our own renderer, never user markdown, and
// every text node is HTML-escaped first.

import type { FeedbackAggregate, FeedbackNextAction } from "@/lib/evaluations/feedback-letter";
import { dimensionTitle } from "@/lib/evaluations/feedback-letter-shared";
import en from "@/lib/i18n/messages/en.json";

const EN = en as Record<string, string>;
const t = (key: string, tokens: Record<string, string | number> = {}) =>
  (EN[key] ?? key).replace(/\{(\w+)\}/g, (_, k: string) => (k in tokens ? String(tokens[k]) : `{${k}}`));

export const FEEDBACK_LETTER_DASHBOARD_PATH = "/dashboard#what-investors-said";

export interface FeedbackLetterEmailInput {
  aggregate: FeedbackAggregate;
  letterMd: string;
  nextActions: readonly FeedbackNextAction[];
  startupName: string | null;
  displayName: string | null;
  /** https://blockid.au — no trailing slash. */
  siteUrl: string;
  /** Spam Act footer (lib/email.ts complianceFooter) — HTML + text twins. */
  footerHtml?: string;
  footerText?: string;
}

export interface RenderedFeedbackLetterEmail {
  subject: string;
  preheader: string;
  html: string;
  text: string;
}

export function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

function inline(s: string): string {
  return escapeHtml(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/(^|\s)_([^_]+)_(?=\s|$)/g, "$1<em>$2</em>");
}

/** Tiny markdown subset → email-safe HTML (inline styles, no external CSS). */
export function letterMarkdownToHtml(md: string): string {
  const out: string[] = [];
  let list: string[] = [];
  const flush = () => {
    if (list.length) {
      out.push(`<ul style="margin:0 0 16px 20px;padding:0;color:#334155;font-size:15px;line-height:1.6;">${list.map((li) => `<li style="margin:0 0 6px 0;">${li}</li>`).join("")}</ul>`);
      list = [];
    }
  };
  for (const raw of md.split("\n")) {
    const line = raw.trimEnd();
    if (!line.trim()) {
      flush();
      continue;
    }
    if (line.startsWith("### ")) {
      flush();
      out.push(`<h3 style="margin:20px 0 8px 0;font-size:16px;font-weight:600;color:#0F172A;">${inline(line.slice(4))}</h3>`);
    } else if (line.startsWith("## ")) {
      flush();
      out.push(`<h2 style="margin:0 0 12px 0;font-size:22px;font-weight:600;color:#0F172A;letter-spacing:-0.01em;">${inline(line.slice(3))}</h2>`);
    } else if (line.startsWith("- ")) {
      list.push(inline(line.slice(2)));
    } else {
      flush();
      out.push(`<p style="margin:0 0 12px 0;color:#334155;font-size:15px;line-height:1.6;">${inline(line)}</p>`);
    }
  }
  flush();
  return out.join("\n");
}

/** Markdown → plain text (strip the marks, keep the structure). */
export function letterMarkdownToText(md: string): string {
  return md
    .split("\n")
    .map((l) => l.replace(/^#{2,3}\s+/, "").replace(/\*\*([^*]+)\*\*/g, "$1").replace(/^_(.+)_$/, "$1"))
    .join("\n")
    .trim();
}

export function renderFounderFeedbackLetterEmail(input: FeedbackLetterEmailInput): RenderedFeedbackLetterEmail {
  const { aggregate, nextActions } = input;
  const startup = input.startupName?.trim() || t("feedback.letter.yourStartup");
  const subject = t("feedback.email.subject", { k: aggregate.k, startup });
  const preheader = t("feedback.email.preheader", { k: aggregate.k, orgs: aggregate.orgCount });
  const url = `${input.siteUrl.replace(/\/$/, "")}${FEEDBACK_LETTER_DASHBOARD_PATH}`;
  const greeting = input.displayName?.trim() ? `Hi ${input.displayName.trim()},` : "Hi,";
  const weakest = aggregate.weakestDim ? dimensionTitle(aggregate.weakestDim, "en") : null;

  const actionsHtml = nextActions.length
    ? `<h3 style="margin:20px 0 8px 0;font-size:16px;font-weight:600;color:#0F172A;">${escapeHtml(t("feedback.block.actions"))}${weakest ? ` — ${escapeHtml(weakest)}` : ""}</h3>
<ol style="margin:0 0 16px 20px;padding:0;color:#334155;font-size:15px;line-height:1.6;">
${nextActions
  .slice(0, 3)
  .map((a) => `<li style="margin:0 0 8px 0;"><strong>${escapeHtml(a.title)}</strong> <span style="color:#16A34A;font-weight:600;">+${a.sviBenefit} SVI pts</span> · ${escapeHtml(a.effort)} effort · ${escapeHtml(a.timeToComplete)}<br><span style="color:#64748B;font-size:13px;">${escapeHtml(a.rationale)}</span></li>`)
  .join("\n")}
</ol>`
    : "";

  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(subject)}</title></head>
<body style="margin:0;padding:0;background:#F1F5F9;color:#0F172A;font-family:Inter,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;">
<span style="display:none;max-height:0;overflow:hidden;color:transparent;">${escapeHtml(preheader)}</span>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F1F5F9;padding:32px 16px;">
  <tr><td align="center">
    <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background:#FFFFFF;border:1px solid #E2E8F0;border-radius:16px;padding:32px;">
      <tr><td>
        <p style="margin:0 0 8px 0;font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:#2563EB;font-weight:600;">BlockID · Startup Value Index</p>
        <p style="margin:0 0 16px 0;color:#334155;font-size:15px;line-height:1.6;">${escapeHtml(greeting)}</p>
        ${letterMarkdownToHtml(input.letterMd)}
        ${actionsHtml}
        <p style="margin:24px 0 8px 0;text-align:center;">
          <a href="${escapeHtml(url)}" style="display:inline-block;background:#2563EB;color:#FFFFFF;font-weight:600;text-decoration:none;padding:12px 24px;border-radius:10px;font-size:15px;">${escapeHtml(t("feedback.email.cta"))}</a>
        </p>
        <p style="margin:8px 0 0 0;color:#64748B;font-size:12px;text-align:center;">${escapeHtml(t("feedback.block.basedOn", { k: aggregate.k, orgs: aggregate.orgCount }))}</p>
      </td></tr>
    </table>
  </td></tr>
</table>
${input.footerHtml ?? ""}
</body></html>`;

  const actionsText = nextActions.length
    ? `\n${t("feedback.block.actions")}${weakest ? ` — ${weakest}` : ""}\n${nextActions
        .slice(0, 3)
        .map((a, i) => `${i + 1}. ${a.title} (+${a.sviBenefit} SVI pts · ${a.effort} effort · ${a.timeToComplete})\n   ${a.rationale}`)
        .join("\n")}\n`
    : "";
  const text = `${greeting}\n\n${letterMarkdownToText(input.letterMd)}\n${actionsText}\n${t("feedback.email.cta")}: ${url}\n${t("feedback.block.basedOn", { k: aggregate.k, orgs: aggregate.orgCount })}${input.footerText ?? ""}`;

  return { subject, preheader, html, text };
}
