export interface DataRoomFolder {
  name: string;
  stage: "idea" | "mvp" | "launch" | "revenue" | "raise";
  priority: "P0" | "P1" | "P2";
  description: string;
  documents: DataRoomDocument[];
}

export interface DataRoomDocument {
  name: string;
  type: "template" | "upload" | "connect";
  format?: string;
  description: string;
  templateContent?: string; // Markdown template content
  connectTo?: string; // e.g. "github", "stripe", "analytics"
}

export const DATA_ROOM_STRUCTURE: DataRoomFolder[] = [
  {
    name: "1. Company Overview",
    stage: "idea",
    priority: "P0",
    description: "Basic company information every investor expects",
    documents: [
      {
        name: "Executive Summary",
        type: "template",
        format: "docx",
        description: "1-page company overview with problem, solution, market, team",
        templateContent: `# Executive Summary — [Company Name]

## The Problem
[Describe the specific problem you're solving. Be concrete — who has this problem and how painful is it?]

## Our Solution
[Explain your solution in 2-3 sentences. What makes it different from existing alternatives?]

## Market Opportunity
- **TAM (Total Addressable Market)**: A$[X]B
- **SAM (Serviceable Addressable Market)**: A$[X]M
- **SOM (Serviceable Obtainable Market)**: A$[X]M in [timeframe]

## Business Model
[How do you make money? What's your pricing?]

## Traction
- [Key metric 1, e.g. "500 users, 15% MoM growth"]
- [Key metric 2, e.g. "A$12K MRR"]
- [Key metric 3, e.g. "3 enterprise pilots"]

## The Team
- **[Founder Name]** — CEO. [1-line background]
- **[Co-founder Name]** — CTO. [1-line background]

## The Ask
- **Raising**: A$[amount] [instrument type, e.g. "SAFE at $5M cap"]
- **Use of funds**: [Top 3 priorities]
- **Timeline**: [Expected close date]

---
*Generated by BlockID.au — Valuation. Ownership. Execution. Growth.*`,
      },
      {
        name: "Pitch Deck",
        type: "upload",
        format: "pdf",
        description: "12-slide investor presentation",
      },
      {
        name: "One-Pager",
        type: "template",
        format: "docx",
        description: "Quick reference sheet for investors",
        templateContent: `# [Company Name] — One-Pager

**Tagline**: [One sentence that explains what you do]
**Website**: [URL]
**Stage**: [Idea / MVP / Revenue / Raising]
**Founded**: [Year]
**Location**: [City, State, Australia]

| Metric | Value |
|--------|-------|
| MRR | A$[X] |
| Users | [X] |
| Growth | [X]% MoM |
| Burn Rate | A$[X]/mo |
| Runway | [X] months |

**Team**: [Names + roles]
**Raising**: A$[amount] on [SAFE/Priced Round]

---
*BlockID.au*`,
      },
    ],
  },
  {
    name: "2. Financial",
    stage: "mvp",
    priority: "P0",
    description: "Financial data, projections, and metrics",
    documents: [
      {
        name: "Financial Model",
        type: "template",
        format: "xlsx",
        description: "3-year revenue projection with assumptions",
        templateContent: `# Financial Model Template

## Revenue Projections (3 Years)

| Quarter | MRR | Customers | ARPU | Churn | Growth |
|---------|-----|-----------|------|-------|--------|
| Q1 Y1 | A$[X] | [X] | A$[X] | [X]% | [X]% |
| Q2 Y1 | | | | | |
| Q3 Y1 | | | | | |
| Q4 Y1 | | | | | |
| Q1 Y2 | | | | | |
| ... | | | | | |

## Key Assumptions
- Customer acquisition cost (CAC): A$[X]
- Lifetime value (LTV): A$[X]
- LTV:CAC ratio: [X]:1
- Monthly burn rate: A$[X]
- Runway at current burn: [X] months

## Use of Funds (if raising)
| Category | Amount | % of Raise |
|----------|--------|-----------|
| Engineering | A$[X] | [X]% |
| Sales & Marketing | A$[X] | [X]% |
| Operations | A$[X] | [X]% |

---
*BlockID.au Financial Template*`,
      },
      {
        name: "Revenue Proof",
        type: "connect",
        description: "Connect Stripe or upload bank statements",
        connectTo: "stripe",
      },
      {
        name: "Bank Statements",
        type: "upload",
        format: "pdf",
        description: "Last 6 months of business bank statements",
      },
    ],
  },
  {
    name: "3. Legal & Corporate",
    stage: "mvp",
    priority: "P1",
    description: "Corporate structure, agreements, and compliance",
    documents: [
      {
        name: "Shareholders Agreement",
        type: "template",
        format: "docx",
        description: "Governs shareholder rights, transfer restrictions, and dispute resolution",
        templateContent: `# Shareholders Agreement — Key Terms Template

## Parties
- [Shareholder 1]: [X]% ordinary shares
- [Shareholder 2]: [X]% ordinary shares
- [ESOP Pool]: [X]% reserved

## Key Provisions

### Vesting
- Standard 4-year vesting with 1-year cliff
- [X]% vests at cliff, remainder monthly
- Accelerated vesting on [single/double] trigger

### Transfer Restrictions
- Board approval required for all share transfers
- Right of first refusal for existing shareholders
- Tag-along and drag-along rights included

### Decision Making
- Ordinary resolutions: >50% of votes
- Special resolutions: >75% of votes
- Reserved matters requiring unanimous consent: [list]

### Good Leaver / Bad Leaver
- Good leaver: retains vested shares at fair market value
- Bad leaver: forfeits unvested shares, vested shares repurchased at [cost/FMV]

---
*Template only — seek legal advice. BlockID.au*`,
      },
      {
        name: "ASIC Registration",
        type: "upload",
        format: "pdf",
        description: "Company extract from ASIC showing directors, shares, ABN",
      },
      {
        name: "Cap Table",
        type: "connect",
        description: "Use BlockID cap table tool",
        connectTo: "blockid-captable",
      },
    ],
  },
  {
    name: "4. Product & Technical",
    stage: "mvp",
    priority: "P1",
    description: "Product evidence, technical documentation",
    documents: [
      {
        name: "Product Demo",
        type: "upload",
        format: "mp4",
        description: "2-5 minute product walkthrough video",
      },
      {
        name: "Technical Architecture",
        type: "template",
        format: "docx",
        description: "System architecture overview",
        templateContent: `# Technical Architecture — [Company Name]

## Stack Overview
- **Frontend**: [e.g. React, Next.js]
- **Backend**: [e.g. Node.js, Python]
- **Database**: [e.g. PostgreSQL, Supabase]
- **Hosting**: [e.g. AWS, GCP, Vercel]
- **CI/CD**: [e.g. GitHub Actions, GitLab CI]

## Key Metrics
- Uptime: [X]%
- Response time (p95): [X]ms
- Active users: [X]
- Data processed: [X]/month

## Security
- [ ] SSL/TLS encryption
- [ ] Authentication (OAuth2/JWT)
- [ ] Data encryption at rest
- [ ] Regular backups
- [ ] Penetration testing

---
*BlockID.au*`,
      },
      {
        name: "GitHub Repository",
        type: "connect",
        description: "Link source code for product depth verification",
        connectTo: "github",
      },
    ],
  },
  {
    name: "5. Market & Traction",
    stage: "launch",
    priority: "P1",
    description: "Market validation, customer evidence, analytics",
    documents: [
      {
        name: "Customer List",
        type: "template",
        format: "xlsx",
        description: "Key customers with contract values",
        templateContent: `# Customer List

| Customer | Type | ACV | Contract Start | Status | Reference? |
|----------|------|-----|----------------|--------|------------|
| [Name] | [Enterprise/SMB/Startup] | A$[X] | [Date] | Active | Yes/No |
| | | | | | |

## Key Stats
- Total customers: [X]
- Enterprise: [X] | SMB: [X] | Startup: [X]
- Total ACV: A$[X]
- Net revenue retention: [X]%

---
*BlockID.au*`,
      },
      {
        name: "Google Analytics",
        type: "connect",
        description: "Connect GA4 for user traction verification",
        connectTo: "analytics",
      },
      {
        name: "Customer Testimonials",
        type: "upload",
        format: "pdf",
        description: "Written testimonials or case studies from customers",
      },
    ],
  },
  {
    name: "6. Team",
    stage: "idea",
    priority: "P0",
    description: "Founder profiles, team structure, advisors",
    documents: [
      {
        name: "Team Bios",
        type: "template",
        format: "docx",
        description: "Founder and key team member profiles",
        templateContent: `# Team — [Company Name]

## Founders

### [Name] — CEO
- **Background**: [2-3 sentences on relevant experience]
- **Education**: [Degree, University]
- **LinkedIn**: [URL]
- **Key achievement**: [One impressive thing]

### [Name] — CTO
- **Background**: [2-3 sentences]
- **Education**: [Degree, University]
- **LinkedIn**: [URL]
- **Key achievement**: [One thing]

## Advisors

### [Name] — [Area of expertise]
- **Background**: [1 sentence]
- **Involvement**: [Hours/month, equity if any]

## Hiring Plan
| Role | Priority | Timeline | Budget |
|------|----------|----------|--------|
| [Role] | P0 | [Q] | A$[X]/yr |

---
*BlockID.au*`,
      },
      {
        name: "LinkedIn Profiles",
        type: "connect",
        description: "Link founder LinkedIn profiles",
        connectTo: "linkedin",
      },
    ],
  },
];

// Get folders relevant to a startup stage
export function getFoldersForStage(stage: number): DataRoomFolder[] {
  const stageMap: Record<number, string[]> = {
    0: ["idea"],
    1: ["idea", "mvp"],
    2: ["idea", "mvp"],
    3: ["idea", "mvp", "launch"],
    4: ["idea", "mvp", "launch", "revenue"],
    5: ["idea", "mvp", "launch", "revenue", "raise"],
    6: ["idea", "mvp", "launch", "revenue", "raise"],
    7: ["idea", "mvp", "launch", "revenue", "raise"],
  };
  const stages = stageMap[stage] ?? ["idea"];
  return DATA_ROOM_STRUCTURE.filter(f => stages.includes(f.stage));
}

// Get all template documents
export function getTemplateDocuments(): DataRoomDocument[] {
  return DATA_ROOM_STRUCTURE.flatMap(f => f.documents.filter(d => d.type === "template"));
}
