// ============================================================
// Data Room Templates — Professional 10-Section Structure
// BlockID Startup Index™ — Proprietary Knowhow
// Updated: 2026-Q2 — Version 2
// Template variables use [VARIABLE_NAME] notation
// ============================================================

export interface DataRoomFolder {
  name: string;
  section: string;
  stage: "idea" | "mvp" | "launch" | "revenue" | "raise";
  priority: "P0" | "P1" | "P2";
  description: string;
  investorImpact: "critical" | "high" | "medium" | "low";
  documents: DataRoomDocument[];
}

export interface DataRoomDocument {
  name: string;
  type: "template" | "upload" | "connect" | "auto";
  format?: string;
  description: string;
  priority: "P0" | "P1" | "P2";
  investorType?: string[];
  templateContent?: string;
  connectTo?: string;
  dueDiligenceNotes?: string;
}

// ─────────────────────────────────────────────────────────────
// Template content strings — use [VARIABLE] placeholder notation
// ─────────────────────────────────────────────────────────────

const EXEC_SUMMARY_TEMPLATE = `# Executive Summary — [STARTUP_NAME]

**ABN:** [ABN] | **ACN:** [ACN] | **Incorporated:** [INCORPORATED_DATE]
**Website:** [WEBSITE] | **Stage:** [STAGE] | **SVI Score:** [SVI_SCORE]/1000

---

## The Problem
[PROBLEM_STATEMENT]

## Our Solution
[SOLUTION_STATEMENT]

## Why Now
[WHY_NOW]

## Market Opportunity
| Market | Size | Source |
|--------|------|--------|
| TAM (Total Addressable) | A$[TAM] | [TAM_SOURCE] |
| SAM (Serviceable Available) | A$[SAM] | |
| SOM (Obtainable — Y3 target) | A$[SOM] | |

## Business Model
**Revenue type:** [REVENUE_MODEL]
**Pricing:** [PRICING]
**Gross margin:** [GROSS_MARGIN]%

## Traction (as of [REPORT_DATE])
- [TRACTION_1]
- [TRACTION_2]
- [TRACTION_3]

## The Team
- **[FOUNDER_1_NAME]** — [FOUNDER_1_ROLE]. [FOUNDER_1_BIO]
- **[FOUNDER_2_NAME]** — [FOUNDER_2_ROLE]. [FOUNDER_2_BIO]

## The Ask
- **Raising:** A$[RAISE_AMOUNT] via [INSTRUMENT]
- **Pre-money valuation:** A$[PRE_MONEY] (BlockID SVI-calibrated)
- **Use of funds:** [USE_OF_FUNDS]
- **Runway post-raise:** [RUNWAY_MONTHS] months
- **Target close:** [TARGET_CLOSE]

---
*Generated by BlockID.au — Valuation. Ownership. Growth.*
*BlockID Startup Index™ Score: [SVI_SCORE]/1000*`;

const CAP_TABLE_TEMPLATE = `# Cap Table Summary — [STARTUP_NAME]
**Date:** [REPORT_DATE]
**Total Shares on Issue:** [TOTAL_SHARES]
**Share Price (last round):** A$[LAST_SHARE_PRICE]
**Implied Pre-money Valuation:** A$[PRE_MONEY]

## Shareholding Table
| Shareholder | Class | Shares | % Pre | % Post-[INSTRUMENT] |
|-------------|-------|--------|-------|---------------------|
| [FOUNDER_1] | Ordinary A | [SHARES_1] | [PCT_1]% | [POST_PCT_1]% |
| [FOUNDER_2] | Ordinary A | [SHARES_2] | [PCT_2]% | [POST_PCT_2]% |
| ESOP Pool | Options | [ESOP_SHARES] | [ESOP_PCT]% | [ESOP_POST_PCT]% |
| New Investor | Ordinary | [NEW_SHARES] | 0% | [INVESTOR_PCT]% |
| **TOTAL** | | [TOTAL_POST] | 100% | 100% |

## Dilution Summary
- Pre-money: A$[PRE_MONEY]
- Investment: A$[RAISE_AMOUNT]
- Post-money: A$[POST_MONEY]
- Investor equity: [INVESTOR_PCT]%

*Generated by BlockID.au Cap Table Tool*`;

const SHAREHOLDERS_AGREEMENT_TEMPLATE = `# Shareholders Agreement — Key Terms Summary
**Company:** [STARTUP_NAME] Pty Ltd (ACN [ACN])
**Date:** [AGREEMENT_DATE]

## Parties
- [SHAREHOLDER_1]: [SHARES_1] shares ([PCT_1]%) — [CLASS_1] shares
- [SHAREHOLDER_2]: [SHARES_2] shares ([PCT_2]%) — [CLASS_2] shares

## Share Classes
| Class | Votes | Dividends | Liquidation Preference |
|-------|-------|-----------|----------------------|
| Ordinary A | 1 per share | Pro-rata | 1x non-participating |
| Ordinary B | 10 per share (founders) | Pro-rata | 1x non-participating |

## Vesting
- Standard: 4 years, 1-year cliff
- Post-cliff: Monthly vesting of remaining 75%
- Acceleration: [ACCELERATION_TYPE] trigger

## Reserved Matters (Require [REQUIRED_MAJORITY]%)
- Issuing new share classes
- Amending constitution
- Change of control transactions
- Winding up / liquidation

## Transfer Restrictions
- Board approval required
- Right of first refusal: 30-day window
- Tag-along: Minority shareholders may join any sale above [TAG_ALONG_THRESHOLD]%
- Drag-along: [DRAG_ALONG_THRESHOLD]% majority may force all shareholders

*Template summary — full agreement in PDF. Legal advice recommended.*`;

const FINANCIAL_MODEL_TEMPLATE = `# Financial Model — [STARTUP_NAME]
**Report Date:** [REPORT_DATE] | **Currency:** AUD

---

## Revenue Projections

### Key Assumptions
| Assumption | Year 1 | Year 2 | Year 3 |
|------------|--------|--------|--------|
| Starting MRR | A$[START_MRR] | A$[Y1_END_MRR] | A$[Y2_END_MRR] |
| Monthly Growth Rate | [Y1_GROWTH]% | [Y2_GROWTH]% | [Y3_GROWTH]% |
| Churn Rate | [Y1_CHURN]% | [Y2_CHURN]% | [Y3_CHURN]% |
| ARPU | A$[Y1_ARPU] | A$[Y2_ARPU] | A$[Y3_ARPU] |
| Gross Margin | [Y1_GM]% | [Y2_GM]% | [Y3_GM]% |

### P&L Summary
| | FY1 | FY2 | FY3 |
|-|-----|-----|-----|
| Revenue | A$[R1] | A$[R2] | A$[R3] |
| COGS | (A$[C1]) | (A$[C2]) | (A$[C3]) |
| Gross Profit | A$[GP1] | A$[GP2] | A$[GP3] |
| Gross Margin | [GM1]% | [GM2]% | [GM3]% |
| S&M | (A$[SM1]) | (A$[SM2]) | (A$[SM3]) |
| R&D / Engineering | (A$[RD1]) | (A$[RD2]) | (A$[RD3]) |
| G&A | (A$[GA1]) | (A$[GA2]) | (A$[GA3]) |
| EBITDA | (A$[EB1]) | (A$[EB2]) | A$[EB3] |
| Net Cash Burn | A$[BURN1]/mo | A$[BURN2]/mo | A$[BURN3]/mo |

## Unit Economics
| Metric | Current | Y3 Target |
|--------|---------|-----------|
| CAC | A$[CAC] | A$[CAC_TARGET] |
| LTV | A$[LTV] | A$[LTV_TARGET] |
| LTV:CAC | [LTV_CAC_RATIO]x | [LTV_CAC_TARGET]x |
| Payback Period | [PAYBACK] months | [PAYBACK_TARGET] months |
| NRR | [NRR]% | [NRR_TARGET]% |

## Use of Funds (A$[RAISE_AMOUNT] raise)
| Category | Amount | % | Milestone |
|----------|--------|---|-----------|
| Engineering / Product | A$[FUND_ENG] | [PCT_ENG]% | [MILESTONE_ENG] |
| Sales & Marketing | A$[FUND_SM] | [PCT_SM]% | [MILESTONE_SM] |
| Operations | A$[FUND_OPS] | [PCT_OPS]% | [MILESTONE_OPS] |
| Reserve | A$[FUND_RES] | [PCT_RES]% | |
| **Total** | **A$[RAISE_AMOUNT]** | **100%** | |

## Valuation Summary (BlockID Multi-Method)
| Method | Valuation |
|--------|-----------|
| SVI-Calibrated | A$[VALUATION_SVI] |
| Revenue Multiple ([REV_MULTIPLE]x ARR) | A$[VALUATION_REV_MULT] |
| DCF ([DISCOUNT_RATE]% discount rate) | A$[VALUATION_DCF] |
| Comparable Transactions | A$[VALUATION_COMPS] |
| **Recommended Pre-money** | **A$[PRE_MONEY]** |

*BlockID Startup Index™ SVI Score: [SVI_SCORE]/1000*
*Confidence: [VALUATION_CONFIDENCE]%*`;

const TECH_ARCH_TEMPLATE = `# Technical Architecture — [STARTUP_NAME]
**Version:** [VERSION] | **Date:** [REPORT_DATE]

## Stack Overview
| Layer | Technology | Rationale |
|-------|------------|-----------|
| Frontend | [FRONTEND_STACK] | [FRONTEND_REASON] |
| Backend | [BACKEND_STACK] | [BACKEND_REASON] |
| Database | [DB_STACK] | [DB_REASON] |
| Infrastructure | [INFRA_STACK] | [INFRA_REASON] |

## Key Technical Metrics
| Metric | Current | Target (12mo) |
|--------|---------|---------------|
| System uptime | [UPTIME]% | 99.9% |
| API response (p95) | [P95]ms | <200ms |
| Monthly active users | [MAU] | [MAU_TARGET] |
| Test coverage | [TEST_COVERAGE]% | >80% |

## Security Posture
- [ ] SSL/TLS (A+ on SSL Labs)
- [ ] OWASP Top 10 addressed
- [ ] Authentication: [AUTH_TYPE]
- [ ] Data encryption at rest
- [ ] Regular automated backups ([BACKUP_FREQ])
- [ ] Penetration test: [PEN_TEST_DATE]
- [ ] Privacy Policy: Australian Privacy Act 1988 compliant`;

const TRACTION_TEMPLATE = `# Traction Summary — [STARTUP_NAME]
**As of:** [REPORT_DATE] | **Powered by BlockID.au**

## Key Metrics
| Metric | [PREV_MONTH] | [CURRENT_MONTH] | MoM Growth |
|--------|-------------|----------------|-----------|
| Monthly Active Users | [MAU_PREV] | [MAU_CURRENT] | [MAU_GROWTH]% |
| Revenue (MRR) | A$[MRR_PREV] | A$[MRR_CURRENT] | [MRR_GROWTH]% |
| Customers | [CUST_PREV] | [CUST_CURRENT] | [CUST_GROWTH]% |
| NPS Score | [NPS_PREV] | [NPS_CURRENT] | |
| Churn Rate | [CHURN_PREV]% | [CHURN_CURRENT]% | |
| NRR | [NRR_PREV]% | [NRR_CURRENT]% | |

## Milestones Achieved
- [MILESTONE_DATE_1]: [MILESTONE_1]
- [MILESTONE_DATE_2]: [MILESTONE_2]
- [MILESTONE_DATE_3]: [MILESTONE_3]

*Data sources: [DATA_SOURCES]*`;

const CUSTOMER_LIST_TEMPLATE = `# Customer List — [STARTUP_NAME] (CONFIDENTIAL)
**Date:** [REPORT_DATE] | **Total Customers:** [TOTAL_CUSTOMERS]

| # | Customer Name | Segment | ACV (A$) | Contract Start | Status | Reference? |
|---|--------------|---------|----------|----------------|--------|-----------|
| 1 | [CUSTOMER_1] | [SEGMENT_1] | [ACV_1] | [START_1] | Active | Yes |
| 2 | [CUSTOMER_2] | [SEGMENT_2] | [ACV_2] | [START_2] | Active | Yes |
| 3 | [CUSTOMER_3] | [SEGMENT_3] | [ACV_3] | [START_3] | Active | No |

## Summary Statistics
- Total ARR: A$[TOTAL_ARR]
- Average ACV: A$[AVG_ACV]
- Net Revenue Retention: [NRR]%
- Churn rate (LTM): [CHURN]%`;

const MARKET_SIZE_TEMPLATE = `# Market Size Analysis — [STARTUP_NAME]
**Market:** [MARKET_NAME] | **Geography:** [GEOGRAPHY]

## Top-Down Analysis
| Market Level | Size | Source | Year |
|-------------|------|--------|------|
| TAM (Global) | US$[TAM_GLOBAL] | [TAM_SOURCE] | [TAM_YEAR] |
| TAM (AU/ANZ) | A$[TAM_AU] | [TAM_AU_SOURCE] | |
| SAM | A$[SAM] | [SAM_SOURCE] | |
| SOM (Year 3) | A$[SOM] | Internal | |

## Bottom-Up Validation
- **Total target businesses/users in AU:** [TOTAL_ICP]
- **Reachable via our channels:** [REACHABLE] ([REACH_PCT]%)
- **Conversion rate assumption:** [CONV_RATE]%
- **ARPU:** A$[ARPU]/year
- **SOM:** [REACHABLE] x [CONV_RATE]% x A$[ARPU] = A$[SOM_CALC]

## Market Growth Rate
[MARKET_NAME] is growing at [CAGR]% CAGR ([CAGR_SOURCE], [CAGR_YEAR])`;

const TEAM_TEMPLATE = `# Team — [STARTUP_NAME]

## Founders

### [FOUNDER_1_NAME] — [FOUNDER_1_TITLE]
- **Background:** [FOUNDER_1_BACKGROUND]
- **Education:** [FOUNDER_1_EDUCATION]
- **LinkedIn:** [FOUNDER_1_LINKEDIN]
- **Domain expertise:** [FOUNDER_1_EXPERTISE]
- **Key achievement:** [FOUNDER_1_ACHIEVEMENT]
- **Equity:** [FOUNDER_1_EQUITY]% (Vesting: 4yr/1yr cliff)

### [FOUNDER_2_NAME] — [FOUNDER_2_TITLE]
- **Background:** [FOUNDER_2_BACKGROUND]
- **Education:** [FOUNDER_2_EDUCATION]
- **LinkedIn:** [FOUNDER_2_LINKEDIN]
- **Key achievement:** [FOUNDER_2_ACHIEVEMENT]
- **Equity:** [FOUNDER_2_EQUITY]% (Vesting: 4yr/1yr cliff)

## Key Advisors

### [ADVISOR_1_NAME] — [ADVISOR_1_EXPERTISE]
- **Background:** [ADVISOR_1_BIO]
- **Involvement:** [ADVISOR_1_HOURS] hours/month
- **Equity:** [ADVISOR_1_EQUITY]% ([ADVISOR_1_VESTING])

## Org Chart
[Insert org chart diagram]

## Hiring Plan
| Role | Priority | Quarter | Budget (A$/yr) |
|------|----------|---------|----------------|
| [ROLE_1] | P0 | [Q1] | [SALARY_1] |
| [ROLE_2] | P1 | [Q2] | [SALARY_2] |`;

const IP_REGISTER_TEMPLATE = `# IP Register — [STARTUP_NAME]

## Trademarks
| Mark | Class | Territory | Application # | Status | Filing Date |
|------|-------|-----------|--------------|--------|-------------|
| [BRAND_NAME] | 42 (Software) | Australia | [TM_NUMBER] | [TM_STATUS] | [TM_DATE] |

## Domain Names
- [DOMAIN_1] — Registered to: [STARTUP_NAME] Pty Ltd — Expires: [EXPIRY_1]
- [DOMAIN_2] — Registered to: [STARTUP_NAME] Pty Ltd — Expires: [EXPIRY_2]

## Open Source Compliance
License audit completed: [LICENSE_AUDIT_DATE]
**No viral/copyleft licenses in production code:** [NO_VIRAL_LICENSES]

## IP Assignment
All founders and contractors have signed IP assignment deeds.
Key assignors:
- [FOUNDER_1_NAME] — Deed dated [DEED_DATE_1]
- [FOUNDER_2_NAME] — Deed dated [DEED_DATE_2]`;

const GTM_TEMPLATE = `# Go-to-Market Strategy — [STARTUP_NAME]
**Version:** [VERSION] | **Target:** [GTM_TARGET]

## Ideal Customer Profile (ICP)
- **Company type:** [ICP_COMPANY_TYPE]
- **Size:** [ICP_SIZE] employees / A$[ICP_REVENUE] revenue
- **Industry:** [ICP_INDUSTRY]
- **Geography:** [ICP_GEO]
- **Decision maker:** [ICP_DECISION_MAKER]
- **Pain point:** [ICP_PAIN]

## Acquisition Channels
| Channel | Cost/Lead | Conv. Rate | CAC | % of Pipeline |
|---------|-----------|-----------|-----|---------------|
| [CHANNEL_1] | A$[C1_CPL] | [C1_CONV]% | A$[C1_CAC] | [C1_PCT]% |
| [CHANNEL_2] | A$[C2_CPL] | [C2_CONV]% | A$[C2_CAC] | [C2_PCT]% |

## Sales Motion
- **Motion type:** [SALES_MOTION] (PLG / Top-down / Hybrid)
- **Sales cycle:** [SALES_CYCLE] days average
- **ACV range:** A$[ACV_MIN] — A$[ACV_MAX]`;

const INVESTOR_FAQ_TEMPLATE = `# Investor FAQ — [STARTUP_NAME]
*Pre-empting common due diligence questions*

**Q: Why are you raising now?**
[RAISING_REASON]

**Q: What's the biggest risk to the business?**
[BIGGEST_RISK]
*Mitigation:* [RISK_MITIGATION]

**Q: Why will you win vs. competitors?**
[WHY_WIN]

**Q: What does the money get you to?**
Raising A$[RAISE_AMOUNT] gets us to:
- [MILESTONE_1]
- [MILESTONE_2]
- [MILESTONE_3]

**Q: What's the next fundraise and when?**
[NEXT_RAISE]

**Q: How did you arrive at this valuation?**
[VALUATION_RATIONALE]
*BlockID SVI Score: [SVI_SCORE]/1000 — Recommended pre-money: A$[PRE_MONEY]*

**Q: Do you have any IP or compliance issues?**
[IP_COMPLIANCE_ANSWER]`;

const DD_CHECKLIST_TEMPLATE = `# Due Diligence Checklist — [STARTUP_NAME]
**Generated:** [REPORT_DATE] | **SVI Score:** [SVI_SCORE]/1000

## Data Room Completeness: [COMPLETENESS_SCORE]%

### Section Summary
| Section | Documents | Complete | % |
|---------|-----------|----------|---|
| Corporate & Legal | [CORP_TOTAL] | [CORP_COMPLETE] | [CORP_PCT]% |
| Cap Table & Equity | [CAP_TOTAL] | [CAP_COMPLETE] | [CAP_PCT]% |
| Financial Projections | [FIN_TOTAL] | [FIN_COMPLETE] | [FIN_PCT]% |
| Product & Technology | [PROD_TOTAL] | [PROD_COMPLETE] | [PROD_PCT]% |
| Market & Traction | [MKT_TOTAL] | [MKT_COMPLETE] | [MKT_PCT]% |
| Team & Advisors | [TEAM_TOTAL] | [TEAM_COMPLETE] | [TEAM_PCT]% |
| IP & Compliance | [IP_TOTAL] | [IP_COMPLETE] | [IP_PCT]% |
| Contracts & Agreements | [CONT_TOTAL] | [CONT_COMPLETE] | [CONT_PCT]% |
| Strategy & Roadmap | [STRAT_TOTAL] | [STRAT_COMPLETE] | [STRAT_PCT]% |
| References & DD | [REF_TOTAL] | [REF_COMPLETE] | [REF_PCT]% |

*Generated by BlockID.au — The Australian Startup Intelligence Platform*
*BlockID Startup Index™ is a proprietary valuation methodology*`;

// ─────────────────────────────────────────────────────────────
// FULL 10-SECTION PROFESSIONAL DATA ROOM
// ─────────────────────────────────────────────────────────────
export const DATA_ROOM_STRUCTURE: DataRoomFolder[] = [

  // ── SECTION 1: CORPORATE & LEGAL ─────────────────────────
  {
    name: "1. Corporate & Legal",
    section: "corporate",
    stage: "idea",
    priority: "P0",
    description: "ASIC registration, company structure, and foundational legal documents",
    investorImpact: "critical",
    documents: [
      {
        name: "Executive Summary",
        type: "template",
        format: "pdf",
        priority: "P0",
        description: "1-page company overview — problem, solution, market, team, ask",
        templateContent: EXEC_SUMMARY_TEMPLATE,
      },
      {
        name: "Company Extract (ASIC)",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "Current ASIC company extract showing directors, shareholders, ABN, ACN",
        dueDiligenceNotes: "Must be <30 days old for active raises",
      },
      {
        name: "Certificate of Registration",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "ASIC certificate proving Pty Ltd entity exists",
      },
      {
        name: "Constitution or Replaceable Rules",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "Company constitution or confirmation of replaceable rules",
      },
      {
        name: "Pitch Deck",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "12-15 slide investor presentation",
        dueDiligenceNotes: "Problem, Solution, Market, Product, Traction, Team, Financials, Ask",
      },
      {
        name: "Register of Members (Share Register)",
        type: "connect",
        priority: "P0",
        description: "Current shareholder register from BlockID cap table",
        connectTo: "blockid-captable",
      },
      {
        name: "Register of Directors & Secretaries",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "All current directors with appointment dates and consent forms",
      },
      {
        name: "Board Minutes (Last 12 months)",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "Signed minutes of all board meetings",
        dueDiligenceNotes: "Key decisions must be minuted. Investors verify governance quality.",
      },
    ],
  },

  // ── SECTION 2: CAP TABLE & EQUITY ────────────────────────
  {
    name: "2. Cap Table & Equity",
    section: "captable",
    stage: "idea",
    priority: "P0",
    description: "Ownership structure, vesting, ESOP, and all equity instruments",
    investorImpact: "critical",
    documents: [
      {
        name: "Cap Table (Current + Post-raise)",
        type: "connect",
        format: "xlsx",
        priority: "P0",
        description: "Full cap table showing current and post-raise ownership",
        connectTo: "blockid-captable",
        templateContent: CAP_TABLE_TEMPLATE,
      },
      {
        name: "Founder Agreements & Vesting Schedules",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "All founder agreements including vesting, IP assignment, non-compete",
        dueDiligenceNotes: "4-year vesting with 1-year cliff is standard AU market expectation",
      },
      {
        name: "Shareholders Agreement",
        type: "template",
        format: "docx",
        priority: "P0",
        description: "Executed shareholders agreement with all key provisions",
        templateContent: SHAREHOLDERS_AGREEMENT_TEMPLATE,
      },
      {
        name: "SAFE / Convertible Note Agreements",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "All outstanding SAFEs, convertible notes, and warrants",
        dueDiligenceNotes: "Must include: cap, discount, pro-rata rights, MFN clause",
      },
      {
        name: "IP Assignment Deeds (Founders)",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "Signed IP assignment from each founder to the company",
        dueDiligenceNotes: "Missing IP assignment = major red flag. Must predate company existence work.",
      },
      {
        name: "ESOP Plan Rules",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "Employee Share Option Plan documentation and trust deed",
        dueDiligenceNotes: "ESOP pool size, eligibility, and exercise conditions key for investors",
      },
      {
        name: "Option / Warrant Register",
        type: "connect",
        priority: "P1",
        description: "All outstanding options, warrants, and convertible instruments",
        connectTo: "blockid-captable",
      },
    ],
  },

  // ── SECTION 3: FINANCIAL PROJECTIONS ─────────────────────
  {
    name: "3. Financial Projections",
    section: "financial",
    stage: "mvp",
    priority: "P0",
    description: "Historical financials, projections, unit economics, and valuation",
    investorImpact: "critical",
    documents: [
      {
        name: "Financial Model (3-Year Projection)",
        type: "template",
        format: "xlsx",
        priority: "P0",
        description: "Full P&L, cash flow, and balance sheet projection with assumptions",
        templateContent: FINANCIAL_MODEL_TEMPLATE,
      },
      {
        name: "P&L Statement (Historical)",
        type: "upload",
        format: "xlsx",
        priority: "P0",
        description: "Profit & Loss for all operating periods (accountant-prepared preferred)",
        dueDiligenceNotes: "Last 24 months minimum for Series A.",
      },
      {
        name: "Bank Statements (6 months)",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "Business bank account statements showing cash position and runway",
      },
      {
        name: "Cash Flow Statement",
        type: "upload",
        format: "xlsx",
        priority: "P0",
        description: "12-month cash flow showing burn rate and runway",
      },
      {
        name: "Revenue Proof (Stripe / Bank)",
        type: "connect",
        priority: "P0",
        description: "Connect Stripe or upload payment proof showing actual revenue",
        connectTo: "stripe",
      },
      {
        name: "Valuation Report (BlockID)",
        type: "auto",
        priority: "P0",
        description: "Auto-generated multi-method valuation from BlockID platform",
        connectTo: "blockid-valuation",
      },
      {
        name: "Balance Sheet",
        type: "upload",
        format: "xlsx",
        priority: "P1",
        description: "Current assets, liabilities, and equity position",
      },
      {
        name: "Tax Returns & ATO Compliance",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "Company tax returns lodged with ATO + BAS statements",
        dueDiligenceNotes: "Investors verify tax compliance — missing returns are red flags",
      },
    ],
  },

  // ── SECTION 4: PRODUCT & TECHNOLOGY ──────────────────────
  {
    name: "4. Product & Technology",
    section: "product",
    stage: "mvp",
    priority: "P1",
    description: "Product evidence, technical architecture, security, and roadmap",
    investorImpact: "high",
    documents: [
      {
        name: "Product Demo Video",
        type: "upload",
        format: "mp4",
        priority: "P0",
        description: "2-5 minute product walkthrough showing core value proposition",
        dueDiligenceNotes: "Most-viewed asset in seed data rooms. Invest in quality.",
      },
      {
        name: "Technical Architecture",
        type: "template",
        format: "docx",
        priority: "P1",
        description: "System architecture, stack decisions, scalability plan",
        templateContent: TECH_ARCH_TEMPLATE,
      },
      {
        name: "Product Roadmap (12-18 months)",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "Feature roadmap tied to fundraise milestones",
      },
      {
        name: "GitHub / Source Code Access",
        type: "connect",
        priority: "P2",
        description: "Private repo read-only access for technical due diligence",
        connectTo: "github",
        dueDiligenceNotes: "Technical VCs will review commit history.",
      },
      {
        name: "Security Audit / Pen Test Report",
        type: "upload",
        format: "pdf",
        priority: "P2",
        description: "Third-party security assessment results",
      },
    ],
  },

  // ── SECTION 5: MARKET & TRACTION ─────────────────────────
  {
    name: "5. Market & Traction",
    section: "traction",
    stage: "launch",
    priority: "P0",
    description: "Market validation, customer evidence, analytics, and growth proof",
    investorImpact: "critical",
    documents: [
      {
        name: "Traction Dashboard",
        type: "auto",
        priority: "P0",
        description: "Auto-generated from connected analytics showing key growth metrics",
        connectTo: "blockid-metrics",
        templateContent: TRACTION_TEMPLATE,
      },
      {
        name: "Customer / User List",
        type: "template",
        format: "xlsx",
        priority: "P0",
        description: "Key customers with ARR/ACV values",
        templateContent: CUSTOMER_LIST_TEMPLATE,
      },
      {
        name: "Market Size Analysis (TAM/SAM/SOM)",
        type: "template",
        format: "pdf",
        priority: "P1",
        description: "Bottom-up and top-down market sizing with sources",
        templateContent: MARKET_SIZE_TEMPLATE,
      },
      {
        name: "Google Analytics / Mixpanel Access",
        type: "connect",
        priority: "P1",
        description: "Read-only analytics access for investor verification",
        connectTo: "analytics",
        dueDiligenceNotes: "More powerful than screenshots — shows cohort retention.",
      },
      {
        name: "Case Studies / Testimonials",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "2-3 written customer case studies or video testimonials",
      },
      {
        name: "Competitive Analysis",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "Competitor landscape with feature differentiation matrix",
      },
    ],
  },

  // ── SECTION 6: TEAM & ADVISORS ────────────────────────────
  {
    name: "6. Team & Advisors",
    section: "team",
    stage: "idea",
    priority: "P0",
    description: "Founder profiles, team org chart, advisors, and hiring plan",
    investorImpact: "critical",
    documents: [
      {
        name: "Founder Profiles",
        type: "template",
        format: "docx",
        priority: "P0",
        description: "Detailed bios of all founders with domain expertise evidence",
        templateContent: TEAM_TEMPLATE,
      },
      {
        name: "LinkedIn Profiles (All Founders)",
        type: "connect",
        priority: "P0",
        description: "LinkedIn profile links for all founders",
        connectTo: "linkedin",
      },
      {
        name: "Hiring Plan (12 months)",
        type: "upload",
        format: "xlsx",
        priority: "P1",
        description: "Planned hires tied to fundraise milestones and budget",
      },
    ],
  },

  // ── SECTION 7: IP & COMPLIANCE ────────────────────────────
  {
    name: "7. IP & Compliance",
    section: "ip",
    stage: "mvp",
    priority: "P1",
    description: "IP ownership, open source, privacy, and regulatory compliance",
    investorImpact: "high",
    documents: [
      {
        name: "IP Assignment Deeds (Contractors)",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "Contracts with all contractors confirming IP assigned to company",
      },
      {
        name: "Trademark / Patent Register",
        type: "template",
        format: "docx",
        priority: "P1",
        description: "All registered and applied IP assets",
        templateContent: IP_REGISTER_TEMPLATE,
      },
      {
        name: "Privacy Policy",
        type: "connect",
        priority: "P0",
        description: "Current privacy policy compliant with Australian Privacy Act 1988",
        connectTo: "website-link",
        dueDiligenceNotes: "Must reference APP (Australian Privacy Principles) compliance",
      },
      {
        name: "Terms of Service",
        type: "connect",
        priority: "P1",
        description: "Current ToS / Customer Agreement",
        connectTo: "website-link",
      },
      {
        name: "Regulatory Licenses",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "AFSL, ACL, TGA, or industry-specific certifications if applicable",
        dueDiligenceNotes: "Fintech: AFSL/ACL required. Healthtech: TGA. Edtech: TEQSA if applicable.",
      },
    ],
  },

  // ── SECTION 8: CONTRACTS & AGREEMENTS ────────────────────
  {
    name: "8. Contracts & Agreements",
    section: "contracts",
    stage: "revenue",
    priority: "P1",
    description: "Customer contracts, supplier agreements, employment, and board arrangements",
    investorImpact: "high",
    documents: [
      {
        name: "Key Customer Contracts (Top 3 by ACV)",
        type: "upload",
        format: "pdf",
        priority: "P0",
        description: "Executed MSAs, SOWs, or subscription agreements with top customers",
        dueDiligenceNotes: "Check for assignment clauses that might not survive change of control",
      },
      {
        name: "Employment Agreements (All Staff)",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "All executed employment contracts including IP assignment",
      },
      {
        name: "Advisor Agreements",
        type: "upload",
        format: "pdf",
        priority: "P1",
        description: "All advisor agreements with equity, vesting, and scope of work",
      },
      {
        name: "Material Supplier / Vendor Contracts",
        type: "upload",
        format: "pdf",
        priority: "P2",
        description: "Key infrastructure or service contracts (AWS, etc.)",
      },
    ],
  },

  // ── SECTION 9: STRATEGY & ROADMAP ────────────────────────
  {
    name: "9. Strategy & Roadmap",
    section: "strategy",
    stage: "mvp",
    priority: "P1",
    description: "Go-to-market strategy, growth playbook, and fundraise plan",
    investorImpact: "high",
    documents: [
      {
        name: "Go-to-Market Strategy",
        type: "template",
        format: "pdf",
        priority: "P0",
        description: "Detailed GTM plan including ICP, channels, and growth levers",
        templateContent: GTM_TEMPLATE,
      },
      {
        name: "Fundraise Strategy & Pipeline",
        type: "upload",
        format: "xlsx",
        priority: "P1",
        description: "Investor pipeline, outreach status, and round structure",
      },
      {
        name: "Exit Strategy Analysis",
        type: "upload",
        format: "docx",
        priority: "P2",
        description: "Potential exit paths, acquirer landscape, and return modeling",
      },
    ],
  },

  // ── SECTION 10: REFERENCES & DUE DILIGENCE ───────────────
  {
    name: "10. References & Due Diligence",
    section: "references",
    stage: "raise",
    priority: "P1",
    description: "Press coverage, awards, references, and investor FAQ responses",
    investorImpact: "medium",
    documents: [
      {
        name: "Investor FAQ",
        type: "template",
        format: "pdf",
        priority: "P0",
        description: "Pre-answered common investor due diligence questions",
        templateContent: INVESTOR_FAQ_TEMPLATE,
      },
      {
        name: "Due Diligence Checklist (Auto-generated)",
        type: "auto",
        priority: "P0",
        description: "Auto-generated DD checklist showing data room completeness",
        connectTo: "blockid-dataroom",
        templateContent: DD_CHECKLIST_TEMPLATE,
      },
      {
        name: "Press & Media Coverage",
        type: "upload",
        format: "pdf",
        priority: "P2",
        description: "Articles, podcast appearances, or media mentions",
      },
      {
        name: "Awards & Recognition",
        type: "upload",
        format: "pdf",
        priority: "P2",
        description: "Industry awards, accelerator acceptance, government grants",
        dueDiligenceNotes: "EMDG, R&D Tax, Accelerating Commercialisation grants add credibility",
      },
    ],
  },
];

// ─────────────────────────────────────────────────────────────
// Helper functions
// ─────────────────────────────────────────────────────────────

export function getFoldersForStage(stage: number): DataRoomFolder[] {
  const stageMap: Record<number, string[]> = {
    0: ["idea"],
    1: ["idea"],
    2: ["idea", "mvp"],
    3: ["idea", "mvp"],
    4: ["idea", "mvp", "launch"],
    5: ["idea", "mvp", "launch", "revenue"],
    6: ["idea", "mvp", "launch", "revenue", "raise"],
    7: ["idea", "mvp", "launch", "revenue", "raise"],
  };
  const stages = stageMap[stage] ?? ["idea"];
  return DATA_ROOM_STRUCTURE.filter(f => stages.includes(f.stage));
}

export function getAllSections(): string[] {
  return DATA_ROOM_STRUCTURE.map(f => f.section);
}

export function getTemplateDocuments(): DataRoomDocument[] {
  return DATA_ROOM_STRUCTURE.flatMap(f =>
    f.documents.filter(d => d.type === "template")
  );
}

export function getP0Documents(): DataRoomDocument[] {
  return DATA_ROOM_STRUCTURE.flatMap(f =>
    f.documents.filter(d => d.priority === "P0")
  );
}

export function getDocumentsByInvestorType(
  investorType: "vc" | "angel" | "strategic" | "family_office"
): DataRoomDocument[] {
  return DATA_ROOM_STRUCTURE.flatMap(f =>
    f.documents.filter(
      d => !d.investorType || d.investorType.includes(investorType)
    )
  );
}

export function getCompletenessRequirements() {
  const sections = DATA_ROOM_STRUCTURE.map(folder => ({
    section: folder.section,
    name: folder.name,
    investorImpact: folder.investorImpact,
    totalDocs: folder.documents.length,
    p0Docs: folder.documents.filter(d => d.priority === "P0").length,
    p1Docs: folder.documents.filter(d => d.priority === "P1").length,
    p2Docs: folder.documents.filter(d => d.priority === "P2").length,
  }));

  const totalDocs = sections.reduce((sum, s) => sum + s.totalDocs, 0);
  const p0Docs = sections.reduce((sum, s) => sum + s.p0Docs, 0);

  return { sections, totalDocs, p0Docs };
}
