// Enhanced email delivery with DOCX + PDF attachments.
//
// Sends styled HTML emails for SVI reports with optional PDF/DOCX attachments.
// Uses the same SMTP infrastructure as email.ts (Nodemailer → Resend fallback).
// Supports English and Vietnamese locales.

import "server-only";
import { sendEmail } from "./email";
import {
  ensureEmailPreferences,
  canSendEmail,
  getUnsubscribeUrl,
  getPreferencesUrl,
} from "./email-preferences";

// ── Types ──────────────────────────────────────────────────────────────

export interface EnhancedReportEmailOptions {
  to: string;
  startupName: string;
  sviScore: number;
  stageLabel: string;
  reportSummary: string;
  pdfBuffer?: Buffer;
  docxBuffer?: Buffer;
  reportUrl: string;
  locale?: "en" | "vi";
}

// ── Helpers ────────────────────────────────────────────────────────────

function siteUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL || "https://blockid.au").replace(
    /\/$/,
    "",
  );
}

/** Return badge color based on SVI score tier. */
function scoreColor(score: number): string {
  if (score >= 80) return "#10b981"; // green — strong
  if (score >= 60) return "#6c5ce7"; // purple — promising
  if (score >= 40) return "#f59e0b"; // amber — developing
  return "#ef4444";                  // red — early
}

/** Return tier label based on SVI score. */
function scoreTier(score: number, locale: "en" | "vi"): string {
  if (locale === "vi") {
    if (score >= 80) return "Mạnh";
    if (score >= 60) return "Tiềm năng";
    if (score >= 40) return "Đang phát triển";
    return "Giai đoạn đầu";
  }
  if (score >= 80) return "Strong";
  if (score >= 60) return "Promising";
  if (score >= 40) return "Developing";
  return "Early Stage";
}

// ── Locale strings ─────────────────────────────────────────────────────

interface LocaleStrings {
  subjectPrefix: string;
  heading: string;
  sviScoreLabel: string;
  stageLabel: string;
  executiveSummary: string;
  viewFullReport: string;
  attachmentsLabel: string;
  disclaimer: string;
  unsubscribe: string;
  managePreferences: string;
  poweredBy: string;
}

const LOCALE: Record<"en" | "vi", LocaleStrings> = {
  en: {
    subjectPrefix: "Your SVI Report",
    heading: "Startup Viability Index Report",
    sviScoreLabel: "SVI Score",
    stageLabel: "Stage",
    executiveSummary: "Executive Summary",
    viewFullReport: "View Full Report",
    attachmentsLabel: "Attached Documents",
    disclaimer:
      "This report is generated by AI and does not constitute financial advice. " +
      "BlockID.au is operated by Auschain PTY LTD (ACN 659 615 111). " +
      "Please consult a licensed financial adviser before making investment decisions.",
    unsubscribe: "Unsubscribe",
    managePreferences: "Manage email preferences",
    poweredBy: "Powered by BlockID.au — AI Startup Intelligence",
  },
  vi: {
    subjectPrefix: "Báo cáo SVI của bạn",
    heading: "Báo cáo Chỉ số Khả thi Khởi nghiệp",
    sviScoreLabel: "Điểm SVI",
    stageLabel: "Giai đoạn",
    executiveSummary: "Tóm tắt điều hành",
    viewFullReport: "Xem báo cáo đầy đủ",
    attachmentsLabel: "Tài liệu đính kèm",
    disclaimer:
      "Báo cáo này được tạo bởi AI và không phải là tư vấn tài chính. " +
      "BlockID.au được vận hành bởi Auschain PTY LTD (ACN 659 615 111). " +
      "Vui lòng tham khảo ý kiến của cố vấn tài chính trước khi đưa ra quyết định đầu tư.",
    unsubscribe: "Hủy đăng ký",
    managePreferences: "Quản lý tùy chọn email",
    poweredBy: "Được cung cấp bởi BlockID.au — Trí tuệ Nhân tạo Khởi nghiệp",
  },
};

// ── HTML builder ───────────────────────────────────────────────────────

function buildEmailHtml(
  opts: EnhancedReportEmailOptions,
  unsubscribeUrl: string,
  preferencesUrl: string,
): string {
  const locale = opts.locale ?? "en";
  const t = LOCALE[locale];
  const color = scoreColor(opts.sviScore);
  const tier = scoreTier(opts.sviScore, locale);
  const summary = opts.reportSummary.slice(0, 500);

  const attachmentsList: string[] = [];
  if (opts.pdfBuffer) attachmentsList.push(`BlockID-SVI-${opts.startupName}.pdf`);
  if (opts.docxBuffer) attachmentsList.push(`BlockID-SVI-${opts.startupName}.docx`);

  const attachmentsSection =
    attachmentsList.length > 0
      ? `
    <div style="background:#f0f0f5;padding:16px;border-radius:8px;margin:20px 0;">
      <h3 style="font-size:14px;color:#495057;margin:0 0 8px;">${t.attachmentsLabel}</h3>
      ${attachmentsList
        .map(
          (name) =>
            `<div style="font-size:13px;color:#6c5ce7;padding:4px 0;">📎 ${name}</div>`,
        )
        .join("")}
    </div>`
      : "";

  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${t.heading}</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a2e;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f8;">
    <tr><td align="center" style="padding:24px 16px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">

        <!-- Header -->
        <tr><td style="background:linear-gradient(135deg,#6c5ce7,#a29bfe);padding:32px 24px;text-align:center;">
          <div style="font-size:28px;font-weight:700;color:#fff;letter-spacing:-0.5px;">BlockID.au</div>
          <div style="font-size:15px;color:rgba(255,255,255,0.85);margin-top:6px;">${t.heading}</div>
        </td></tr>

        <!-- SVI Score Badge -->
        <tr><td style="padding:32px 24px 16px;text-align:center;">
          <div style="display:inline-block;width:120px;height:120px;border-radius:60px;background:${color};line-height:120px;text-align:center;">
            <span style="font-size:42px;font-weight:800;color:#fff;">${opts.sviScore}</span>
          </div>
          <div style="margin-top:12px;">
            <span style="display:inline-block;font-size:13px;font-weight:600;color:${color};background:${color}1a;padding:4px 14px;border-radius:20px;text-transform:uppercase;letter-spacing:0.5px;">${tier}</span>
          </div>
          <div style="font-size:12px;color:#888;margin-top:4px;">${t.sviScoreLabel}</div>
        </td></tr>

        <!-- Startup Name & Stage -->
        <tr><td style="padding:0 24px 24px;text-align:center;">
          <h2 style="font-size:22px;color:#1a1a2e;margin:0 0 6px;">${opts.startupName}</h2>
          <div style="font-size:14px;color:#666;">${t.stageLabel}: <strong>${opts.stageLabel}</strong></div>
        </td></tr>

        <!-- Divider -->
        <tr><td style="padding:0 24px;"><hr style="border:none;border-top:1px solid #eee;margin:0;"></td></tr>

        <!-- Executive Summary -->
        <tr><td style="padding:24px;">
          <h3 style="font-size:16px;color:#6c5ce7;margin:0 0 12px;">${t.executiveSummary}</h3>
          <p style="font-size:14px;line-height:1.7;color:#333;margin:0;">${summary}${opts.reportSummary.length > 500 ? "..." : ""}</p>
        </td></tr>

        <!-- Attachments -->
        <tr><td style="padding:0 24px;">${attachmentsSection}</td></tr>

        <!-- CTA Button -->
        <tr><td style="padding:24px;text-align:center;">
          <a href="${opts.reportUrl}" style="display:inline-block;background:#6c5ce7;color:#fff;text-decoration:none;padding:14px 36px;border-radius:8px;font-size:15px;font-weight:600;letter-spacing:0.3px;">${t.viewFullReport}</a>
        </td></tr>

        <!-- Footer -->
        <tr><td style="background:#1a1a2e;padding:24px;text-align:center;">
          <p style="font-size:11px;color:rgba(255,255,255,0.5);margin:0 0 8px;line-height:1.6;">${t.disclaimer}</p>
          <p style="font-size:11px;color:rgba(255,255,255,0.4);margin:0 0 12px;">${t.poweredBy}</p>
          <p style="font-size:11px;margin:0;">
            <a href="${unsubscribeUrl}" style="color:rgba(255,255,255,0.4);text-decoration:underline;">${t.unsubscribe}</a>
            &nbsp;|&nbsp;
            <a href="${preferencesUrl}" style="color:rgba(255,255,255,0.4);text-decoration:underline;">${t.managePreferences}</a>
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

// ── Public API ──────────────────────────────────────────────────────────

export async function sendEnhancedReport(
  opts: EnhancedReportEmailOptions,
): Promise<{ ok: boolean; error?: string }> {
  const locale = opts.locale ?? "en";
  const t = LOCALE[locale];

  try {
    // Ensure email preferences exist and check subscription status
    await ensureEmailPreferences(opts.to);
    const allowed = await canSendEmail(opts.to, "svi_alerts");
    if (!allowed) {
      console.log(
        `[email-enhanced] Skipped: ${opts.to} has unsubscribed from svi_alerts`,
      );
      return { ok: false, error: "unsubscribed" };
    }

    // Build unsubscribe / preferences URLs
    const unsubscribeUrl =
      (await getUnsubscribeUrl(opts.to)) ?? `${siteUrl()}/unsubscribe`;
    const preferencesUrl =
      (await getPreferencesUrl(opts.to)) ?? `${siteUrl()}/email-preferences`;

    // Build email HTML
    const html = buildEmailHtml(opts, unsubscribeUrl, preferencesUrl);

    // Prepare attachments
    const attachments: {
      filename: string;
      content: Buffer | Uint8Array;
      contentType?: string;
    }[] = [];

    if (opts.pdfBuffer) {
      attachments.push({
        filename: `BlockID-SVI-${opts.startupName}.pdf`,
        content: opts.pdfBuffer,
        contentType: "application/pdf",
      });
    }

    if (opts.docxBuffer) {
      attachments.push({
        filename: `BlockID-SVI-${opts.startupName}.docx`,
        content: opts.docxBuffer,
        contentType:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      });
    }

    // Send via existing email infrastructure (SMTP → Resend fallback)
    const subject = `${t.subjectPrefix}: ${opts.startupName} — Score ${opts.sviScore}`;
    const result = await sendEmail({
      to: opts.to,
      subject,
      html,
      unsubscribeUrl,
      attachments,
    });

    if (result.ok) {
      console.log(
        `[email-enhanced] Sent report for "${opts.startupName}" to ${opts.to} (score ${opts.sviScore}, ${attachments.length} attachments)`,
      );
      return { ok: true };
    }

    console.error(
      `[email-enhanced] Failed to send report for "${opts.startupName}" to ${opts.to}:`,
      result,
    );
    return {
      ok: false,
      error: result.reason ?? "unknown",
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[email-enhanced] Exception sending to ${opts.to}:`, msg);
    return { ok: false, error: msg };
  }
}
