import type { Metadata } from "next";
import Link from "next/link";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { Download, Sparkles, ShieldCheck } from "lucide-react";
import { Navbar } from "@/components/site/navbar";
import { Footer } from "@/components/site/footer";
import { Button } from "@/components/ui/button";
import { ScoreCard } from "@/components/score/score-card";
import { getSupabaseAdmin, isSupabaseConfigured } from "@/lib/supabase";
import { hashIp, clientIpFromHeaders } from "@/lib/iphash";

// Force dynamic — every render records a view, and the score data is keyed
// by an opaque slug we can't statically pre-compute.
export const dynamic = "force-dynamic";

interface ScoreRow {
  id: string;
  email: string;
  company_name: string | null;
  total_score: number;
  sub_scores: Record<string, number>;
  inputs: Record<string, unknown>;
  score_version?: string | null;
  confidence_score?: number | null;
  missing_inputs?: string[] | null;
  action_plan?: Array<{
    title: string;
    detail: string;
    impact: "high" | "medium" | "low";
  }> | null;
  benchmark?: {
    label: string;
    medianScore: number;
    band: string;
    rationale: string;
  } | null;
  created_at: string;
}

const DEMO_SUBS = [
  { label: "Financials", value: 78 },
  { label: "Cap Table Hygiene", value: 86 },
  { label: "Governance", value: 72 },
  { label: "Founder Background", value: 88 },
  { label: "Documentation", value: 80 },
];

const DEMO_ACTIONS = [
  {
    title: "Complete diligence inputs",
    detail: "Connect accounting data and confirm the shareholders agreement before sending to institutional investors.",
    impact: "high" as const,
  },
  {
    title: "Prepare runway narrative",
    detail: "Explain the bridge plan and burn reduction path before the first investor meeting.",
    impact: "medium" as const,
  },
];

function siteUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(
    /\/$/,
    "",
  );
}

async function fetchScore(slug: string): Promise<ScoreRow | null> {
  const supabase = getSupabaseAdmin();
  if (!supabase) return null;
  const { data, error } = await supabase
    .from("scores")
    .select("*")
    .eq("id", slug)
    .maybeSingle();
  if (error) {
    console.error("[blockid:s] supabase fetch failed", error);
    return null;
  }
  return (data as ScoreRow) ?? null;
}

async function recordView(slug: string) {
  const supabase = getSupabaseAdmin();
  if (!supabase) return;
  const h = await headers();
  const ip = clientIpFromHeaders(h);
  const { error } = await supabase.from("score_views").insert({
    score_id: slug,
    viewer_ip_hash: hashIp(ip),
    viewer_ua: h.get("user-agent")?.slice(0, 512) ?? null,
    referer: h.get("referer")?.slice(0, 512) ?? null,
  });
  if (error) {
    // Don't fail the page render on telemetry failure.
    console.error("[blockid:s] view insert failed", error);
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  let title = "Investor-Ready Score — BlockID";
  let description =
    "An Investor-Ready Score generated by BlockID — five sub-scores investors review at seed and Series A.";

  if (slug.startsWith("demo-") || !isSupabaseConfigured()) {
    title = `Investor-Ready Score · 82/100 — Demo (BlockID)`;
  } else {
    const score = await fetchScore(slug);
    if (score) {
      const co = score.company_name || "Company";
      title = `${co} · Investor-Ready Score ${score.total_score}/100 — BlockID`;
      description = `${co} scored ${score.total_score}/100 across financials, cap table, governance, founder background and documentation. Generated by BlockID.`;
    }
  }

  const url = `${siteUrl()}/s/${slug}`;
  return {
    title,
    description,
    openGraph: { title, description, url, siteName: "BlockID", type: "website" },
    twitter: { card: "summary_large_image", title, description },
    robots: { index: false, follow: false }, // share links are private artifacts
  };
}

export default async function ShareScorePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  const isDemo = slug.startsWith("demo-") || !isSupabaseConfigured();
  let row: ScoreRow | null = null;

  if (!isDemo) {
    row = await fetchScore(slug);
    if (!row) notFound();
    await recordView(slug);
  }

  const companyName = row?.company_name || "Acme Co Pty Ltd";
  const totalScore = row?.total_score ?? 82;
  const subScores =
    row?.sub_scores
      ? [
          { label: "Financials", value: row.sub_scores.financials ?? 0 },
          { label: "Cap Table Hygiene", value: row.sub_scores.capTable ?? 0 },
          { label: "Governance", value: row.sub_scores.governance ?? 0 },
          { label: "Founder Background", value: row.sub_scores.founder ?? 0 },
          { label: "Documentation", value: row.sub_scores.documentation ?? 0 },
        ]
      : DEMO_SUBS;
  const createdAt = row?.created_at || new Date().toISOString();
  const confidenceScore = row?.confidence_score ?? 78;
  const missingInputs = row?.missing_inputs ?? [];
  const actionPlan = row?.action_plan?.length ? row.action_plan : DEMO_ACTIONS;
  const benchmark = row?.benchmark ?? {
    label: "seed · SAAS",
    medianScore: 71,
    band: "within current AU founder benchmark",
    rationale:
      "Benchmark is an internal heuristic until BlockID has enough verified AU company outcomes.",
  };
  const scoreVersion = row?.score_version ?? "1.0.0";

  return (
    <>
      <Navbar />
      <main id="main" className="flex-1 pt-32 md:pt-40 pb-24">
        <div className="mx-auto max-w-5xl px-6">
          {isDemo && (
            <div className="mb-8 rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">
              Demo mode — Supabase is not configured, so this page renders a
              sample score. Set <code className="font-mono">SUPABASE_URL</code>{" "}
              and <code className="font-mono">SUPABASE_SERVICE_ROLE_KEY</code>{" "}
              to persist real scores.
            </div>
          )}
          <header className="max-w-3xl">
            <p className="text-xs uppercase tracking-[0.2em] text-teal-400 font-medium inline-flex items-center gap-2">
              <ShieldCheck strokeWidth={1.75} className="h-4 w-4" />
              Investor View Link
            </p>
            <h1 className="mt-3 text-4xl md:text-5xl font-semibold tracking-tight text-slate-50">
              {companyName}
            </h1>
            <p className="mt-4 text-base md:text-lg leading-relaxed text-slate-400">
              Investor-Ready Score generated by BlockID. Five sub-scores
              covering the dimensions investors review at seed and Series A.
              Generated{" "}
              <span className="font-mono tabular-nums">
                {createdAt.slice(0, 10)}
              </span>
              .
            </p>
          </header>

          <section className="mt-10 grid lg:grid-cols-2 gap-8 items-start">
            <ScoreCard
              score={totalScore}
              subScores={subScores}
              caption={`${createdAt.slice(0, 10)} · v${scoreVersion}`}
            />

            <div className="rounded-2xl border border-ink-700 bg-ink-900 p-6">
              <h2 className="text-lg font-semibold text-slate-50 inline-flex items-center gap-2">
                <Sparkles strokeWidth={1.75} className="h-5 w-5 text-teal-400" />
                Get your own free score
              </h2>
              <p className="mt-2 text-sm text-slate-400 leading-relaxed">
                BlockID gives every Australian founder a free Investor-Ready
                Score in 5 minutes — one number, five sub-scores, one
                shareable link. No credit card.
              </p>
              <div className="mt-5 flex flex-wrap gap-3">
                <Link href="/score" className="inline-flex">
                  <Button variant="primary">Generate my score</Button>
                </Link>
                <a
                  href={`/s/${slug}/pdf`}
                  className="inline-flex"
                  target="_blank"
                  rel="noopener"
                >
                  <Button variant="secondary">
                    <Download strokeWidth={1.75} className="h-5 w-5" />
                    Download PDF
                  </Button>
                </a>
                <Link href={`/s/${slug}/activity`} className="inline-flex">
                  <Button variant="secondary">View activity</Button>
                </Link>
              </div>
              <hr className="my-6 border-ink-700" />
              <div className="grid sm:grid-cols-2 gap-3">
                <InfoStat
                  label="Confidence"
                  value={`${confidenceScore}/100`}
                  detail={
                    missingInputs.length
                      ? `${missingInputs.length} missing inputs`
                      : "Core inputs present"
                  }
                />
                <InfoStat
                  label="Benchmark"
                  value={benchmark.label}
                  detail={`${benchmark.band}; median ${benchmark.medianScore}`}
                />
              </div>
              <div className="mt-6 rounded-xl border border-ink-700 bg-ink-800/40 p-4">
                <p className="text-xs uppercase tracking-[0.16em] text-slate-500">
                  Recommended actions
                </p>
                <ul className="mt-4 space-y-3">
                  {actionPlan.slice(0, 3).map((action) => (
                    <li key={action.title} className="text-sm">
                      <p className="font-medium text-slate-100">
                        {action.title}
                      </p>
                      <p className="mt-1 text-xs leading-relaxed text-slate-400">
                        {action.detail}
                      </p>
                    </li>
                  ))}
                </ul>
              </div>
              <hr className="my-6 border-ink-700" />
              <dl className="grid grid-cols-2 gap-4 text-xs">
                <div>
                  <dt className="text-slate-500 uppercase tracking-[0.15em]">
                    Generated
                  </dt>
                  <dd className="mt-1 text-slate-300 font-mono tabular-nums">
                    {createdAt.slice(0, 10)}
                  </dd>
                </div>
                <div>
                  <dt className="text-slate-500 uppercase tracking-[0.15em]">
                    Link
                  </dt>
                  <dd className="mt-1 text-slate-300 font-mono tabular-nums break-all">
                    /s/{slug}
                  </dd>
                </div>
                <div>
                  <dt className="text-slate-500 uppercase tracking-[0.15em]">
                    Score version
                  </dt>
                  <dd className="mt-1 text-slate-300 font-mono tabular-nums">
                    v{scoreVersion}
                  </dd>
                </div>
                <div className="col-span-2">
                  <dt className="text-slate-500 uppercase tracking-[0.15em]">
                    Powered by
                  </dt>
                  <dd className="mt-1 text-slate-300">
                    BlockID — Persistent Identity & Trust Infrastructure for
                    Private Capital Markets. AU data residency.
                  </dd>
                </div>
              </dl>
            </div>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}

function InfoStat({
  label,
  value,
  detail,
}: {
  label: string;
  value: string;
  detail: string;
}) {
  return (
    <div className="rounded-xl border border-ink-700 bg-ink-800/40 px-4 py-3">
      <p className="text-[10px] uppercase tracking-[0.16em] text-slate-500">
        {label}
      </p>
      <p className="mt-1 text-sm font-medium text-slate-100">{value}</p>
      <p className="mt-1 text-xs text-slate-500">{detail}</p>
    </div>
  );
}
