"use client";

import { useEffect, useState, useCallback } from "react";
import {
  Lightbulb,
  TrendingUp,
  Users,
  Target,
  Zap,
  Check,
  Loader2,
} from "lucide-react";

// ---------------------------------------------------------------------------
// InsightsPanel — client component that fetches and displays personalized
// startup insights generated by the Customer Care AI agent.
// ---------------------------------------------------------------------------

interface Insight {
  id: string;
  insight_type: string;
  title: string;
  summary: string;
  detail: string | null;
  relevance_score: number | null;
  source: string | null;
  read_at: string | null;
  created_at: string;
}

const TYPE_CONFIG: Record<string, { icon: typeof Lightbulb; color: string; label: string }> = {
  market_trend: { icon: TrendingUp, color: "text-blue-600 bg-blue-50 border-blue-200", label: "Market Trend" },
  competitor_update: { icon: Users, color: "text-amber-600 bg-amber-50 border-amber-200", label: "Competitor" },
  new_business: { icon: Zap, color: "text-emerald-600 bg-emerald-50 border-emerald-200", label: "New Business" },
  opportunity: { icon: Target, color: "text-brand-600 bg-brand-50 border-brand-200", label: "Opportunity" },
};

function getTypeConfig(type: string) {
  return TYPE_CONFIG[type] ?? TYPE_CONFIG.market_trend;
}

function relevanceBadge(score: number | null) {
  if (score == null) return null;
  const pct = Math.round(score * 100);
  let color = "bg-surface-100 text-ink-600";
  if (pct >= 90) color = "bg-emerald-50 text-emerald-700";
  else if (pct >= 80) color = "bg-blue-50 text-blue-700";
  else if (pct >= 70) color = "bg-amber-50 text-amber-700";
  return (
    <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${color}`}>
      {pct}% relevant
    </span>
  );
}

export function InsightsPanel() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  const [dismissing, setDismissing] = useState<string | null>(null);

  const fetchInsights = useCallback(async () => {
    try {
      const res = await fetch("/api/insights");
      if (!res.ok) return;
      const data = await res.json();
      if (data.ok) setInsights(data.insights);
    } catch { /* ignore */ }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { fetchInsights(); }, [fetchInsights]);

  const markAsRead = async (id: string) => {
    setDismissing(id);
    try {
      const res = await fetch("/api/insights", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ insightId: id }),
      });
      if (res.ok) {
        setInsights(prev => prev.filter(i => i.id !== id));
      }
    } catch { /* ignore */ }
    finally { setDismissing(null); }
  };

  if (loading) return null; // Don't show loading skeleton for a secondary panel
  if (insights.length === 0) return null; // Clean — no empty state cluttering the dashboard

  return (
    <section className="mt-8 bg-white border border-surface-200 shadow-sm rounded-2xl p-6">
      <div className="flex items-center gap-2 mb-4">
        <Lightbulb className="h-5 w-5 text-brand-600" />
        <h2 className="text-lg font-semibold text-ink-800">Insights for You</h2>
        <span className="rounded-full bg-brand-100 px-2 py-0.5 text-xs font-medium text-brand-700">
          {insights.length} new
        </span>
      </div>

      <ul className="space-y-3">
        {insights.map((insight) => {
          const cfg = getTypeConfig(insight.insight_type);
          const Icon = cfg.icon;
          const isDismissing = dismissing === insight.id;

          return (
            <li
              key={insight.id}
              className="rounded-xl border border-surface-200 bg-surface-50 px-4 py-3 transition-colors hover:border-brand-200"
            >
              <div className="flex items-start gap-3">
                <div className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border ${cfg.color}`}>
                  <Icon className="h-4 w-4" />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <h3 className="text-sm font-semibold text-ink-800">{insight.title}</h3>
                    <span className={`rounded-full border px-2 py-0.5 text-[10px] font-medium ${cfg.color}`}>
                      {cfg.label}
                    </span>
                    {relevanceBadge(insight.relevance_score)}
                  </div>
                  <p className="mt-1 text-xs leading-relaxed text-ink-600">
                    {insight.summary}
                  </p>
                  {insight.detail && (
                    <details className="mt-2">
                      <summary className="cursor-pointer text-[11px] font-medium text-brand-600 hover:text-brand-700">
                        Read more
                      </summary>
                      <p className="mt-1 text-xs leading-relaxed text-ink-500">
                        {insight.detail}
                      </p>
                    </details>
                  )}
                  <div className="mt-2 flex items-center justify-between">
                    <span className="text-[11px] text-ink-400">
                      {insight.source && `${insight.source} · `}
                      {new Date(insight.created_at).toLocaleDateString("en-AU", {
                        day: "numeric",
                        month: "short",
                      })}
                    </span>
                    <button
                      onClick={() => markAsRead(insight.id)}
                      disabled={isDismissing}
                      className="flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-medium text-ink-500 transition-colors hover:bg-surface-200 hover:text-ink-700 disabled:opacity-50"
                    >
                      {isDismissing ? (
                        <Loader2 className="h-3 w-3 animate-spin" />
                      ) : (
                        <Check className="h-3 w-3" />
                      )}
                      Mark as read
                    </button>
                  </div>
                </div>
              </div>
            </li>
          );
        })}
      </ul>
    </section>
  );
}
