// Colocated tests for POST /api/svi/docx — S18-A member access.
//
// The export is a READ of the shared startup record (viewer+), charged to
// the caller's own credits. Pins:
//   - viewer on a shared project is allowed; account + latest analysis are
//     resolved under the OWNER's email with the legacy fallback bound to the
//     caller
//   - the assembled report / saved section lookup accepts rows generated by
//     the caller OR the owner (`user_id in (caller, owner)`) on the
//     project's account — never a filter on the caller alone
//   - credits are spent from the CALLER's wallet

import { describe, it, expect, vi, beforeEach } from "vitest";
import { describeMemberAccess } from "@/test/member-access-suite";
import { fakeSupabase } from "@/test/fake-supabase";
import { makeScopeState } from "@/test/project-scope-mock";

vi.mock("server-only", () => ({}));

const scopeState = await vi.hoisted(async () => {
  const { makeScopeState } = await import("@/test/project-scope-mock");
  return makeScopeState();
});
vi.mock("@/lib/projects", async () => {
  const { projectsMock } = await import("@/test/project-scope-mock");
  return projectsMock(scopeState);
});

const auth = vi.hoisted(() => ({ user: { id: "user-caller", email: "caller@x.test" } as Record<string, unknown> | null }));
vi.mock("@/lib/auth", () => ({ getCurrentUser: async () => auth.user }));
vi.mock("@/lib/rate-limit", () => ({ enforceRateLimit: () => null }));

const credits = vi.hoisted(() => ({ canAfford: vi.fn(), spendCredits: vi.fn() }));
vi.mock("@/lib/credits", () => ({
  canAfford: (...a: unknown[]) => credits.canAfford(...a),
  spendCredits: (...a: unknown[]) => credits.spendCredits(...a),
}));

vi.mock("@/lib/docx/svi-report-docx", () => ({
  generateSVIDocx: async () => new Uint8Array([1, 2, 3]),
}));
vi.mock("@/lib/paywall/report-delivery", () => ({
  reconstructAssembledReport: (row: Record<string, unknown>) => ({
    title: row.title,
    sections: [],
    totalWords: 10,
  }),
}));

const db = vi.hoisted(() => ({ sb: null as ReturnType<typeof fakeSupabase> | null }));
vi.mock("@/lib/supabase", () => ({ getSupabaseAdmin: () => db.sb }));

import { POST } from "./route";

function req() {
  return new Request("http://x/api/svi/docx", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ analysisId: "latest" }),
  });
}

function reset() {
  Object.assign(scopeState, makeScopeState({
    account: { id: "acct-1", email: "owner@x.test", startup_name: "Acme", current_svi: 100, current_stage: 1 },
  }));
  auth.user = { id: "user-caller", email: "caller@x.test" };
  credits.canAfford.mockReset().mockResolvedValue({ allowed: true, balance: 10, cost: 1 });
  credits.spendCredits.mockReset().mockResolvedValue({ ok: true, balance: 9 });
  db.sb = fakeSupabase({
    assembled_reports: [{ id: "rep-1", title: "SVI Enhanced Report: Acme", status: "complete", user_id: "user-owner" }],
  });
}

beforeEach(reset);

describeMemberAccess("POST /api/svi/docx (latest report)", {
  state: scopeState,
  kind: "read",
  reset,
  run: () => POST(req()),
  expectKeyFns: ["findSVIAccountWithFallback"],
});

describe("POST /api/svi/docx — shared report lookup + wallet", () => {
  it("viewer: exports the OWNER's assembled report and pays from their own wallet", async () => {
    scopeState.role = "viewer";
    const res = await POST(req());
    expect(res.status).toBe(200);
    expect(db.sb!.hasEq("assembled_reports", "account_id", "acct-1")).toBe(true);
    const inCall = db.sb!.find("assembled_reports", "in")[0];
    expect(inCall.args[0]).toBe("user_id");
    expect(inCall.args[1]).toEqual(["user-caller", "user-owner"]);
    expect(credits.spendCredits).toHaveBeenCalledWith("user-caller", "docx_export", expect.anything());
  });

  it("owner: report lookup is bound to the owner alone", async () => {
    const res = await POST(req());
    expect(res.status).toBe(200);
    const inCall = db.sb!.find("assembled_reports", "in")[0];
    expect(inCall.args[1]).toEqual(["user-caller"]);
  });
});
