#!/usr/bin/env tsx
/**
 * build-plans.ts — Compile pricing CSV → TypeScript + Stripe seed JSON.
 *
 * Reads:  web/src/config/pricing/plans.csv          (source of truth for humans)
 * Writes: web/src/config/pricing/plans.generated.ts (typed const, fallback for DB miss)
 *         web/src/config/pricing/stripe-seed.json    (consumed by seed-stripe.ts)
 *
 * ADDITIVE ONLY. Does not commit; deploy pipeline runs this before build.
 * Fails loudly on schema violations so bad rows never ship.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CSV_PATH = resolve(__dirname, "../src/config/pricing/plans.csv");
const TS_OUT   = resolve(__dirname, "../src/config/pricing/plans.generated.ts");
const SEED_OUT = resolve(__dirname, "../src/config/pricing/stripe-seed.json");

// ── CSV parsing (Node built-in — no runtime dep) ──────────────────────────────
// Handles double-quoted fields with embedded commas + escaped double quotes ("").
function parseCsv(input: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuotes = false;
  let i = 0;
  const len = input.length;

  while (i < len) {
    const ch = input[i];
    if (inQuotes) {
      if (ch === '"') {
        if (input[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQuotes = false; i++; continue;
      }
      field += ch; i++; continue;
    }
    if (ch === '"') { inQuotes = true; i++; continue; }
    if (ch === ",") { row.push(field); field = ""; i++; continue; }
    if (ch === "\n" || ch === "\r") {
      // handle CRLF
      if (ch === "\r" && input[i + 1] === "\n") i++;
      row.push(field); field = "";
      if (row.length > 1 || row[0] !== "") rows.push(row);
      row = [];
      i++;
      continue;
    }
    field += ch; i++;
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

// ── Row schema ────────────────────────────────────────────────────────────────
const PlanRowSchema = z.object({
  id: z.string().min(1),
  segment: z.enum(["founder", "investor_angel", "advisor", "investor_vc", "accelerator"]),
  name: z.string().min(1),
  price_aud_cents: z.coerce.number().int().min(0),
  annual_price_aud_cents: z.coerce.number().int().min(0),
  interval: z.enum(["free", "monthly", "yearly", "once", "custom"]),
  trial_days: z.coerce.number().int().min(0).max(365),
  stripe_env_var: z.string().optional().default(""),
  feature_flags: z.string().transform((s, ctx) => {
    try { const v = JSON.parse(s); if (!Array.isArray(v)) throw new Error(); return v as string[]; }
    catch { ctx.addIssue({ code: "custom", message: "feature_flags must be a JSON array" }); return z.NEVER; }
  }),
  usage_limits: z.string().transform((s, ctx) => {
    try { const v = JSON.parse(s); if (typeof v !== "object" || v === null) throw new Error(); return v as Record<string, number>; }
    catch { ctx.addIssue({ code: "custom", message: "usage_limits must be a JSON object" }); return z.NEVER; }
  }),
  active: z.string().transform(s => s.toLowerCase() === "true"),
  sort_order: z.coerce.number().int(),
});

export type PlanRow = z.infer<typeof PlanRowSchema>;

// ── Main ──────────────────────────────────────────────────────────────────────
function main(): void {
  const raw = readFileSync(CSV_PATH, "utf8");
  const rows = parseCsv(raw);
  if (rows.length < 2) throw new Error("plans.csv is empty");

  const [header, ...dataRows] = rows;
  const plans: PlanRow[] = dataRows.map((cols, idx) => {
    const obj: Record<string, string> = {};
    header.forEach((h, i) => { obj[h.trim()] = (cols[i] ?? "").trim(); });
    const parsed = PlanRowSchema.safeParse(obj);
    if (!parsed.success) {
      const issues = parsed.error.issues.map(i => `${i.path.join(".")}: ${i.message}`).join("; ");
      throw new Error(`plans.csv row ${idx + 2} invalid: ${issues}`);
    }
    return parsed.data;
  });

  // ID uniqueness
  const ids = new Set<string>();
  for (const p of plans) {
    if (ids.has(p.id)) throw new Error(`Duplicate plan id: ${p.id}`);
    ids.add(p.id);
  }

  // ── Emit TypeScript ───────────────────────────────────────────────────────
  const ts = `// AUTO-GENERATED by scripts/build-plans.ts — DO NOT EDIT BY HAND.
// Source: web/src/config/pricing/plans.csv
// Regenerate: npx tsx scripts/build-plans.ts

export interface GeneratedPlan {
  id: string;
  segment: "founder" | "investor_angel" | "advisor" | "investor_vc" | "accelerator";
  name: string;
  price_aud_cents: number;
  annual_price_aud_cents: number;
  interval: "free" | "monthly" | "yearly" | "once" | "custom";
  trial_days: number;
  stripe_env_var: string;
  feature_flags: string[];
  usage_limits: Record<string, number>;
  active: boolean;
  sort_order: number;
}

export const GENERATED_PLANS: readonly GeneratedPlan[] = ${JSON.stringify(plans, null, 2)} as const;

export const GENERATED_PLANS_BY_ID: Readonly<Record<string, GeneratedPlan>> =
  Object.fromEntries(GENERATED_PLANS.map(p => [p.id, p]));
`;
  writeFileSync(TS_OUT, ts, "utf8");

  // ── Emit Stripe seed JSON ─────────────────────────────────────────────────
  // seed-stripe.ts reads this to create/update Product+Price objects.
  const stripeSeed = plans
    .filter(p => p.active && p.price_aud_cents > 0 && p.stripe_env_var)
    .map(p => ({
      plan_id: p.id,
      product_name: p.name,
      segment: p.segment,
      stripe_env_var: p.stripe_env_var,
      currency: "aud",
      monthly_amount_cents: p.interval === "monthly" ? p.price_aud_cents : null,
      annual_amount_cents: p.annual_price_aud_cents > 0 ? p.annual_price_aud_cents : null,
      interval: p.interval,
      trial_days: p.trial_days,
    }));
  writeFileSync(SEED_OUT, JSON.stringify({ generated_at: new Date().toISOString(), plans: stripeSeed }, null, 2), "utf8");

  // eslint-disable-next-line no-console
  console.log(`[build-plans] wrote ${plans.length} plans -> ${TS_OUT}`);
  // eslint-disable-next-line no-console
  console.log(`[build-plans] wrote ${stripeSeed.length} Stripe seed entries -> ${SEED_OUT}`);
}

main();
