#!/bin/bash
# BlockID.au — GitHub Flow Helper
#
# Usage:
#   bash scripts/git-flow.sh push              # commit + push current branch to GitHub
#   bash scripts/git-flow.sh pr "title"         # create PR from current branch → master
#   bash scripts/git-flow.sh release "note"     # merge current PR + deploy live
#   bash scripts/git-flow.sh deploy             # pull master from GitHub + deploy live
#   bash scripts/git-flow.sh sync               # push master to both GitLab + GitHub
#
# Flow: edit code → push → PR (review) → merge → auto deploy on server

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$WEB_DIR"

GITHUB_REMOTE="github"
GITLAB_REMOTE="origin"

cmd="${1:-help}"
shift 2>/dev/null || true

case "$cmd" in

  push)
    BRANCH=$(git branch --show-current)
    if [ "$BRANCH" = "master" ]; then
      echo "⚠️  You're on master. Create a feature branch first:"
      echo "    git checkout -b feat/my-feature"
      exit 1
    fi
    echo "📤 Pushing branch '$BRANCH' to GitHub..."
    git push "$GITHUB_REMOTE" "$BRANCH" -u
    echo ""
    echo "✅ Branch pushed. Create a PR with:"
    echo "   bash scripts/git-flow.sh pr \"Your PR title\""
    echo "   Or: gh pr create --title \"...\" --body \"...\""
    ;;

  pr)
    TITLE="${1:-$(git log -1 --pretty=%s)}"
    BRANCH=$(git branch --show-current)
    if [ "$BRANCH" = "master" ]; then
      echo "❌ Cannot create PR from master. Use a feature branch."
      exit 1
    fi
    echo "📝 Creating PR: $TITLE"
    echo "   Branch: $BRANCH → master"
    gh pr create \
      --title "$TITLE" \
      --body "$(cat <<EOF
## Summary
Branch: \`$BRANCH\`

## Changes
$(git log master.."$BRANCH" --oneline 2>/dev/null || echo "New branch")

## Deploy
Auto-deploys to production when merged to master.

---
🤖 Generated by BlockID CI/CD
EOF
)" \
      --base master \
      --head "$BRANCH"
    echo ""
    echo "✅ PR created. Review at: https://github.com/Blockid-au/blockid/pulls"
    ;;

  release)
    NOTE="${1:-Release}"
    BRANCH=$(git branch --show-current)
    if [ "$BRANCH" = "master" ]; then
      echo "🚀 Deploying master directly..."
    else
      echo "🔀 Merging $BRANCH into master..."
      git checkout master
      git merge "$BRANCH" --no-edit
      git branch -d "$BRANCH" 2>/dev/null || true
    fi
    echo "📤 Pushing master to GitHub + GitLab..."
    git push "$GITHUB_REMOTE" master
    git push "$GITLAB_REMOTE" master 2>/dev/null || echo "⚠️  GitLab push failed (non-critical)"
    echo "🔨 Running deploy..."
    DEPLOY_NOTE="$NOTE" bash "$SCRIPT_DIR/deploy-live.sh"
    ;;

  deploy)
    echo "📥 Pulling latest master from GitHub..."
    git pull "$GITHUB_REMOTE" master --ff-only
    echo "🔨 Running deploy..."
    DEPLOY_NOTE="GitHub pull + deploy" bash "$SCRIPT_DIR/deploy-live.sh"
    ;;

  sync)
    echo "🔄 Syncing master to both remotes..."
    git push "$GITHUB_REMOTE" master
    git push "$GITLAB_REMOTE" master 2>/dev/null || echo "⚠️  GitLab push failed (non-critical)"
    echo "✅ Synced."
    ;;

  help|*)
    echo "BlockID.au — GitHub Flow"
    echo ""
    echo "Usage: bash scripts/git-flow.sh <command>"
    echo ""
    echo "Commands:"
    echo "  push            Push current branch to GitHub"
    echo "  pr \"title\"      Create PR (current branch → master)"
    echo "  release \"note\"  Merge + deploy (local merge)"
    echo "  deploy          Pull from GitHub master + deploy"
    echo "  sync            Push master to GitHub + GitLab"
    echo ""
    echo "Flow:"
    echo "  1. git checkout -b feat/my-feature"
    echo "  2. (make changes)"
    echo "  3. git add . && git commit -m \"feat: ...\" "
    echo "  4. bash scripts/git-flow.sh push"
    echo "  5. bash scripts/git-flow.sh pr \"My feature\""
    echo "  6. (review on GitHub)"
    echo "  7. bash scripts/git-flow.sh release \"My feature\""
    ;;
esac
