#!/usr/bin/env node
/**
 * Seed Stripe products + prices for the 12-SKU v2.0 pricing matrix.
 *
 * Reads:  web/src/config/pricing/stripe-seed.json  (generated by build-plans.ts)
 * Writes: Stripe products/prices (via API) + UPDATE plans.stripe_price_id in DB
 *
 * Env:
 *   STRIPE_SECRET_KEY               (LIVE keys create real products — use --dry-run first)
 *   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
 *
 * Flags:
 *   --dry-run           List actions without touching Stripe or DB.
 *   --test-mode         Use STRIPE_SECRET_KEY_TEST if present (falls back to LIVE).
 *   --skus <a,b,c>      Only seed the given plan_ids.
 *   --update-db-only    Skip Stripe creates; only sync existing plan.stripe_price_id
 *                       from env vars STRIPE_PRICE_<SKU>.
 *
 * Idempotency:
 *   - Products keyed by metadata.plan_id — reused on re-run.
 *   - Monthly and annual prices keyed by metadata.plan_id + metadata.interval.
 *   - Prices are immutable in Stripe; on amount change we create a new price
 *     and mark the old one inactive.
 *
 * Owner: CFO agent (W1 track). Wired to `scripts/build-plans.ts` output.
 */

import Stripe from "stripe";
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "node:fs";
import { argv, env, exit } from "node:process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SEED_JSON = join(__dirname, "..", "src", "config", "pricing", "stripe-seed.json");

const args = new Set(argv.slice(2));
const DRY_RUN = args.has("--dry-run");
const TEST_MODE = args.has("--test-mode");
const UPDATE_DB_ONLY = args.has("--update-db-only");
const SKUS_ARG = argv.find((a) => a.startsWith("--skus="));
const SKUS_FILTER = SKUS_ARG ? new Set(SKUS_ARG.split("=")[1].split(",")) : null;

function pickStripeKey() {
  if (TEST_MODE && env.STRIPE_SECRET_KEY_TEST) return env.STRIPE_SECRET_KEY_TEST;
  if (!env.STRIPE_SECRET_KEY) {
    console.error("[seed-stripe] STRIPE_SECRET_KEY missing in env");
    exit(1);
  }
  return env.STRIPE_SECRET_KEY;
}

async function ensureProduct(stripe, plan) {
  // Search by metadata.plan_id (Stripe API v2023-08-16+ supports metadata search)
  const existing = await stripe.products.search({
    query: `metadata['plan_id']:'${plan.plan_id}'`,
    limit: 1,
  });
  if (existing.data[0]) {
    console.log(`  ~ product exists ${plan.plan_id} → ${existing.data[0].id}`);
    return existing.data[0];
  }
  if (DRY_RUN) {
    console.log(`  [dry] create product ${plan.plan_id} (${plan.product_name})`);
    return { id: `prod_dry_${plan.plan_id}` };
  }
  const p = await stripe.products.create({
    name: `BlockID ${plan.product_name}`,
    metadata: { plan_id: plan.plan_id, segment: plan.segment },
    active: true,
  });
  console.log(`  + product created ${plan.plan_id} → ${p.id}`);
  return p;
}

async function ensurePrice(stripe, product, plan, interval, amount) {
  if (!amount || amount === 0) {
    console.log(`  - skip ${plan.plan_id} ${interval}: amount=${amount}`);
    return null;
  }
  const existing = await stripe.prices.search({
    query: `metadata['plan_id']:'${plan.plan_id}' AND metadata['interval']:'${interval}' AND active:'true'`,
    limit: 1,
  });
  if (existing.data[0] && existing.data[0].unit_amount === amount) {
    console.log(`  ~ price exists ${plan.plan_id} ${interval} (${amount}c) → ${existing.data[0].id}`);
    return existing.data[0];
  }
  // Deactivate stale price with same key but different amount
  for (const stale of existing.data) {
    if (stale.unit_amount !== amount && !DRY_RUN) {
      await stripe.prices.update(stale.id, { active: false });
      console.log(`  * deactivated stale ${stale.id} (${stale.unit_amount}c)`);
    }
  }
  if (DRY_RUN) {
    console.log(`  [dry] create price ${plan.plan_id} ${interval}=${amount}c`);
    return { id: `price_dry_${plan.plan_id}_${interval}` };
  }
  const priceObj = await stripe.prices.create({
    product: product.id,
    unit_amount: amount,
    currency: plan.currency,
    recurring: interval === "monthly" || interval === "annual" ? { interval: interval === "annual" ? "year" : "month" } : undefined,
    metadata: { plan_id: plan.plan_id, interval },
  });
  console.log(`  + price created ${plan.plan_id} ${interval}=${amount}c → ${priceObj.id}`);
  return priceObj;
}

async function updatePlansDb(supabase, plan, priceMonthly, priceAnnual) {
  if (DRY_RUN) {
    console.log(`  [dry] plans.update ${plan.plan_id} stripe_price_id=${priceMonthly?.id ?? "null"}, annual=${priceAnnual?.id ?? "null"}`);
    return;
  }
  const { error } = await supabase
    .from("plans")
    .update({
      stripe_price_id: priceMonthly?.id ?? null,
      stripe_price_id_annual: priceAnnual?.id ?? null,
      updated_at: new Date().toISOString(),
    })
    .eq("id", plan.plan_id);
  if (error) {
    console.error(`  ! plans.update ${plan.plan_id} failed: ${error.message}`);
  } else {
    console.log(`  ✓ plans.update ${plan.plan_id} → ${priceMonthly?.id ?? "null"}`);
  }
}

async function syncFromEnv(supabase) {
  const map = [
    ["founder_starter", env.STRIPE_PRICE_FOUNDER],
    ["founder_growth", env.STRIPE_PRICE_GROWTH],
    ["founder_scale", env.STRIPE_PRICE_GROWTH_499],
  ];
  for (const [planId, priceId] of map) {
    if (!priceId) {
      console.log(`  - skip ${planId}: env var missing`);
      continue;
    }
    if (DRY_RUN) {
      console.log(`  [dry] plans.update ${planId} stripe_price_id=${priceId}`);
      continue;
    }
    const { error } = await supabase
      .from("plans")
      .update({ stripe_price_id: priceId, updated_at: new Date().toISOString() })
      .eq("id", planId);
    if (error) console.error(`  ! ${planId}: ${error.message}`);
    else console.log(`  ✓ ${planId} → ${priceId}`);
  }
}

async function main() {
  console.log(`[seed-stripe] mode=${DRY_RUN ? "dry-run" : "LIVE"} test=${TEST_MODE} update-db-only=${UPDATE_DB_ONLY}${SKUS_FILTER ? ` skus=${[...SKUS_FILTER].join(",")}` : ""}`);

  const supabaseUrl = env.SUPABASE_URL || "http://localhost:8000";
  const supabaseKey = env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseKey) {
    console.error("[seed-stripe] SUPABASE_SERVICE_ROLE_KEY missing");
    exit(1);
  }
  const supabase = createClient(supabaseUrl, supabaseKey, { auth: { persistSession: false } });

  if (UPDATE_DB_ONLY) {
    console.log("[seed-stripe] --update-db-only: mapping existing env price IDs to new SKUs");
    await syncFromEnv(supabase);
    console.log("[seed-stripe] done (db-only sync)");
    return;
  }

  const stripe = new Stripe(pickStripeKey(), { apiVersion: "2024-04-10" });
  const seed = JSON.parse(readFileSync(SEED_JSON, "utf8"));
  const plans = SKUS_FILTER ? seed.plans.filter((p) => SKUS_FILTER.has(p.plan_id)) : seed.plans;

  console.log(`[seed-stripe] ${plans.length} SKUs to process from ${SEED_JSON}`);
  for (const plan of plans) {
    console.log(`\n[${plan.plan_id}] ${plan.product_name} (${plan.segment})`);
    try {
      const product = await ensureProduct(stripe, plan);
      const monthly = await ensurePrice(stripe, product, plan, "monthly", plan.monthly_amount_cents);
      const annual = await ensurePrice(stripe, product, plan, "annual", plan.annual_amount_cents);
      await updatePlansDb(supabase, plan, monthly, annual);
    } catch (e) {
      console.error(`  ! ${plan.plan_id} failed: ${e.message}`);
    }
  }
  console.log("\n[seed-stripe] done");
}

main().catch((e) => {
  console.error("[seed-stripe] fatal", e);
  exit(1);
});
