// POST /api/cron/milestone-report — Per-milestone C-Level breakdown reporter.
//
// Triggered automatically by agent-orchestrator after stageUpdateArtifacts creates
// a new milestone, and also runs hourly as a defensive sweep in case the inline
// call was missed. Idempotent: a milestone is reported exactly once, tracked via
// content/reports/milestone-report-state.json.
//
// For each NEW milestone (since last run) it produces:
//   1. content/reports/milestone-<id>-v<version>.md — full breakdown per C-Level
//      with tasks, rationale, commits, and version impact.
//   2. Telegram summary to admin (mdEscape v2 format).
//   3. Email digest to admin@blockid.au.
//
// Reads project-state.json (single source of truth) for milestones / tasks.

import { NextResponse } from "next/server";
import * as fs from "fs";
import { loadProjectState, type Milestone, type PlanTask } from "@/lib/project-state";
import { sendTelegram, mdEscape } from "@/lib/telegram";
import { sendEmail } from "@/lib/email";
import { checkRateLimit } from "@/lib/rate-limit";

export const dynamic = "force-dynamic";
export const maxDuration = 120;

const CRON_SECRET = process.env.CRON_SECRET;
const REPORTS_DIR = "/home/dovanlong/blockid.au/web/content/reports";
const STATE_FILE = `${REPORTS_DIR}/milestone-report-state.json`;
const ADMIN_EMAIL = "admin@blockid.au";

interface ReportState {
  reportedMilestoneIds: string[];
  lastRun: string;
}

function loadReportState(): ReportState {
  try {
    return JSON.parse(fs.readFileSync(STATE_FILE, "utf8"));
  } catch {
    return { reportedMilestoneIds: [], lastRun: "" };
  }
}

function saveReportState(s: ReportState) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  fs.writeFileSync(STATE_FILE, JSON.stringify(s, null, 2) + "\n");
}

function tasksByAgent(tasks: PlanTask[]): Map<string, PlanTask[]> {
  const m = new Map<string, PlanTask[]>();
  for (const t of tasks) {
    const k = (t.agent || "unknown").toLowerCase();
    const list = m.get(k) ?? [];
    list.push(t);
    m.set(k, list);
  }
  return m;
}

function renderMilestoneMarkdown(milestone: Milestone, tasks: PlanTask[], targets: { thirtyDay: string }): string {
  const grouped = tasksByAgent(tasks);
  const agents = [...grouped.keys()].sort();
  const lines: string[] = [
    `# Milestone ${milestone.id} — v${milestone.version}`,
    ``,
    `**Completed:** ${milestone.completedAt}`,
    `**Tasks shipped:** ${milestone.taskIds.length}`,
    `**C-Levels involved:** ${agents.map(a => a.toUpperCase()).join(", ") || "—"}`,
    ``,
    `> ${milestone.title}`,
    ``,
    `## 30-Day North Star context`,
    targets.thirtyDay,
    ``,
    `## Per-C-Level breakdown`,
    ``,
  ];

  for (const agent of agents) {
    const list = grouped.get(agent)!;
    lines.push(`### ${agent.toUpperCase()} — ${list.length} task(s) shipped`);
    lines.push(``);
    for (const t of list) {
      lines.push(`#### \`${t.id}\` — ${t.title}`);
      lines.push(``);
      lines.push(`- **Impact:** ${t.versionImpact}`);
      lines.push(`- **Commit:** ${t.commit ? `\`${t.commit}\`` : "_(not linked)_"}`);
      lines.push(`- **Completed:** ${t.completedAt ?? "—"}`);
      lines.push(`- **Rationale:** ${t.rationale || "_(no rationale recorded)_"}`);
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`_Generated by /api/cron/milestone-report (CEO implementing-plan loop)._`);
  return lines.join("\n");
}

function renderTelegramSummary(milestone: Milestone, tasks: PlanTask[]): string {
  const grouped = tasksByAgent(tasks);
  const byAgent = [...grouped.entries()]
    .map(([a, list]) => `${a.toUpperCase()}: ${list.length}`)
    .join(", ");
  const lines = [
    `🚀 *BlockID Milestone ${mdEscape(milestone.id)} — v${mdEscape(milestone.version)}*`,
    ``,
    mdEscape(milestone.title.slice(0, 240)),
    ``,
    `🧭 *Breakdown:* ${mdEscape(byAgent || "—")}`,
    `📦 *Tasks:* ${milestone.taskIds.length}`,
    `📄 _Full report:_ content/reports/milestone\\-${mdEscape(milestone.id)}\\-v${mdEscape(milestone.version)}\\.md`,
  ];
  return lines.join("\n");
}

function renderEmailHtml(milestone: Milestone, tasks: PlanTask[], markdown: string): string {
  const grouped = tasksByAgent(tasks);
  const rows = [...grouped.entries()]
    .map(([agent, list]) => {
      const items = list.map(t => `<li><code>${t.id}</code> — ${t.title}</li>`).join("");
      return `<tr><td valign="top"><strong>${agent.toUpperCase()}</strong></td><td><ul>${items}</ul></td></tr>`;
    })
    .join("");
  return `
<!doctype html>
<html><body style="font-family:Inter,system-ui,sans-serif;max-width:720px;margin:0 auto;padding:24px;">
<h1>Milestone ${milestone.id} — v${milestone.version}</h1>
<p style="color:#555">${milestone.title}</p>
<p><strong>Completed:</strong> ${milestone.completedAt}<br/>
<strong>Tasks shipped:</strong> ${milestone.taskIds.length}</p>
<h2>Per-C-Level breakdown</h2>
<table cellpadding="6" cellspacing="0" border="0" style="border-collapse:collapse;width:100%;">${rows}</table>
<hr/>
<details><summary>Full markdown report</summary><pre style="white-space:pre-wrap;font-size:12px;background:#f6f8fa;padding:12px;border-radius:8px;">${markdown.replace(/[<>&]/g, c => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" }[c]!))}</pre></details>
<p style="color:#888;font-size:12px;margin-top:24px;">Generated by /api/cron/milestone-report — BlockID.au CEO implementing-plan loop.</p>
</body></html>`.trim();
}

async function reportOneMilestone(milestone: Milestone, allTasks: PlanTask[]): Promise<{ id: string; mdPath: string; tg: boolean; email: boolean }> {
  const taskIdSet = new Set(milestone.taskIds);
  const tasks = allTasks.filter(t => taskIdSet.has(t.id));

  const targets = {
    thirtyDay:
      "Target: 10 paying customers, AUD $1k–$3k revenue, AUD $1k MRR, 100 company profiles, 50 assessments. See `.claude/goals/30day-validation-mvp.md`.",
  };

  const md = renderMilestoneMarkdown(milestone, tasks, targets);
  const safeVersion = milestone.version.replace(/[^a-zA-Z0-9.]/g, "");
  const mdPath = `${REPORTS_DIR}/milestone-${milestone.id}-v${safeVersion}.md`;
  fs.writeFileSync(mdPath, md);

  let tgOk = false;
  let emailOk = false;
  try {
    await sendTelegram(renderTelegramSummary(milestone, tasks));
    tgOk = true;
  } catch { /* swallow — Telegram is best-effort */ }

  try {
    await sendEmail({
      to: ADMIN_EMAIL,
      subject: `🚀 BlockID milestone ${milestone.id} — v${milestone.version}`,
      html: renderEmailHtml(milestone, tasks, md),
    });
    emailOk = true;
  } catch { /* swallow — email is best-effort */ }

  return { id: milestone.id, mdPath, tg: tgOk, email: emailOk };
}

export async function POST(request: Request) {
  const auth = request.headers.get("authorization");
  if (CRON_SECRET && auth !== `Bearer ${CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const rl = await checkRateLimit("milestone-report", 6, 600_000);
  if (!rl.allowed) {
    return NextResponse.json({ error: "Rate limited", retryAfter: rl.resetIn }, { status: 429 });
  }

  const ps = loadProjectState();
  const reportState = loadReportState();
  const reported = new Set(reportState.reportedMilestoneIds);

  // Backfill: if this is the first run, mark every existing milestone older than
  // 24h as already-reported so we don't spam admin with 20 years of history.
  if (reportState.reportedMilestoneIds.length === 0 && ps.milestones.length > 1) {
    const cutoff = Date.now() - 24 * 60 * 60 * 1000;
    for (const m of ps.milestones) {
      if (Date.parse(m.completedAt) < cutoff) reported.add(m.id);
    }
  }

  const fresh = ps.milestones.filter(m => !reported.has(m.id));

  const sent: Array<{ id: string; mdPath: string; tg: boolean; email: boolean }> = [];
  for (const m of fresh) {
    try {
      const r = await reportOneMilestone(m, ps.plan.tasks);
      sent.push(r);
      reported.add(m.id);
    } catch (err) {
      // Don't mark reported on failure — next sweep will retry.
      // eslint-disable-next-line no-console
      console.error("milestone-report failed for", m.id, err);
    }
  }

  saveReportState({
    reportedMilestoneIds: [...reported],
    lastRun: new Date().toISOString(),
  });

  return NextResponse.json({
    ok: true,
    milestonesReported: sent.length,
    sent,
    totalReported: reported.size,
  });
}
