// CGH — Capital Governance Health (lead CFO). Annex §3 CGH-01…10. No existing
// guiding question is primary here, so every item is an overlay (absorbs G31 overlay CT).

import { ALL_STAGES, defineItems, span } from "../define";

export const CGH_ITEMS = defineItems("CGH", [
  {
    id: "CGH-01",
    title: { en: "Cap table matches the register", vi: "Bảng sở hữu khớp với sổ đăng ký" },
    question: { en: "Does the cap table match the company register and the ASIC record?", vi: "Bảng sở hữu có khớp với sổ đăng ký cổ đông của công ty và hồ sơ ASIC không?" },
    supporting: ["clo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T1"], sources: ["asic", "cap_table"], freshnessDays: 180 },
    benchmarkRef: "Corporations Act 2001 s169",
    redFlags: [
      { key: "cgh.cap_table_register_mismatch", rule: "Cap table differs from the register or ASIC" },
      { key: "cgh.undocumented_safes", rule: "SAFEs or notes not documented" },
    ],
    signal: "capital_structure",
    rule: "Reconcile the cap table with the s169 register and ASIC whenever a source is available.",
  },
  {
    id: "CGH-02",
    title: { en: "Founder ownership", vi: "Tỷ lệ sở hữu của nhà sáng lập" },
    question: { en: "Do founders retain enough ownership for the stage, without dead equity?", vi: "Nhà sáng lập có giữ đủ tỷ lệ sở hữu phù hợp giai đoạn và không có cổ phần \"chết\" không?" },
    supporting: ["chro"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["cap_table"], freshnessDays: 180 },
    benchmarkRef: "Carta founder ownership (via secondary sources)",
    redFlags: [{ key: "cgh.low_founder_stake_or_dead_equity", rule: "Very low founder stake early, or dead equity" }],
    signal: "capital_structure",
  },
  {
    id: "CGH-03",
    title: { en: "Dilution per round", vi: "Mức pha loãng mỗi vòng" },
    question: { en: "How much did each priced round or conversion dilute existing holders?", vi: "Mỗi vòng định giá hoặc chuyển đổi đã pha loãng cổ đông hiện hữu bao nhiêu?" },
    supporting: ["clo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2"], sources: ["contract", "cap_table"], freshnessDays: 365 },
    redFlags: [{ key: "cgh.dilution_over_30pct", rule: "More than 30% dilution in one round" }],
    signal: "capital_structure",
  },
  {
    id: "CGH-04",
    title: { en: "Runway and default alive", vi: "Thời gian hoạt động còn lại và khả năng tự sống" },
    question: { en: "How many months of runway remain, and is the company default alive?", vi: "Công ty còn bao nhiêu tháng hoạt động, và có thể tự sống nếu không gọi thêm vốn không?" },
    supporting: ["coo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T1"], sources: ["bank", "financial_model"], freshnessDays: 60 },
    benchmarkRef: "Paul Graham, Default Alive or Default Dead 2015",
    redFlags: [{ key: "cgh.runway_under_6m", rule: "Under 6 months of runway, or default dead" }],
    signal: "capital_structure", metricsKey: "runway",
  },
  {
    id: "CGH-05",
    title: { en: "Round history versus Australian medians", vi: "Lịch sử gọi vốn so với trung vị tại Úc" },
    question: { en: "How do past rounds compare with Australian medians for each stage?", vi: "Các vòng gọi vốn trước so với trung vị tại Úc theo từng giai đoạn thế nào?" },
    supporting: ["clo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2"], sources: ["contract"], freshnessDays: 365 },
    benchmarkRef: "Cut Through Venture 2025",
    redFlags: [{ key: "cgh.serial_bridges", rule: "Serial bridge rounds" }],
    signal: "capital_structure",
  },
  {
    id: "CGH-06",
    title: { en: "Convertible overhang", vi: "Công cụ chuyển đổi tồn đọng" },
    question: { en: "What SAFEs and notes are outstanding, and on what caps?", vi: "Còn những SAFE và giấy nợ chuyển đổi nào chưa chuyển đổi, với mức trần định giá nào?" },
    supporting: ["clo"], stages: span("PS", "A"),
    evidence: { acceptedTiers: ["T2"], sources: ["contract"], freshnessDays: 180 },
    redFlags: [{ key: "cgh.stacked_uncapped_safes", rule: "Stacked uncapped SAFEs" }],
    signal: "capital_structure",
  },
  {
    id: "CGH-07",
    title: { en: "Board and governance", vi: "Hội đồng quản trị và quản trị công ty" },
    question: { en: "Does a board meet on a regular cadence with minutes kept?", vi: "Hội đồng quản trị có họp định kỳ và lưu biên bản không?" },
    supporting: ["clo", "coo"], stages: span("A"),
    evidence: { acceptedTiers: ["T2"], sources: ["board_minutes"], freshnessDays: 180 },
    redFlags: [{ key: "cgh.no_board_post_a", rule: "No board after Series A" }],
    signal: null,
  },
  {
    id: "CGH-08",
    title: { en: "ESOP pool", vi: "Quỹ quyền chọn cổ phần nhân viên (ESOP)" },
    question: { en: "Is the employee option pool documented under a plan, with grants recorded?", vi: "Quỹ quyền chọn cho nhân viên đã được lập thành chương trình và ghi nhận các lần cấp chưa?" },
    supporting: ["chro", "clo"], stages: span("S"),
    evidence: { acceptedTiers: ["T2"], sources: ["document", "cap_table"], freshnessDays: 365 },
    redFlags: [{ key: "cgh.undocumented_options", rule: "Options promised but not documented" }],
    signal: "capital_structure",
  },
  {
    id: "CGH-09",
    title: { en: "Investor quality", vi: "Chất lượng nhà đầu tư" },
    question: { en: "Is there a credible lead, and are existing investors known and vetted?", vi: "Có nhà đầu tư dẫn dắt đáng tin cậy không, và các nhà đầu tư hiện hữu có được xác minh không?" },
    supporting: ["clo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2", "T3"], sources: ["cap_table", "contract"], freshnessDays: 365 },
    benchmarkRef: "Kerr, Lerner & Schoar 2010 (NBER w15831)",
    redFlags: [{ key: "cgh.unvetted_investors", rule: "Unvetted investors on the register" }],
    signal: "capital_structure",
  },
  {
    id: "CGH-10",
    title: { en: "Financial controls", vi: "Kiểm soát tài chính" },
    question: { en: "Are the books closed monthly, with an audit from Series B?", vi: "Sổ sách có được khoá hằng tháng, và có kiểm toán từ vòng Series B không?" },
    supporting: ["coo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["xero"], freshnessDays: 90 },
    redFlags: [{ key: "cgh.no_bookkeeping", rule: "No bookkeeping" }],
    signal: null,
  },
]);
