// FTV — Founder Traction Velocity (lead CHRO). Annex §3 FTV-01…09.
// Fairness rule (§4.2): FTV never scores demographic or credential-prestige
// attributes; registry.test.ts scans every FTV string for them.

import { ALL_STAGES, defineItems, span } from "../define";

export const FTV_ITEMS = defineItems("FTV", [
  {
    id: "FTV-01",
    title: { en: "Founder–problem fit", vi: "Mức phù hợp giữa nhà sáng lập và vấn đề" },
    question: { en: "Why is this founding team the right one to solve this problem?", vi: "Vì sao đội sáng lập này phù hợp để giải quyết vấn đề này?" },
    questionRefs: ["blockid:question:founder_profile:7d1532c5f2a434cb", "blockid:question:founder_profile:1a6358c2526fa381"],
    supporting: ["ceo"], stages: span("PS", "A"),
    evidence: { acceptedTiers: ["T2", "T3"], sources: ["document", "reference", "founder_input"], freshnessDays: 365 },
    redFlags: [{ key: "ftv.no_why_us", rule: "Founders cannot state why they are the team for this problem" }],
    signal: "team",
  },
  {
    id: "FTV-02",
    title: { en: "Can build and sell in-house", vi: "Tự xây dựng và tự bán được" },
    question: { en: "Does the founding team cover both building the product and selling it?", vi: "Đội sáng lập có tự đảm nhận được cả xây dựng sản phẩm lẫn bán hàng không?" },
    questionRefs: ["blockid:question:team:05b12dca2fd5576c", "blockid:question:team:9363f15231dde2c7", "blockid:question:team_structure:d8e3b1fd289c1b20"],
    supporting: ["ceo", "coo"], stages: span("PS", "S"),
    evidence: { acceptedTiers: ["T1", "T2"], sources: ["contract", "git"], freshnessDays: 180 },
    benchmarkRef: "First Round Capital 10-year review 2015",
    redFlags: [{ key: "ftv.core_product_outsourced", rule: "Core product build is outsourced" }],
    signal: "team",
  },
  {
    id: "FTV-03",
    title: { en: "Full-time commitment", vi: "Cam kết toàn thời gian" },
    question: { en: "What share of the founders work on the company full-time?", vi: "Bao nhiêu phần trong số nhà sáng lập làm việc toàn thời gian cho công ty?" },
    questionRefs: ["blockid:question:team:d78f9584c696bb84"],
    supporting: ["coo"], stages: span("PS", "S"),
    evidence: { acceptedTiers: ["T1"], sources: ["payroll", "ato"], freshnessDays: 180 },
    redFlags: [{ key: "ftv.all_part_time", rule: "All founders are part-time" }],
    signal: "team",
  },
  {
    id: "FTV-04",
    title: { en: "Industry experience and track record", vi: "Kinh nghiệm ngành và thành tích" },
    question: { en: "What verifiable industry experience, prior ventures or exits does the team bring?", vi: "Đội ngũ có kinh nghiệm ngành, dự án trước hoặc thương vụ thoái vốn nào kiểm chứng được?" },
    questionRefs: ["blockid:question:founder_profile:9ae8fd3780184e53", "blockid:question:founder_profile:86630d5700dae95d"],
    supporting: ["clo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T1"], sources: ["asic", "reference"], freshnessDays: 365 },
    benchmarkRef: "Gompers et al. 2006 (NBER w12592)",
    redFlags: [{ key: "ftv.unverifiable_track_record", rule: "Track-record claims cannot be verified" }],
    signal: "team",
  },
  {
    id: "FTV-05",
    title: { en: "Velocity between checkpoints", vi: "Tốc độ tiến triển giữa các mốc" },
    question: { en: "How much shipped work and metric movement happened since the last checkpoint?", vi: "Từ mốc kiểm tra trước đến nay, đội đã giao được gì và chỉ số đã thay đổi bao nhiêu?" },
    questionRefs: ["blockid:question:team_structure:a188bb064bd37212"],
    supporting: ["coo"], stages: span("PS", "A"),
    evidence: { acceptedTiers: ["T1", "T3"], sources: ["analytics", "git", "document"], freshnessDays: 90 },
    redFlags: [{ key: "ftv.stale_deck", rule: "Same deck and metrics months later" }],
    signal: "team",
  },
  {
    id: "FTV-06",
    title: { en: "Founder agreement and vesting", vi: "Thoả thuận nhà sáng lập và vesting" },
    question: { en: "Is there a signed founder agreement with cliff vesting for every founder?", vi: "Đã có thoả thuận nhà sáng lập đã ký với vesting có cliff cho từng nhà sáng lập chưa?" },
    supporting: ["clo"], stages: span("PS", "A"),
    evidence: { acceptedTiers: ["T2"], sources: ["contract"], freshnessDays: 365 },
    redFlags: [{ key: "ftv.departed_founder_stake", rule: "A departed founder still holds a large stake" }],
    signal: "team",
  },
  {
    id: "FTV-07",
    title: { en: "Talent magnet", vi: "Sức hút nhân tài" },
    question: { en: "Has the company attracted and kept senior hires and advisers?", vi: "Công ty đã thu hút và giữ được nhân sự cấp cao và cố vấn chưa?" },
    questionRefs: ["blockid:question:team:6e680aa9167ae5a6", "blockid:question:team_structure:bf8118940f1046c3", "blockid:question:team_structure:78c0a15277b3e586"],
    supporting: ["ceo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1", "T3"], sources: ["payroll", "cap_table", "document"], freshnessDays: 180 },
    redFlags: [{ key: "ftv.no_senior_hires_post_a", rule: "No senior hires after Series A" }],
    signal: "team",
  },
  {
    id: "FTV-08",
    title: { en: "Candour and self-awareness", vi: "Thẳng thắn và tự nhận thức" },
    question: { en: "Do references and diligence answers match the metrics the founders present?", vi: "Người tham chiếu và câu trả lời thẩm định có khớp với số liệu nhà sáng lập trình bày không?" },
    supporting: ["ceo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2"], sources: ["reference"], freshnessDays: 365 },
    redFlags: [{ key: "ftv.inflated_metrics", rule: "Metrics inflated during diligence" }],
    signal: "team",
  },
  {
    id: "FTV-09",
    title: { en: "Founder-to-CEO scaling", vi: "Từ nhà sáng lập thành CEO quy mô lớn" },
    question: { en: "Is there an executive bench so the CEO is not the bottleneck?", vi: "Đã có đội ngũ điều hành để CEO không trở thành nút thắt chưa?" },
    supporting: ["ceo", "coo"], stages: span("A"),
    evidence: { acceptedTiers: ["T2"], sources: ["board_minutes"], freshnessDays: 180 },
    benchmarkRef: "Ewens & Marx 2018 (RFS 31(4))",
    redFlags: [{ key: "ftv.ceo_bottleneck", rule: "CEO is the decision bottleneck" }],
    signal: "team",
  },
]);
