// IRI — Investor Readiness Index (lead CLO; CFO must judge IRI-02/03/08, D24-c).
// Annex §3 IRI-01…09. Diligence readiness; absorbs G31 overlay LQ.

import { ALL_STAGES, defineItems, span } from "../define";

export const IRI_ITEMS = defineItems("IRI", [
  {
    id: "IRI-01",
    title: { en: "Data-room completeness by stage", vi: "Độ đầy đủ của phòng dữ liệu theo giai đoạn" },
    question: { en: "Does the data room hold the items investors expect at this stage, organised and current?", vi: "Phòng dữ liệu có đủ tài liệu nhà đầu tư cần ở giai đoạn này, được sắp xếp và cập nhật không?" },
    questionRefs: ["blockid:question:dataroom:90445a71fe794e79", "blockid:question:dataroom:375b42f9f70a36ff", "blockid:question:dataroom:d954c78126c19807", "blockid:question:dataroom:38e27593719c916a", "blockid:question:documents:b02bae8b8d10755c"],
    supporting: ["cdo", "cfo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2", "T3"], sources: ["data_room"], freshnessDays: 180 },
    benchmarkRef: "AirTree data room guide",
    redFlags: [{ key: "iri.missing_basics", rule: "Data room missing stage basics" }],
    signal: null,
  },
  {
    id: "IRI-02",
    title: { en: "Financial model and assumptions", vi: "Mô hình tài chính và giả định" },
    question: { en: "Is there a driver-based or three-statement model with sourced assumptions?", vi: "Có mô hình tài chính theo động lực hoặc ba báo cáo với giả định có nguồn không?" },
    questionRefs: ["blockid:question:documents:62c76cf7c9fce351"],
    supporting: ["cfo"], requiredJudgeAgents: ["cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1", "T3"], sources: ["financial_model", "xero"], freshnessDays: 180 },
    redFlags: [{ key: "iri.hockey_stick_no_drivers", rule: "Hockey-stick forecast without drivers" }],
    signal: null,
  },
  {
    id: "IRI-03",
    title: { en: "Metrics reconciled to systems of record", vi: "Số liệu đối chiếu với hệ thống gốc" },
    question: { en: "Do the metrics in the deck match the connectors, ledger and bank?", vi: "Số liệu trong bài trình bày có khớp với dữ liệu kết nối, sổ cái và ngân hàng không?" },
    supporting: ["cfo", "cdo"], requiredJudgeAgents: ["cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["stripe", "xero", "bank"], freshnessDays: 90 },
    redFlags: [{ key: "iri.deck_ledger_mismatch", rule: "Deck metrics differ from the ledger" }],
    signal: null,
  },
  {
    id: "IRI-04",
    title: { en: "Round terms and ask clarity", vi: "Điều khoản vòng gọi vốn và mức gọi vốn rõ ràng" },
    question: { en: "Are the raise, instrument, use of funds and milestones stated clearly?", vi: "Mức gọi vốn, công cụ, mục đích sử dụng vốn và các mốc có được nêu rõ không?" },
    questionRefs: ["blockid:question:documents:1f6fc9c753d7c096", "blockid:question:documents:0fd3c89c6e1d2315"],
    supporting: ["cfo", "ceo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2", "T3"], sources: ["contract", "deck"], freshnessDays: 180 },
    redFlags: [{ key: "iri.ask_without_milestones", rule: "Ask stated without milestones" }],
    signal: "capital_structure",
  },
  {
    id: "IRI-05",
    title: { en: "Reporting cadence", vi: "Nhịp báo cáo" },
    question: { en: "Are monthly investor or board KPI packs produced?", vi: "Công ty có gửi báo cáo KPI hằng tháng cho nhà đầu tư hoặc hội đồng quản trị không?" },
    supporting: ["cfo", "ceo"], stages: span("A"),
    evidence: { acceptedTiers: ["T2"], sources: ["board_minutes", "document"], freshnessDays: 90 },
    redFlags: [{ key: "iri.no_reporting_rhythm", rule: "No reporting rhythm" }],
    signal: null,
  },
  {
    id: "IRI-06",
    title: { en: "References available", vi: "Có người tham chiếu" },
    question: { en: "Can investors reach customers and prior investors as references?", vi: "Nhà đầu tư có liên hệ được khách hàng và nhà đầu tư trước để tham chiếu không?" },
    supporting: ["cro", "ceo"], stages: span("S"),
    evidence: { acceptedTiers: ["T2"], sources: ["reference"], freshnessDays: 180 },
    redFlags: [{ key: "iri.refuses_references", rule: "Refuses to provide references" }],
    signal: null,
  },
  {
    id: "IRI-07",
    title: { en: "ESIC eligibility documentation", vi: "Hồ sơ đủ điều kiện ESIC" },
    question: { en: "Is ESIC status supported by adviser documentation of the early-stage tests?", vi: "Tư cách ESIC có được xác nhận bằng tài liệu của cố vấn về các tiêu chí giai đoạn đầu không?" },
    supporting: ["cfo"], stages: span("PS", "S"),
    evidence: { acceptedTiers: ["T2"], sources: ["document"], freshnessDays: 365 },
    benchmarkRef: "ATO ESIC guidance",
    redFlags: [{ key: "iri.esic_claimed_without_advice", rule: "ESIC claimed without adviser support" }],
    signal: null,
  },
  {
    id: "IRI-08",
    title: { en: "R&D Tax Incentive registration", vi: "Đăng ký ưu đãi thuế R&D" },
    question: { en: "Are R&D Tax Incentive claims backed by AusIndustry registration within the deadline?", vi: "Khoản ưu đãi thuế R&D có được hỗ trợ bởi đăng ký AusIndustry đúng hạn không?" },
    supporting: ["cfo"], requiredJudgeAgents: ["cfo"], stages: span("PS", "A"),
    evidence: { acceptedTiers: ["T1"], sources: ["ausindustry", "ato"], freshnessDays: 365 },
    benchmarkRef: "ATO R&D Tax Incentive rates 2025",
    redFlags: [{ key: "iri.unregistered_rdti_claim", rule: "R&D claims without registration" }],
    signal: null,
  },
  {
    id: "IRI-09",
    title: { en: "Liquidity path readiness", vi: "Sẵn sàng cho lộ trình thanh khoản" },
    question: { en: "Which plausible exit routes and buyers exist, and what constrains a transaction?", vi: "Có những lộ trình thoái vốn và bên mua khả thi nào, và điều gì hạn chế giao dịch?" },
    supporting: ["ceo", "cfo"], stages: span("A"),
    evidence: { acceptedTiers: ["T3"], sources: ["document", "public_url"], freshnessDays: 365 },
    redFlags: [{ key: "iri.no_logical_buyer", rule: "No logical buyer identified" }],
    signal: "liquidity",
  },
]);
