// LCO — Legal Compliance Observability (lead CLO). Annex §3 LCO-01…12. No
// existing guiding question is primary here, so every item is an overlay (absorbs G31 overlays IP and ES).

import { ALL_STAGES, defineItems, span } from "../define";

export const LCO_ITEMS = defineItems("LCO", [
  {
    id: "LCO-01",
    title: { en: "All IP assigned to the company", vi: "Toàn bộ sở hữu trí tuệ đã chuyển giao cho công ty" },
    question: { en: "Have all founders, staff and contractors signed IP assignments to the company?", vi: "Tất cả nhà sáng lập, nhân viên và nhà thầu đã ký chuyển giao sở hữu trí tuệ cho công ty chưa?" },
    supporting: ["coo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2"], sources: ["contract"], freshnessDays: 365 },
    benchmarkRef: "IP Australia, Who owns IP",
    redFlags: [{ key: "lco.ip_not_assigned", rule: "No signed IP assignment deed, or pre-incorporation IP held by a founder", hard: true }],
    signal: "ip",
    rule: "A missing IP assignment is a hard red flag at every stage.",
  },
  {
    id: "LCO-02",
    title: { en: "Registered IP", vi: "Sở hữu trí tuệ đã đăng ký" },
    question: { en: "Which trade marks or patents are registered, and are there conflicts?", vi: "Nhãn hiệu hoặc sáng chế nào đã được đăng ký, và có xung đột nào không?" },
    supporting: ["coo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["ip_australia"], freshnessDays: 365 },
    redFlags: [{ key: "lco.trade_mark_conflict", rule: "Trade mark conflict" }],
    signal: "ip",
  },
  {
    id: "LCO-03",
    title: { en: "Open-source licences and freedom to operate", vi: "Giấy phép mã nguồn mở và quyền tự do khai thác" },
    question: { en: "Does a licence scan show distributed code is free of conflicting obligations?", vi: "Kết quả quét giấy phép có cho thấy mã phân phối không vướng nghĩa vụ xung đột không?" },
    supporting: ["ciso"], stages: span("A"),
    evidence: { acceptedTiers: ["T2"], sources: ["document", "git"], freshnessDays: 180 },
    redFlags: [{ key: "lco.gpl_in_distributed_code", rule: "GPL code in distributed product" }],
    signal: "ip",
  },
  {
    id: "LCO-04",
    title: { en: "Regulatory licences", vi: "Giấy phép theo quy định ngành" },
    question: { en: "Does the company hold every licence its activity requires (for example AFSL or TGA)?", vi: "Công ty có đủ mọi giấy phép hoạt động bắt buộc (ví dụ AFSL hoặc TGA) không?" },
    supporting: ["coo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T1"], sources: ["sector_register"], freshnessDays: 365 },
    redFlags: [{ key: "lco.unlicensed_activity", rule: "Regulated activity without a licence" }],
    signal: null,
  },
  {
    id: "LCO-05",
    title: { en: "Privacy Act and APPs", vi: "Luật Quyền riêng tư và các nguyên tắc APP" },
    question: { en: "Is there a privacy policy and breach log consistent with the Australian Privacy Principles?", vi: "Có chính sách quyền riêng tư và nhật ký vi phạm phù hợp với các Nguyên tắc Quyền riêng tư của Úc không?" },
    supporting: ["ciso"], stages: span("S"),
    evidence: { acceptedTiers: ["T3"], sources: ["document", "public_url"], freshnessDays: 365 },
    redFlags: [{ key: "lco.undisclosed_breach", rule: "Undisclosed data breach" }],
    signal: null,
  },
  {
    id: "LCO-06",
    title: { en: "Corporate structure", vi: "Cơ cấu pháp nhân" },
    question: { en: "Is the business held in a single Pty Ltd with a constitution matching the ASIC record?", vi: "Doanh nghiệp có nằm trong một công ty Pty Ltd duy nhất với điều lệ khớp hồ sơ ASIC không?" },
    supporting: ["cfo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T1"], sources: ["asic"], freshnessDays: 365 },
    redFlags: [{ key: "lco.structure_mismatch", rule: "Trust or offshore structure mismatch" }],
    signal: null,
  },
  {
    id: "LCO-07",
    title: { en: "Material contracts in writing", vi: "Hợp đồng quan trọng bằng văn bản" },
    question: { en: "Are material customer and supplier agreements signed, with change-of-control terms reviewed?", vi: "Các hợp đồng quan trọng với khách hàng và nhà cung cấp đã được ký, và điều khoản thay đổi quyền kiểm soát đã được rà soát chưa?" },
    supporting: ["coo", "cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T2"], sources: ["contract"], freshnessDays: 365 },
    redFlags: [{ key: "lco.handshake_deals", rule: "Material deals on a handshake" }],
    signal: null,
  },
  {
    id: "LCO-08",
    title: { en: "Employment and tax compliance", vi: "Tuân thủ lao động và thuế" },
    question: { en: "Are super, STP and BAS lodged on time, with workers correctly classified?", vi: "Hưu bổng, STP và BAS có được nộp đúng hạn, và người lao động có được phân loại đúng không?" },
    supporting: ["cfo", "coo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["ato", "payroll"], freshnessDays: 180 },
    redFlags: [{ key: "lco.sham_contracting_or_ato_debt", rule: "Sham contracting or ATO debt" }],
    signal: null,
  },
  {
    id: "LCO-09",
    title: { en: "Litigation and disputes", vi: "Tranh chấp và kiện tụng" },
    question: { en: "Are any disputes or proceedings pending or threatened?", vi: "Có tranh chấp hoặc vụ kiện nào đang diễn ra hoặc có nguy cơ xảy ra không?" },
    supporting: ["coo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T1"], sources: ["court_search"], freshnessDays: 180 },
    redFlags: [{ key: "lco.undisclosed_disputes", rule: "Undisclosed disputes" }],
    signal: null,
  },
  {
    id: "LCO-10",
    title: { en: "Related-party dealings", vi: "Giao dịch với bên liên quan" },
    question: { en: "Are related-party dealings disclosed, approved and at arm's length?", vi: "Giao dịch với bên liên quan có được công bố, phê duyệt và theo giá thị trường không?" },
    supporting: ["cfo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T2"], sources: ["board_minutes"], freshnessDays: 365 },
    redFlags: [{ key: "lco.founder_owned_supplier", rule: "Undisclosed founder-owned supplier" }],
    signal: null,
  },
  {
    id: "LCO-11",
    title: { en: "Insurance", vi: "Bảo hiểm" },
    question: { en: "Are professional indemnity, cyber and D&O policies in place?", vi: "Công ty đã có bảo hiểm trách nhiệm nghề nghiệp, an ninh mạng và trách nhiệm giám đốc chưa?" },
    supporting: ["coo", "ciso"], stages: span("S"),
    evidence: { acceptedTiers: ["T2"], sources: ["document"], freshnessDays: 365 },
    redFlags: [{ key: "lco.no_insurance", rule: "No insurance cover" }],
    signal: null,
  },
  {
    id: "LCO-12",
    title: { en: "Key-person continuity", vi: "Tính liên tục khi mất nhân sự chủ chốt" },
    question: { en: "Is there cover and a succession plan if a key person leaves?", vi: "Có bảo hiểm và kế hoạch kế nhiệm nếu một nhân sự chủ chốt rời đi không?" },
    supporting: ["coo"], stages: span("S"),
    evidence: { acceptedTiers: ["T2"], sources: ["document"], freshnessDays: 365 },
    redFlags: [{ key: "lco.single_person_knowledge", rule: "Critical knowledge held by one person" }],
    signal: "team",
  },
]);
