// MPC — Market Pull & Category (lead CMO; CPO supports MPC-01/02, D24-c). Annex §3 MPC-01…09.

import { ALL_STAGES, defineItems, span } from "../define";

export const MPC_ITEMS = defineItems("MPC", [
  {
    id: "MPC-01",
    title: { en: "One-sentence purpose and problem", vi: "Mục đích và vấn đề trong một câu" },
    question: { en: "Can the company state its purpose and the problem it solves in one clear sentence?", vi: "Công ty có nêu được mục đích và vấn đề mình giải quyết trong một câu rõ ràng không?" },
    questionRefs: ["blockid:question:idea:fc1b2eb085dbce9b"],
    supporting: ["cpo"], stages: span("PS", "PS"),
    evidence: { acceptedTiers: ["T3"], sources: ["deck"], freshnessDays: 365 },
    benchmarkRef: "Sequoia business plan guide",
    redFlags: [{ key: "mpc.buzzword_purpose", rule: "Purpose is buzzwords without a concrete problem" }],
    signal: null,
  },
  {
    id: "MPC-02",
    title: { en: "Validated customer pain", vi: "Nỗi đau khách hàng đã được xác nhận" },
    question: { en: "What interviews, LOIs or paid pilots show customers feel this pain?", vi: "Phỏng vấn, thư ý định (LOI) hay thí điểm có trả phí nào cho thấy khách hàng thật sự gặp vấn đề này?" },
    questionRefs: ["blockid:question:idea:ec82a16208aea1ee"],
    supporting: ["cpo", "cro"], stages: span("PS", "S"),
    evidence: { acceptedTiers: ["T2"], sources: ["contract", "document"], freshnessDays: 180 },
    benchmarkRef: "CB Insights startup failure reasons",
    redFlags: [{ key: "mpc.no_customer_contact", rule: "No evidence of customer contact" }],
    signal: "traction",
  },
  {
    id: "MPC-03",
    title: { en: "ICP and buyer defined", vi: "Xác định khách hàng lý tưởng và người mua" },
    question: { en: "Who is the ideal customer, and who pays versus who uses the product?", vi: "Khách hàng lý tưởng là ai, và ai trả tiền so với ai sử dụng sản phẩm?" },
    questionRefs: ["blockid:question:gtm_strategy:7dcd677e15986fef"],
    supporting: ["cro", "cpo"], stages: span("S", "A"),
    evidence: { acceptedTiers: ["T1"], sources: ["crm"], freshnessDays: 180 },
    redFlags: [{ key: "mpc.icp_everyone", rule: "ICP is \"everyone\"" }],
    signal: null,
  },
  {
    id: "MPC-04",
    title: { en: "Bottom-up market size", vi: "Quy mô thị trường tính từ dưới lên" },
    question: { en: "Is there a sourced, bottom-up path to a large revenue pool?", vi: "Có lộ trình tính từ dưới lên, có nguồn, dẫn tới một nguồn doanh thu đủ lớn không?" },
    questionRefs: ["blockid:question:market:0b506ec9a327339a", "blockid:question:market:61d61b023e6cda19"],
    supporting: ["cfo", "cdo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T3"], sources: ["financial_model", "public_url"], freshnessDays: 365 },
    redFlags: [{ key: "mpc.top_down_tam", rule: "Top-down \"1% of TAM\" sizing" }],
    signal: null,
  },
  {
    id: "MPC-05",
    title: { en: "Why now", vi: "Vì sao là lúc này" },
    question: { en: "Which named shift makes this possible or urgent now?", vi: "Thay đổi cụ thể nào khiến việc này khả thi hoặc cấp bách vào lúc này?" },
    questionRefs: ["blockid:question:market:b595fad4fbfe0839"],
    supporting: ["cdo"], stages: span("PS", "A"),
    evidence: { acceptedTiers: ["T3"], sources: ["public_url", "deck"], freshnessDays: 365 },
    redFlags: [{ key: "mpc.no_catalyst", rule: "No enabling catalyst named" }],
    signal: null,
  },
  {
    id: "MPC-06",
    title: { en: "Competition and wedge", vi: "Cạnh tranh và điểm đột phá" },
    question: { en: "Which rivals are named, and where does the company win against them?", vi: "Đối thủ nào được nêu tên, và công ty thắng họ ở điểm nào?" },
    questionRefs: ["blockid:question:market:d6eae1d178553aef", "blockid:question:idea:e12890bcd2a729a5", "blockid:question:idea:6a184fd6e5509608"],
    supporting: ["cpo", "cdo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T3"], sources: ["document", "public_url"], freshnessDays: 180 },
    redFlags: [{ key: "mpc.no_competitors", rule: "Claims \"no competitors\"" }],
    signal: "moat",
  },
  {
    id: "MPC-07",
    title: { en: "Repeatable go-to-market", vi: "Kênh tiếp cận thị trường lặp lại được" },
    question: { en: "Which channels acquire customers repeatably, at what payback and sales cycle?", vi: "Kênh nào thu hút khách hàng một cách lặp lại được, với thời gian hoàn vốn và chu kỳ bán hàng bao lâu?" },
    questionRefs: ["blockid:question:gtm_strategy:1dbb551dd4a50ae3", "blockid:question:gtm_strategy:6a1c3f59b63f5f02", "blockid:question:gtm_strategy:3d8820fc15e09ac4", "blockid:question:website:45a822d8b7528dfa"],
    supporting: ["cro", "cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["crm", "analytics"], freshnessDays: 90 },
    redFlags: [{ key: "mpc.founder_only_selling", rule: "Founder-only selling at Series A or later" }],
    signal: "traction",
  },
  {
    id: "MPC-08",
    title: { en: "Global ceiling beyond Australia", vi: "Trần tăng trưởng ngoài Úc" },
    question: { en: "What share of revenue or pipeline comes from outside Australia?", vi: "Bao nhiêu phần doanh thu hoặc cơ hội bán hàng đến từ ngoài nước Úc?" },
    supporting: ["cro", "cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["stripe", "xero"], freshnessDays: 180 },
    redFlags: [{ key: "mpc.au_only_tam", rule: "Addressable market is Australia-only" }],
    signal: null,
  },
  {
    id: "MPC-09",
    title: { en: "Customer concentration", vi: "Mức tập trung khách hàng" },
    question: { en: "How much revenue depends on the largest customer?", vi: "Bao nhiêu doanh thu phụ thuộc vào khách hàng lớn nhất?" },
    supporting: ["cro", "cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["xero", "stripe"], freshnessDays: 90 },
    redFlags: [{ key: "mpc.single_customer_over_30pct", rule: "One customer above 30% of revenue" }],
    signal: "traction",
  },
]);
