// PTD — Product-Tech Depth (lead CTO; CPO supports PTD-08, D24-c). Annex §3 PTD-01…08.

import { defineItems, span } from "../define";

export const PTD_ITEMS = defineItems("PTD", [
  {
    id: "PTD-01",
    title: { en: "Live product in use", vi: "Sản phẩm đang hoạt động và có người dùng" },
    question: { en: "Is the product live, and how many people actively use it?", vi: "Sản phẩm đã hoạt động thật chưa, và có bao nhiêu người đang dùng thường xuyên?" },
    questionRefs: ["blockid:question:website:285c049d72d782d5", "blockid:question:website:48ff7ec50dd91ec2", "blockid:question:website:4efdafd9b3689b60"],
    supporting: ["cpo", "cdo"], stages: span("PS", "S"),
    evidence: { acceptedTiers: ["T1"], sources: ["analytics", "public_url"], freshnessDays: 90 },
    redFlags: [{ key: "ptd.demo_only_at_seed", rule: "Demo-only product at seed" }],
    signal: "traction",
  },
  {
    id: "PTD-02",
    title: { en: "Cohort retention flattens", vi: "Tỷ lệ giữ chân theo nhóm đi ngang" },
    question: { en: "Do user cohorts plateau rather than decay to zero?", vi: "Các nhóm người dùng có giữ ổn định thay vì giảm dần về không?" },
    supporting: ["cdo", "cpo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["analytics"], freshnessDays: 90 },
    benchmarkRef: "a16z 16 startup metrics",
    redFlags: [{ key: "ptd.cohorts_decay_to_zero", rule: "Cohort retention decays to zero" }],
    signal: "traction",
  },
  {
    id: "PTD-03",
    title: { en: "Code owned in-house", vi: "Mã nguồn do công ty nắm giữ" },
    question: { en: "Does the company control its repository, and who commits to it?", vi: "Công ty có kiểm soát kho mã nguồn không, và ai đang đóng góp mã?" },
    questionRefs: ["blockid:question:code_git:3c4c4f2386f7a250", "blockid:question:code_git:e761a57a9ddf8ce5"],
    supporting: ["ciso"], stages: span("PS", "S"),
    evidence: { acceptedTiers: ["T1"], sources: ["git"], freshnessDays: 90 },
    redFlags: [{ key: "ptd.agency_holds_repo", rule: "An agency holds the repository" }],
    signal: "ip",
  },
  {
    id: "PTD-04",
    title: { en: "Reliability and scalability", vi: "Độ tin cậy và khả năng mở rộng" },
    question: { en: "What uptime, incident rate and testing practice support scale?", vi: "Thời gian hoạt động, tần suất sự cố và kiểm thử nào chứng minh hệ thống mở rộng được?" },
    questionRefs: ["blockid:question:code_git:4878e79113de624a", "blockid:question:code_git:d912f0f6b15de7d9"],
    supporting: ["ciso", "cdo"], stages: span("A"),
    evidence: { acceptedTiers: ["T1", "T2"], sources: ["public_url", "git", "document"], freshnessDays: 90 },
    redFlags: [{ key: "ptd.single_point_of_failure", rule: "Single point of failure in production" }],
    signal: null,
  },
  {
    id: "PTD-05",
    title: { en: "Security and privacy engineering", vi: "Kỹ thuật bảo mật và quyền riêng tư" },
    question: { en: "Which certifications, Essential Eight controls or penetration tests cover customer data?", vi: "Chứng nhận, biện pháp Essential Eight hay kiểm thử xâm nhập nào bảo vệ dữ liệu khách hàng?" },
    supporting: ["ciso"], stages: span("S"),
    evidence: { acceptedTiers: ["T2"], sources: ["document"], freshnessDays: 365 },
    redFlags: [{ key: "ptd.customer_data_no_pentest", rule: "Holds customer data with no penetration test" }],
    signal: null,
  },
  {
    id: "PTD-06",
    title: { en: "AI compute economics", vi: "Hiệu quả chi phí tính toán AI" },
    question: { en: "What is gross margin after inference and model costs, and is there a path to improve it?", vi: "Biên lợi nhuận gộp sau chi phí suy luận và model là bao nhiêu, và có lộ trình cải thiện không?" },
    supporting: ["cdo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["cloud_billing"], freshnessDays: 90 },
    benchmarkRef: "BVP State of AI 2025",
    redFlags: [{ key: "ptd.thin_wrapper_low_gm", rule: "Thin wrapper near 25% gross margin with no path up" }],
    signal: null,
  },
  {
    id: "PTD-07",
    title: { en: "Proprietary data or technology", vi: "Dữ liệu hoặc công nghệ độc quyền" },
    question: { en: "Which data assets or technology are proprietary and hard to copy?", vi: "Tài sản dữ liệu hoặc công nghệ nào là độc quyền và khó sao chép?" },
    supporting: ["cdo"], stages: span("A"),
    evidence: { acceptedTiers: ["T3"], sources: ["document"], freshnessDays: 365 },
    redFlags: [{ key: "ptd.commodity_stack", rule: "Commodity stack with no proprietary asset" }],
    signal: "moat",
  },
  {
    id: "PTD-08",
    title: { en: "Roadmap to \"Act II\"", vi: "Lộ trình sang sản phẩm thứ hai" },
    question: { en: "How are features prioritised toward expansion products beyond the first one?", vi: "Tính năng được ưu tiên thế nào để mở rộng sang sản phẩm tiếp theo ngoài sản phẩm đầu tiên?" },
    questionRefs: ["blockid:question:roadmap:a0fa8d89d844ab6a"],
    supporting: ["cpo"], stages: span("S"),
    evidence: { acceptedTiers: ["T3"], sources: ["document"], freshnessDays: 180 },
    redFlags: [{ key: "ptd.feature_list_only", rule: "Roadmap is a feature list only" }],
    signal: "moat",
  },
]);
