// SVM — Strategic Vision & Moat (lead CEO; CPO supports SVM-06, D24-c).
// Annex §3 SVM-01…08. Absorbs G31 overlay MT.

import { ALL_STAGES, defineItems, span } from "../define";

export const SVM_ITEMS = defineItems("SVM", [
  {
    id: "SVM-01",
    title: { en: "Named moat type", vi: "Loại lợi thế phòng thủ cụ thể" },
    question: { en: "Which specific moat applies (network effects, data, switching costs) and what usage data supports it?", vi: "Lợi thế phòng thủ cụ thể nào áp dụng (hiệu ứng mạng, dữ liệu, chi phí chuyển đổi) và dữ liệu sử dụng nào chứng minh?" },
    supporting: ["cpo", "cmo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["analytics"], freshnessDays: 180 },
    benchmarkRef: "NFX network effects",
    redFlags: [{ key: "svm.execution_only_moat", rule: "Moat named only as \"execution\"" }],
    signal: "moat",
  },
  {
    id: "SVM-02",
    title: { en: "Non-consensus insight", vi: "Góc nhìn khác biệt với số đông" },
    question: { en: "What does the company believe that most others do not, and why is it right?", vi: "Công ty tin vào điều gì mà phần lớn người khác không tin, và vì sao điều đó đúng?" },
    supporting: ["cmo"], stages: span("PS", "S"),
    evidence: { acceptedTiers: ["T3"], sources: ["document", "deck"], freshnessDays: 365 },
    redFlags: [{ key: "svm.me_too", rule: "Me-too play on a trend" }],
    signal: "moat",
  },
  {
    id: "SVM-03",
    title: { en: "Global ambition", vi: "Tham vọng toàn cầu" },
    question: { en: "Does the 12-month vision aim at a world-best outcome rather than a lifestyle ceiling?", vi: "Tầm nhìn 12 tháng có hướng tới kết quả hàng đầu thế giới thay vì một mức trần nhỏ không?" },
    questionRefs: ["blockid:question:roadmap:ccb348b8ee88d1ad"],
    supporting: ["cpo"], stages: span("PS", "A"),
    evidence: { acceptedTiers: ["T3"], sources: ["document"], freshnessDays: 365 },
    redFlags: [{ key: "svm.lifestyle_ceiling", rule: "Plan implies a lifestyle ceiling" }],
    signal: null,
  },
  {
    id: "SVM-04",
    title: { en: "Path to scale", vi: "Lộ trình mở rộng quy mô" },
    question: { en: "Does the growth trajectory to date support the plan to scale?", vi: "Quỹ đạo tăng trưởng đến nay có hỗ trợ kế hoạch mở rộng quy mô không?" },
    supporting: ["cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1", "T3"], sources: ["financial_model", "stripe", "xero"], freshnessDays: 180 },
    benchmarkRef: "BVP Cloud 100 Benchmarks",
    redFlags: [{ key: "svm.hockey_stick", rule: "Hockey-stick plan unsupported by history" }],
    signal: "traction",
  },
  {
    id: "SVM-05",
    title: { en: "Scalable economics", vi: "Kinh tế mở rộng được" },
    question: { en: "Do revenue per FTE and gross margin improve as the company grows?", vi: "Doanh thu trên mỗi nhân sự và biên lợi nhuận gộp có cải thiện khi công ty lớn lên không?" },
    supporting: ["cfo"], stages: span("A"),
    evidence: { acceptedTiers: ["T1"], sources: ["payroll", "stripe", "xero"], freshnessDays: 180 },
    redFlags: [{ key: "svm.linear_services_economics", rule: "Linear, services-like economics" }],
    signal: null,
  },
  {
    id: "SVM-06",
    title: { en: "Capital path to milestones", vi: "Lộ trình vốn gắn với các mốc" },
    question: { en: "Which milestones will each round fund, and what dependencies or blockers stand in the way?", vi: "Mỗi vòng vốn sẽ tài trợ cho những mốc nào, và phụ thuộc hay trở ngại nào đang cản đường?" },
    questionRefs: ["blockid:question:roadmap:86a493aa575cb75b", "blockid:question:roadmap:af97926d94d1d6ef"],
    supporting: ["cpo", "cfo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T3"], sources: ["document", "financial_model"], freshnessDays: 180 },
    benchmarkRef: "Startup Genome premature scaling",
    redFlags: [{ key: "svm.premature_scaling", rule: "Premature scaling ahead of milestones" }],
    signal: null,
  },
  {
    id: "SVM-07",
    title: { en: "Exit path", vi: "Lộ trình thoái vốn" },
    question: { en: "Which acquirers are named, and what comparable multiples apply?", vi: "Những bên mua lại nào được nêu tên, và bội số so sánh nào áp dụng?" },
    supporting: ["cfo", "cmo"], stages: span("A"),
    evidence: { acceptedTiers: ["T3"], sources: ["document", "public_url"], freshnessDays: 365 },
    redFlags: [{ key: "svm.no_logical_buyer", rule: "No logical buyer" }],
    signal: "liquidity",
  },
  {
    id: "SVM-08",
    title: { en: "Durability against AI substitution", vi: "Khả năng trụ vững trước sự thay thế của AI" },
    question: { en: "Do customers stay even as AI substitutes appear?", vi: "Khách hàng có ở lại ngay cả khi xuất hiện giải pháp AI thay thế không?" },
    supporting: ["cpo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["analytics"], freshnessDays: 180 },
    redFlags: [{ key: "svm.foundation_model_replicable", rule: "Replicable by a foundation model" }],
    signal: "moat",
  },
]);
