// TRE — Traction Revenue Evidence (lead CRO; CFO sits on the judge panel for
// revenue-mapped items, D24-c). Annex §3 TRE-01…13. Absorbs G31 overlay TR.

import { ALL_STAGES, defineItems, span } from "../define";

export const TRE_ITEMS = defineItems("TRE", [
  {
    id: "TRE-01",
    title: { en: "Verified revenue", vi: "Doanh thu được xác minh" },
    question: { en: "What MRR or ARR is confirmed by a billing or accounting system of record?", vi: "MRR hoặc ARR nào được xác nhận bởi hệ thống thanh toán hoặc kế toán gốc?" },
    questionRefs: ["blockid:question:revenue:e95923a31d3bcb97"],
    supporting: ["cfo", "cdo"], requiredJudgeAgents: ["cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["stripe", "xero", "bank"], freshnessDays: 60 },
    redFlags: [{ key: "tre.spreadsheet_only_revenue", rule: "Revenue shown only in a spreadsheet" }],
    signal: "traction", metricsKey: "arr",
  },
  {
    id: "TRE-02",
    title: { en: "Pre-revenue proxies", vi: "Chỉ báo thay thế khi chưa có doanh thu" },
    question: { en: "Which LOIs, paid pilots, active users or waitlist conversions show demand before revenue?", vi: "Thư ý định, thí điểm có trả phí, người dùng hoạt động hay tỷ lệ chuyển đổi danh sách chờ nào cho thấy nhu cầu trước khi có doanh thu?" },
    questionRefs: ["blockid:question:customer_size:34a4e1d98758e703", "blockid:question:customer_size:8683d3f20181479e"],
    supporting: ["cmo", "cdo"], stages: span("PS", "PS"),
    evidence: { acceptedTiers: ["T1", "T2"], sources: ["contract", "analytics"], freshnessDays: 90 },
    benchmarkRef: "Startmate accelerator cohort data",
    redFlags: [{ key: "tre.lois_booked_as_revenue", rule: "LOIs booked as revenue" }],
    signal: "traction",
    rule: "At pre-seed TRE-02 stands in for NRR (TRE-04) and gross margin (TRE-06).",
  },
  {
    id: "TRE-03",
    title: { en: "Growth rate versus stage", vi: "Tốc độ tăng trưởng so với giai đoạn" },
    question: { en: "How fast is revenue or usage growing compared with current stage medians?", vi: "Doanh thu hoặc mức sử dụng tăng nhanh thế nào so với trung vị của giai đoạn hiện tại?" },
    questionRefs: ["blockid:question:revenue:dd9adda5c203301e", "blockid:question:customer_size:1b6450bbee7361a3"],
    supporting: ["cfo", "cdo"], requiredJudgeAgents: ["cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["stripe", "xero", "analytics"], freshnessDays: 60 },
    benchmarkRef: "High Alpha SaaS Benchmarks 2025",
    redFlags: [{ key: "tre.decelerating_below_median", rule: "Growth decelerating below the stage median" }],
    signal: "traction", metricsKey: "growth",
  },
  {
    id: "TRE-04",
    title: { en: "Net revenue retention", vi: "Tỷ lệ giữ chân doanh thu ròng (NRR)" },
    question: { en: "What is net revenue retention across billing cohorts?", vi: "Tỷ lệ giữ chân doanh thu ròng theo các nhóm thanh toán là bao nhiêu?" },
    supporting: ["cfo", "cdo"], stages: span("A"),
    evidence: { acceptedTiers: ["T1"], sources: ["stripe", "xero"], freshnessDays: 90 },
    benchmarkRef: "SaaS Capital retention 2025",
    redFlags: [{ key: "tre.nrr_below_100", rule: "NRR below 100%" }],
    signal: "traction", metricsKey: "nrr",
  },
  {
    id: "TRE-05",
    title: { en: "Gross revenue retention", vi: "Tỷ lệ giữ chân doanh thu gộp (GRR)" },
    question: { en: "What share of starting revenue is kept before expansion?", vi: "Giữ lại được bao nhiêu phần doanh thu ban đầu trước khi tính phần mở rộng?" },
    supporting: ["cfo", "cdo"], stages: span("A"),
    evidence: { acceptedTiers: ["T1"], sources: ["stripe", "xero"], freshnessDays: 90 },
    benchmarkRef: "SaaS Capital retention 2025",
    redFlags: [{ key: "tre.grr_below_80", rule: "GRR below 80%" }],
    signal: "traction", metricsKey: "grr",
  },
  {
    id: "TRE-06",
    title: { en: "Gross margin", vi: "Biên lợi nhuận gộp" },
    question: { en: "What are gross margin and unit economics once services and delivery costs are included?", vi: "Biên lợi nhuận gộp và kinh tế đơn vị là bao nhiêu khi đã tính chi phí dịch vụ và vận hành?" },
    questionRefs: ["blockid:question:revenue:0ad91b47eaa98a71"],
    supporting: ["cfo"], requiredJudgeAgents: ["cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1", "T2"], sources: ["xero", "document"], freshnessDays: 90 },
    benchmarkRef: "BVP Scaling to $100M",
    redFlags: [{ key: "tre.services_counted_as_saas", rule: "Services revenue counted as SaaS" }],
    signal: "traction", metricsKey: "gross_margin",
  },
  {
    id: "TRE-07",
    title: { en: "CAC payback", vi: "Thời gian hoàn vốn chi phí thu hút khách hàng" },
    question: { en: "How many months of gross profit repay the cost of acquiring a customer?", vi: "Cần bao nhiêu tháng lợi nhuận gộp để bù lại chi phí thu hút một khách hàng?" },
    supporting: ["cfo", "cmo"], stages: span("A"),
    evidence: { acceptedTiers: ["T1", "T2"], sources: ["crm", "xero"], freshnessDays: 90 },
    benchmarkRef: "High Alpha SaaS Benchmarks 2025",
    redFlags: [{ key: "tre.cac_payback_over_24m", rule: "CAC payback above 24 months" }],
    signal: "traction",
  },
  {
    id: "TRE-08",
    title: { en: "LTV to CAC", vi: "Tỷ lệ LTV trên CAC" },
    question: { en: "Is lifetime value comfortably above acquisition cost, using observed churn?", vi: "Giá trị vòng đời khách hàng có cao hơn rõ rệt chi phí thu hút, dựa trên tỷ lệ rời bỏ thực tế không?" },
    supporting: ["cfo", "cmo"], stages: span("A"),
    evidence: { acceptedTiers: ["T1"], sources: ["stripe", "crm"], freshnessDays: 90 },
    redFlags: [{ key: "tre.assumed_churn", rule: "LTV uses assumed rather than observed churn" }],
    signal: "traction",
  },
  {
    id: "TRE-09",
    title: { en: "Burn multiple", vi: "Hệ số đốt tiền (burn multiple)" },
    question: { en: "How much net burn does each dollar of net new ARR cost?", vi: "Mỗi đô la ARR tăng thêm tốn bao nhiêu tiền đốt ròng?" },
    supporting: ["cfo"], stages: span("S"),
    evidence: { acceptedTiers: ["T1"], sources: ["bank", "stripe", "xero"], freshnessDays: 90 },
    redFlags: [{ key: "tre.burn_multiple_over_3", rule: "Burn multiple above 3" }],
    signal: "traction", metricsKey: "burn_multiple",
  },
  {
    id: "TRE-10",
    title: { en: "Magic number", vi: "Chỉ số hiệu quả bán hàng (magic number)" },
    question: { en: "How much new recurring revenue does each dollar of sales and marketing produce?", vi: "Mỗi đô la chi cho bán hàng và marketing tạo ra bao nhiêu doanh thu định kỳ mới?" },
    supporting: ["cfo", "cmo"], stages: span("A"),
    evidence: { acceptedTiers: ["T1"], sources: ["xero", "stripe"], freshnessDays: 90 },
    benchmarkRef: "Scale Venture Partners magic number",
    redFlags: [{ key: "tre.magic_number_below_0_5", rule: "Magic number below 0.5" }],
    signal: "traction",
  },
  {
    id: "TRE-11",
    title: { en: "Rule of 40", vi: "Quy tắc 40" },
    question: { en: "Do growth rate and profit margin together reach 40 or more?", vi: "Tốc độ tăng trưởng cộng biên lợi nhuận có đạt từ 40 trở lên không?" },
    supporting: ["cfo"], stages: span("B+"),
    evidence: { acceptedTiers: ["T2"], sources: ["document"], freshnessDays: 180 },
    redFlags: [{ key: "tre.rule_of_40_far_below", rule: "Far below 40 with no plan" }],
    signal: "traction",
  },
  {
    id: "TRE-12",
    title: { en: "Revenue quality", vi: "Chất lượng doanh thu" },
    question: { en: "How much revenue is recurring, retained and free of related-party or one-off deals, and is there a path to profitability?", vi: "Bao nhiêu doanh thu là định kỳ, được giữ chân và không đến từ bên liên quan hay giao dịch một lần, và có lộ trình có lãi không?" },
    questionRefs: ["blockid:question:customer_size:0772ed94647c795a", "blockid:question:revenue:e26ca87f3feff2a3"],
    supporting: ["cfo", "cdo"], requiredJudgeAgents: ["cfo"], stages: ALL_STAGES,
    evidence: { acceptedTiers: ["T1"], sources: ["xero", "stripe"], freshnessDays: 90 },
    redFlags: [{ key: "tre.related_party_or_one_off", rule: "Material related-party or one-off revenue" }],
    signal: "traction",
  },
  {
    id: "TRE-13",
    title: { en: "Contracted backlog", vi: "Hợp đồng đã ký chưa triển khai" },
    question: { en: "What revenue is signed but not yet live?", vi: "Có bao nhiêu doanh thu đã ký hợp đồng nhưng chưa triển khai?" },
    supporting: ["cfo"], stages: span("A"),
    evidence: { acceptedTiers: ["T2"], sources: ["contract"], freshnessDays: 180 },
    redFlags: [{ key: "tre.verbal_pipeline", rule: "Backlog is verbal pipeline only" }],
    signal: "traction",
  },
]);
