// Product Tour v2 — <TourMedia />
//
// Renders the visual asset for a feature-tour header or step. We keep this a
// pure server component so both the /guides/features pages (server-rendered)
// and the FeatureSpotlight overlay (client-rendered) can use the exact same
// component with no bundle-size cost. There is no external asset pipeline —
// every "media" is either an inline SVG (icon) or a labeled placeholder tile,
// so tours stay renderable in tests, PDFs and offline docs.

import * as React from "react";
import {
  Compass,
  Flag,
  Folder,
  Gauge,
  Rocket,
  Users,
  type LucideIcon,
} from "lucide-react";

import type { FeatureTourIcon } from "@/lib/product-tour/feature-tours";

const ICON_MAP: Record<FeatureTourIcon, LucideIcon> = {
  rocket: Rocket,
  gauge: Gauge,
  folder: Folder,
  users: Users,
  compass: Compass,
  flag: Flag,
};

/** Header icon rendered next to the tour name. Uses lucide-react. */
export function TourIcon({
  icon,
  className,
}: {
  icon: FeatureTourIcon;
  className?: string;
}): React.ReactElement {
  const Cmp = ICON_MAP[icon] ?? Rocket;
  return (
    <Cmp
      strokeWidth={1.75}
      className={className ?? "h-5 w-5"}
      aria-hidden
    />
  );
}

/**
 * Placeholder "screenshot tile" for a step. We deliberately do NOT reach for a
 * real screenshot here because those live under /public/tour/* and are
 * regenerated by the screenshot-tour skill — until that pipeline emits a file
 * for a given key, this component renders an accessible, on-brand labeled tile
 * so the tour still looks intentional.
 */
export function TourMedia({
  media,
  label,
}: {
  /** Media key from a FeatureTourStep — free-form so tours can extend. */
  media?: string;
  /** Screen-reader label; defaults to the media key or "Illustration". */
  label?: string;
}): React.ReactElement | null {
  if (!media) return null;
  const alt = label ?? media;
  return (
    <div
      role="img"
      aria-label={alt}
      data-testid="tour-media"
      data-media={media}
      className="relative w-full aspect-[16/9] rounded-xl overflow-hidden border border-surface-200 bg-gradient-to-br from-brand-50 via-white to-gold-50 dark:from-brand-900/40 dark:via-surface-900 dark:to-gold-900/30"
    >
      <svg
        viewBox="0 0 320 180"
        preserveAspectRatio="xMidYMid slice"
        className="absolute inset-0 h-full w-full opacity-70"
        aria-hidden
      >
        <defs>
          <pattern
            id={"tour-grid-" + media}
            x="0"
            y="0"
            width="20"
            height="20"
            patternUnits="userSpaceOnUse"
          >
            <path
              d="M20 0H0V20"
              fill="none"
              stroke="currentColor"
              strokeOpacity="0.08"
              strokeWidth="1"
            />
          </pattern>
        </defs>
        <rect
          width="320"
          height="180"
          fill={"url(#tour-grid-" + media + ")"}
          className="text-brand-700"
        />
      </svg>
      <div className="absolute inset-0 flex items-center justify-center">
        <span className="rounded-full px-3 py-1 text-[11px] font-medium uppercase tracking-wider bg-white/80 dark:bg-surface-900/70 text-ink-700 dark:text-ink-100 backdrop-blur-sm border border-surface-200/70">
          {alt}
        </span>
      </div>
    </div>
  );
}
