// /showcase/blockid/report — the pure view (G19-S46).
//
// Server-renderable, no hooks: the page loads BlockID's own ReportV2
// (lib/showcase/blockid-report.ts) and hands it here; the colocated test
// renders both branches with renderToStaticMarkup. The report itself is the
// same <TbrReportV2> every founder gets — nothing on this page is a fixture,
// and nothing is locked (standard tier, no unlock rail, no clarity survey).

import Link from "next/link";
import { MarketingHero } from "@/components/marketing/marketing-hero";
import { MarketingSection } from "@/components/marketing/marketing-section";
import { NotFinancialAdvice } from "@/components/legal/not-financial-advice";
import { TbrReportV2 } from "@/components/tbr/v2/report";
import type { TbrAssessmentBenchmarks } from "@/components/tbr/v2/assessment";
import { DATA_PRINCIPLE_SENTENCE } from "@/lib/report-v2/schema";
import type { BlockidShowcaseReport } from "@/lib/showcase/blockid-report";

export const SHOWCASE_REPORT_BANNER = "This is BlockID's own Trusted Business Report — generated by the same pipeline every founder gets; numbers are live, evidence is ours.";
export const SHOWCASE_REPORT_EMPTY_TITLE = "Our own report is not published yet";
export const SHOWCASE_REPORT_TESTID = "showcase-blockid-report";
export const SHOWCASE_REPORT_EMPTY_TESTID = "showcase-blockid-report-empty";

function formatRunDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-AU", { day: "2-digit", month: "short", year: "numeric", timeZone: "Australia/Sydney" });
}

export function ShowcaseBlockidReportView({ loaded, benchmarks }: { loaded: BlockidShowcaseReport | null; benchmarks?: TbrAssessmentBenchmarks }) {
  return (
    <>
      <MarketingHero
        eyebrow="Showcase · BlockID scoring BlockID"
        title="Our own Trusted Business Report"
        subtitle={SHOWCASE_REPORT_BANNER}
        primaryCta={{ href: "/methodology", label: "How the score is built" }}
        secondaryCta={{ href: "/showcase/blockid", label: "Back to the showcase" }}
      />

      <MarketingSection kicker="Same pipeline, our data" title="What you are reading">
        <div className="rounded-2xl border border-line-subtle bg-surface p-5 text-sm text-secondary" data-testid="showcase-blockid-report-banner">
          <p>
            Every chapter below was written by the pipeline that produces a founder&apos;s standard-tier report: the deterministic score ledger, the
            valuation inputs table, the evidence register and the auditor log are all ours, unedited. Dimensions we have not evidenced yet render as
            pending — exactly as they would for any founder.
          </p>
          <p className="mt-3 text-xs text-tertiary">{DATA_PRINCIPLE_SENTENCE}</p>
          <p className="mt-3 text-xs text-tertiary">
            Read the{" "}
            <Link className="text-action underline" href="/methodology">
              methodology
            </Link>{" "}
            or compare with the{" "}
            <Link className="text-action underline" href="/tbr/demo">
              illustrative demo report
            </Link>
            {loaded ? (
              <>
                {" "}
                · generated {formatRunDate(loaded.generatedAt)} · snapshot <span className="font-mono">{loaded.snapshotId.slice(0, 8)}</span>
              </>
            ) : null}
            .
          </p>
        </div>
      </MarketingSection>

      {loaded ? (
        <MarketingSection kicker="Trusted Business Report" title={loaded.report.cover.startupName}>
          <div className="rounded-2xl border border-line-subtle bg-surface p-4 text-primary md:p-8" data-testid={SHOWCASE_REPORT_TESTID} data-snapshot-id={loaded.snapshotId}>
            <TbrReportV2 report={loaded.report} locale="en" benchmarks={benchmarks} />
          </div>
        </MarketingSection>
      ) : (
        <MarketingSection kicker="Trusted Business Report" title={SHOWCASE_REPORT_EMPTY_TITLE}>
          <div className="rounded-2xl border border-dashed border-line-subtle bg-surface p-6 text-sm text-secondary" data-testid={SHOWCASE_REPORT_EMPTY_TESTID}>
            <p>
              The weekly self-report has not been persisted for this build yet. The pipeline runs on our own project every Monday; until then the{" "}
              <Link className="text-action underline" href="/tbr/demo">
                demo report
              </Link>{" "}
              shows the exact chapter structure with illustrative numbers.
            </p>
          </div>
        </MarketingSection>
      )}

      <MarketingSection>
        <NotFinancialAdvice kind="not_financial_advice" />
      </MarketingSection>
    </>
  );
}
