// AUTO-GENERATED by scripts/build-plans.ts — DO NOT EDIT BY HAND.
// Source: web/src/config/pricing/plans.csv
// Regenerate: npx tsx scripts/build-plans.ts

export interface GeneratedPlan {
  id: string;
  segment: "founder" | "investor_angel" | "advisor" | "investor_vc" | "accelerator";
  name: string;
  price_aud_cents: number;
  annual_price_aud_cents: number;
  interval: "free" | "monthly" | "yearly" | "once" | "custom";
  trial_days: number;
  stripe_env_var: string;
  feature_flags: string[];
  usage_limits: Record<string, number>;
  active: boolean;
  sort_order: number;
}

export const GENERATED_PLANS: readonly GeneratedPlan[] = [
  {
    "id": "founder_free",
    "segment": "founder",
    "name": "Free (anonymous)",
    "price_aud_cents": 0,
    "annual_price_aud_cents": 0,
    "interval": "free",
    "trial_days": 0,
    "stripe_env_var": "",
    "feature_flags": [
      "svi.public"
    ],
    "usage_limits": {
      "profiles": 0,
      "svi_per_month": 1
    },
    "active": true,
    "sort_order": 10
  },
  {
    "id": "founder_starter",
    "segment": "founder",
    "name": "Starter",
    "price_aud_cents": 2900,
    "annual_price_aud_cents": 29000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_STARTER",
    "feature_flags": [
      "profile.multi",
      "svi.premium"
    ],
    "usage_limits": {
      "profiles": 1,
      "svi_per_month": 10,
      "monthly_credits": 50
    },
    "active": true,
    "sort_order": 20
  },
  {
    "id": "founder_growth",
    "segment": "founder",
    "name": "Growth",
    "price_aud_cents": 9900,
    "annual_price_aud_cents": 99000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_GROWTH",
    "feature_flags": [
      "profile.multi",
      "cap_table.write",
      "data_room.access",
      "investor_links.premium",
      "term_sheet_ai"
    ],
    "usage_limits": {
      "profiles": 3,
      "svi_per_month": 50,
      "monthly_credits": 200
    },
    "active": true,
    "sort_order": 30
  },
  {
    "id": "founder_scale",
    "segment": "founder",
    "name": "Scale",
    "price_aud_cents": 29900,
    "annual_price_aud_cents": 299000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_SCALE",
    "feature_flags": [
      "profile.multi",
      "cap_table.write",
      "data_room.access",
      "investor_links.premium",
      "term_sheet_ai",
      "esop.manage",
      "blockchain.sync",
      "advisor_portal",
      "white_label"
    ],
    "usage_limits": {
      "profiles": 10,
      "svi_per_month": -1,
      "monthly_credits": 1000
    },
    "active": true,
    "sort_order": 40
  },
  {
    "id": "founder_enterprise",
    "segment": "founder",
    "name": "Enterprise",
    "price_aud_cents": 150000,
    "annual_price_aud_cents": 1800000,
    "interval": "custom",
    "trial_days": 0,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_ENTERPRISE",
    "feature_flags": [
      "profile.multi",
      "cap_table.write",
      "data_room.access",
      "investor_links.premium",
      "term_sheet_ai",
      "esop.manage",
      "blockchain.sync",
      "advisor_portal",
      "white_label",
      "api.access",
      "sso"
    ],
    "usage_limits": {
      "profiles": -1,
      "svi_per_month": -1,
      "monthly_credits": -1
    },
    "active": true,
    "sort_order": 50
  },
  {
    "id": "investor_angel",
    "segment": "investor_angel",
    "name": "Angel",
    "price_aud_cents": 7900,
    "annual_price_aud_cents": 79000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_ANGEL",
    "feature_flags": [
      "investor.dealflow",
      "investor.watchlist"
    ],
    "usage_limits": {
      "watchlist_size": 25,
      "diligence_packs_per_month": 5
    },
    "active": true,
    "sort_order": 60
  },
  {
    "id": "investor_advisor",
    "segment": "advisor",
    "name": "Advisor",
    "price_aud_cents": 14900,
    "annual_price_aud_cents": 149000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_ADVISOR",
    "feature_flags": [
      "investor.dealflow",
      "advisor.clients",
      "white_label"
    ],
    "usage_limits": {
      "clients": 25
    },
    "active": true,
    "sort_order": 70
  },
  {
    "id": "investor_vc_small",
    "segment": "investor_vc",
    "name": "VC Small (5-seat min)",
    "price_aud_cents": 34900,
    "annual_price_aud_cents": 349000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_VC_SMALL",
    "feature_flags": [
      "investor.dealflow",
      "investor.portfolio",
      "investor.lp_export"
    ],
    "usage_limits": {
      "seats": 5,
      "portfolio_size": 50
    },
    "active": true,
    "sort_order": 80
  },
  {
    "id": "investor_vc_ent",
    "segment": "investor_vc",
    "name": "VC Enterprise",
    "price_aud_cents": 250000,
    "annual_price_aud_cents": 3000000,
    "interval": "custom",
    "trial_days": 0,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_VC_ENT",
    "feature_flags": [
      "investor.dealflow",
      "investor.portfolio",
      "investor.lp_export",
      "api.access",
      "custom_benchmarks"
    ],
    "usage_limits": {
      "seats": -1
    },
    "active": true,
    "sort_order": 90
  },
  {
    "id": "accelerator_starter",
    "segment": "accelerator",
    "name": "Cohort Starter",
    "price_aud_cents": 50000,
    "annual_price_aud_cents": 500000,
    "interval": "monthly",
    "trial_days": 14,
    "stripe_env_var": "STRIPE_PRICE_ACCEL_STARTER",
    "feature_flags": [
      "cohort_dashboard",
      "cohort_reports",
      "program_curriculum_hub"
    ],
    "usage_limits": {
      "seats": 15,
      "monthly_credits": 2000
    },
    "active": true,
    "sort_order": 100
  },
  {
    "id": "accelerator_growth",
    "segment": "accelerator",
    "name": "Cohort Growth",
    "price_aud_cents": 150000,
    "annual_price_aud_cents": 1500000,
    "interval": "monthly",
    "trial_days": 14,
    "stripe_env_var": "STRIPE_PRICE_ACCEL_GROWTH",
    "feature_flags": [
      "cohort_dashboard",
      "cohort_reports",
      "program_curriculum_hub",
      "co_mentor_pool",
      "cohort_batch_reports",
      "alumni_network_tools"
    ],
    "usage_limits": {
      "seats": 50,
      "monthly_credits": 8000
    },
    "active": true,
    "sort_order": 110
  },
  {
    "id": "accelerator_enterprise",
    "segment": "accelerator",
    "name": "Cohort Enterprise",
    "price_aud_cents": 350000,
    "annual_price_aud_cents": 3500000,
    "interval": "monthly",
    "trial_days": 14,
    "stripe_env_var": "STRIPE_PRICE_ACCEL_ENTERPRISE",
    "feature_flags": [
      "cohort_dashboard",
      "cohort_reports",
      "program_curriculum_hub",
      "co_mentor_pool",
      "cohort_batch_reports",
      "alumni_network_tools",
      "multi_cohort_management",
      "white_label_reports",
      "dedicated_success_manager",
      "sso"
    ],
    "usage_limits": {
      "seats": -1,
      "monthly_credits": -1
    },
    "active": true,
    "sort_order": 120
  }
] as const;

export const GENERATED_PLANS_BY_ID: Readonly<Record<string, GeneratedPlan>> =
  Object.fromEntries(GENERATED_PLANS.map(p => [p.id, p]));
