// AUTO-GENERATED by scripts/build-plans.ts — DO NOT EDIT BY HAND.
// Source: web/src/config/pricing/plans.csv
// Regenerate: npx tsx scripts/build-plans.ts

export interface GeneratedPlan {
  id: string;
  segment: "founder" | "investor_angel" | "advisor" | "investor_vc" | "accelerator";
  name: string;
  price_aud_cents: number;
  annual_price_aud_cents: number;
  interval: "free" | "monthly" | "yearly" | "once" | "custom";
  trial_days: number;
  stripe_env_var: string;
  feature_flags: string[];
  usage_limits: Record<string, number>;
  active: boolean;
  sort_order: number;
}

export const GENERATED_PLANS: readonly GeneratedPlan[] = [
  {
    "id": "founder_free",
    "segment": "founder",
    "name": "Free (anonymous)",
    "price_aud_cents": 0,
    "annual_price_aud_cents": 0,
    "interval": "free",
    "trial_days": 0,
    "stripe_env_var": "",
    "feature_flags": [
      "svi.public"
    ],
    "usage_limits": {
      "profiles": 0,
      "svi_per_month": 1
    },
    "active": true,
    "sort_order": 10
  },
  {
    "id": "founder_starter",
    "segment": "founder",
    "name": "Starter",
    "price_aud_cents": 2900,
    "annual_price_aud_cents": 29000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_STARTER",
    "feature_flags": [
      "profile.multi",
      "svi.premium",
      "data_room.access",
      "investor_links.premium",
      "grant_finder",
      "money_radar"
    ],
    "usage_limits": {
      "profiles": 1,
      "svi_per_month": 10,
      "monthly_credits": 20
    },
    "active": true,
    "sort_order": 20
  },
  {
    "id": "founder_growth",
    "segment": "founder",
    "name": "Growth",
    "price_aud_cents": 6900,
    "annual_price_aud_cents": 69000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_GROWTH",
    "feature_flags": [
      "profile.multi",
      "svi.premium",
      "cap_table.write",
      "data_room.access",
      "investor_links.premium",
      "term_sheet_ai",
      "share_management",
      "investor_pack",
      "per_investor_share_links",
      "grant_finder",
      "money_radar",
      "secondary_market.view"
    ],
    "usage_limits": {
      "profiles": 3,
      "svi_per_month": 50,
      "monthly_credits": 45
    },
    "active": true,
    "sort_order": 30
  },
  {
    "id": "founder_scale",
    "segment": "founder",
    "name": "Pro",
    "price_aud_cents": 29900,
    "annual_price_aud_cents": 299000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_SCALE",
    "feature_flags": [
      "profile.multi",
      "svi.premium",
      "cap_table.write",
      "data_room.access",
      "investor_links.premium",
      "term_sheet_ai",
      "share_management",
      "investor_pack",
      "per_investor_share_links",
      "esop.manage",
      "blockchain.sync",
      "advisor_portal",
      "white_label",
      "c_level_agents",
      "dcf_sensitivity",
      "dividend_engine",
      "white_label_pdf",
      "grant_finder",
      "money_radar",
      "secondary_market.view"
    ],
    "usage_limits": {
      "profiles": 10,
      "svi_per_month": -1,
      "monthly_credits": 200
    },
    "active": false,
    "sort_order": 40
  },
  {
    "id": "founder_enterprise",
    "segment": "founder",
    "name": "Enterprise",
    "price_aud_cents": 150000,
    "annual_price_aud_cents": 1800000,
    "interval": "custom",
    "trial_days": 0,
    "stripe_env_var": "STRIPE_PRICE_FOUNDER_ENTERPRISE",
    "feature_flags": [
      "profile.multi",
      "svi.premium",
      "cap_table.write",
      "data_room.access",
      "investor_links.premium",
      "term_sheet_ai",
      "share_management",
      "investor_pack",
      "per_investor_share_links",
      "esop.manage",
      "blockchain.sync",
      "advisor_portal",
      "white_label",
      "api.access",
      "sso",
      "grant_finder",
      "money_radar",
      "secondary_market.view"
    ],
    "usage_limits": {
      "profiles": -1,
      "svi_per_month": -1,
      "monthly_credits": -1
    },
    "active": true,
    "sort_order": 50
  },
  {
    "id": "investor_angel",
    "segment": "investor_angel",
    "name": "Scout",
    "price_aud_cents": 7900,
    "annual_price_aud_cents": 79000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_ANGEL",
    "feature_flags": [
      "watchlist",
      "svi.feed",
      "investor.dealflow",
      "grant_finder",
      "money_radar"
    ],
    "usage_limits": {
      "profiles": 25,
      "watchlist_size": 25,
      "reports_per_month": 10,
      "seats": 1
    },
    "active": true,
    "sort_order": 60
  },
  {
    "id": "investor_advisor",
    "segment": "advisor",
    "name": "Firm",
    "price_aud_cents": 14900,
    "annual_price_aud_cents": 149000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_ADVISOR",
    "feature_flags": [
      "watchlist",
      "svi.feed",
      "investor.dealflow",
      "advisory_equity",
      "advisor_portal",
      "advisor.cohort",
      "white_label",
      "grant_finder",
      "money_radar"
    ],
    "usage_limits": {
      "profiles": 50,
      "clients": 50,
      "reports_per_month": 30,
      "seats": 3
    },
    "active": true,
    "sort_order": 70
  },
  {
    "id": "investor_vc_small",
    "segment": "investor_vc",
    "name": "Program",
    "price_aud_cents": 34900,
    "annual_price_aud_cents": 349000,
    "interval": "monthly",
    "trial_days": 7,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_VC_SMALL",
    "feature_flags": [
      "watchlist",
      "svi.feed",
      "investor.dealflow",
      "advisory_equity",
      "advisor_portal",
      "advisor.cohort",
      "white_label",
      "portfolio",
      "diligence_pack",
      "api",
      "api.access",
      "lp_export",
      "lp_report",
      "grant_finder",
      "money_radar"
    ],
    "usage_limits": {
      "profiles": 200,
      "portfolio_size": 200,
      "reports_per_month": 100,
      "seats": 5
    },
    "active": true,
    "sort_order": 80
  },
  {
    "id": "investor_vc_ent",
    "segment": "investor_vc",
    "name": "VC Enterprise",
    "price_aud_cents": 250000,
    "annual_price_aud_cents": 3000000,
    "interval": "custom",
    "trial_days": 0,
    "stripe_env_var": "STRIPE_PRICE_INVESTOR_VC_ENT",
    "feature_flags": [
      "watchlist",
      "svi.feed",
      "investor.dealflow",
      "advisory_equity",
      "advisor_portal",
      "advisor.cohort",
      "white_label",
      "portfolio",
      "diligence_pack",
      "api",
      "api.access",
      "lp_export",
      "lp_report",
      "custom_benchmark",
      "multi_fund",
      "sso",
      "weekly_delta",
      "grant_finder",
      "money_radar"
    ],
    "usage_limits": {
      "profiles": -1,
      "seats": -1,
      "reports_per_month": -1
    },
    "active": true,
    "sort_order": 90
  },
  {
    "id": "accelerator_starter",
    "segment": "accelerator",
    "name": "Cohort Starter",
    "price_aud_cents": 50000,
    "annual_price_aud_cents": 500000,
    "interval": "monthly",
    "trial_days": 14,
    "stripe_env_var": "STRIPE_PRICE_ACCEL_STARTER",
    "feature_flags": [
      "cohort.view",
      "cohort.view.stats",
      "accelerator.cohort"
    ],
    "usage_limits": {
      "profiles": 25,
      "seats": 15,
      "monthly_credits": 2000
    },
    "active": true,
    "sort_order": 100
  },
  {
    "id": "accelerator_growth",
    "segment": "accelerator",
    "name": "Cohort Growth",
    "price_aud_cents": 150000,
    "annual_price_aud_cents": 1500000,
    "interval": "monthly",
    "trial_days": 14,
    "stripe_env_var": "STRIPE_PRICE_ACCEL_GROWTH",
    "feature_flags": [
      "cohort.view",
      "cohort.view.stats",
      "accelerator.cohort",
      "cohort.manage"
    ],
    "usage_limits": {
      "profiles": 100,
      "seats": 50,
      "monthly_credits": 8000
    },
    "active": true,
    "sort_order": 110
  },
  {
    "id": "accelerator_enterprise",
    "segment": "accelerator",
    "name": "Cohort Enterprise",
    "price_aud_cents": 350000,
    "annual_price_aud_cents": 3500000,
    "interval": "monthly",
    "trial_days": 14,
    "stripe_env_var": "STRIPE_PRICE_ACCEL_ENTERPRISE",
    "feature_flags": [
      "cohort.view",
      "cohort.view.stats",
      "accelerator.cohort",
      "cohort.manage",
      "white_label",
      "api",
      "api.access",
      "sso",
      "lp_report"
    ],
    "usage_limits": {
      "profiles": -1,
      "seats": -1,
      "monthly_credits": -1
    },
    "active": true,
    "sort_order": 120
  },
  {
    "id": "founder_package",
    "segment": "founder",
    "name": "Startup Package",
    "price_aud_cents": 14900,
    "annual_price_aud_cents": 0,
    "interval": "once",
    "trial_days": 0,
    "stripe_env_var": "STRIPE_PRICE_STARTUP_PACKAGE",
    "feature_flags": [
      "startup_package",
      "pdf_branding",
      "grant_finder",
      "money_radar"
    ],
    "usage_limits": {
      "monthly_credits": 25
    },
    "active": true,
    "sort_order": 95
  }
] as const;

export const GENERATED_PLANS_BY_ID: Readonly<Record<string, GeneratedPlan>> =
  Object.fromEntries(GENERATED_PLANS.map(p => [p.id, p]));
