import type { Metadata } from "next";
import Link from "next/link";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { Download, Sparkles, ShieldCheck, BadgeCheck } from "lucide-react";
import { Navbar } from "@/components/site/navbar";
import { Footer } from "@/components/site/footer";
import { Button } from "@/components/ui/button";
import { ScoreCard } from "@/components/score/score-card";
import { getSupabaseAdmin, isSupabaseConfigured } from "@/lib/supabase";
import { hashIp, clientIpFromHeaders } from "@/lib/iphash";
import {
  getInvestorLink,
  isInvestorLinkActive,
  investorLabel,
  recordInvestorLinkView,
  type InvestorLink,
} from "@/lib/investor-links";
import { sendScoreViewed } from "@/lib/email";

// Force dynamic — every render records a view and the token is opaque.
export const dynamic = "force-dynamic";

interface ScoreRow {
  id: string;
  email: string;
  company_name: string | null;
  total_score: number;
  sub_scores: Record<string, number>;
  inputs: Record<string, unknown>;
  score_version?: string | null;
  confidence_score?: number | null;
  missing_inputs?: string[] | null;
  action_plan?: Array<{
    title: string;
    detail: string;
    impact: "high" | "medium" | "low";
  }> | null;
  benchmark?: {
    label: string;
    medianScore: number;
    band: string;
    rationale: string;
  } | null;
  created_at: string;
}

function siteUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(
    /\/$/,
    "",
  );
}

async function fetchScore(scoreId: string): Promise<ScoreRow | null> {
  const supabase = getSupabaseAdmin();
  if (!supabase) return null;
  const { data, error } = await supabase
    .from("scores")
    .select("*")
    .eq("id", scoreId)
    .maybeSingle();
  if (error) {
    console.error("[blockid:s/i] supabase fetch failed", error);
    return null;
  }
  return (data as ScoreRow) ?? null;
}

async function trackAndNotify(link: InvestorLink, score: ScoreRow): Promise<void> {
  const h = await headers();
  const ip = clientIpFromHeaders(h);
  const ua = h.get("user-agent")?.slice(0, 512) ?? null;
  const referer = h.get("referer")?.slice(0, 512) ?? null;
  const ipHash = hashIp(ip);

  // Skip telemetry for known bots so we don't email founders for previewers
  // (Slack, WhatsApp, LinkedIn unfurlers, etc.).
  if (ua && /bot|crawler|spider|preview|fetch|curl|httpclient/i.test(ua)) return;

  const result = await recordInvestorLinkView({
    link,
    viewerIpHash: ipHash,
    viewerUa: ua,
    referer,
  });

  if (result.shouldNotifyFounder) {
    void sendScoreViewed({
      to: score.email,
      slug: score.id,
      viewerLabel: `by ${investorLabel(link)}`,
      companyName: score.company_name,
    });
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const url = `${siteUrl()}/s/i/${token}`;
  const meta: Metadata = {
    title: "Investor View Link — BlockID",
    description:
      "Investor-Ready Score shared via BlockID. Five sub-scores, confidence and benchmark — generated for a specific investor.",
    openGraph: {
      title: "Investor View Link — BlockID",
      url,
      siteName: "BlockID",
      type: "website",
    },
    twitter: { card: "summary_large_image" },
    robots: { index: false, follow: false },
  };

  if (!isSupabaseConfigured()) return meta;

  const link = await getInvestorLink(token);
  if (!link) return meta;
  const score = await fetchScore(link.scoreId);
  if (!score) return meta;

  const co = score.company_name || "Company";
  const title = `${co} · Investor-Ready Score ${score.total_score}/100 — BlockID`;
  return {
    ...meta,
    title,
    description: `${co} scored ${score.total_score}/100 across financials, cap table, governance, founder background and documentation. Generated by BlockID for ${investorLabel(link)}.`,
    openGraph: { ...meta.openGraph, title },
  };
}

export default async function InvestorViewLinkPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;

  if (!isSupabaseConfigured()) notFound();
  const link = await getInvestorLink(token);
  if (!link) notFound();

  const score = await fetchScore(link.scoreId);
  if (!score) notFound();

  const active = isInvestorLinkActive(link);
  if (active) {
    // Don't await: telemetry must never delay the page render. Errors are
    // already swallowed and logged inside trackAndNotify.
    void trackAndNotify(link, score);
  }

  const subScores = [
    { label: "Financials", value: score.sub_scores.financials ?? 0 },
    { label: "Cap Table Hygiene", value: score.sub_scores.capTable ?? 0 },
    { label: "Governance", value: score.sub_scores.governance ?? 0 },
    { label: "Founder Background", value: score.sub_scores.founder ?? 0 },
    { label: "Documentation", value: score.sub_scores.documentation ?? 0 },
  ];
  const confidenceScore = score.confidence_score ?? 78;
  const missingInputs = score.missing_inputs ?? [];
  const actionPlan = score.action_plan ?? [];
  const benchmark = score.benchmark ?? {
    label: "seed · SaaS",
    medianScore: 71,
    band: "within current AU founder benchmark",
    rationale:
      "Benchmark is an internal heuristic until BlockID has enough verified AU company outcomes.",
  };
  const scoreVersion = score.score_version ?? "1.0.0";
  const companyName = score.company_name || "Company";
  const recipientLabel = investorLabel(link);

  return (
    <>
      <Navbar />
      <main id="main" className="flex-1 pt-32 md:pt-40 pb-24">
        <div className="mx-auto max-w-5xl px-6">
          {!active && (
            <div className="mb-8 rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">
              This investor link is no longer active
              {link.revokedAt
                ? " (revoked by the founder)"
                : " (expired)"}
              . Contact the founder for an updated link.
            </div>
          )}

          <header className="max-w-3xl">
            <p className="text-xs uppercase tracking-[0.2em] text-gold-400 font-medium inline-flex items-center gap-2">
              <ShieldCheck strokeWidth={1.75} className="h-4 w-4" />
              Investor View Link
            </p>
            <h1 className="mt-3 text-4xl md:text-5xl font-semibold tracking-tight text-slate-50">
              {companyName}
            </h1>
            <p className="mt-4 inline-flex items-center gap-2 rounded-full border border-brand-500/30 bg-brand-500/10 px-3 py-1 text-xs text-brand-200">
              <BadgeCheck strokeWidth={1.75} className="h-3.5 w-3.5" />
              Prepared for {recipientLabel}
            </p>
            <p className="mt-4 text-base md:text-lg leading-relaxed text-slate-400">
              Investor-Ready Score generated by BlockID. Five sub-scores
              covering the dimensions investors review at seed and Series A.
              Generated{" "}
              <span className="font-mono tabular-nums">
                {score.created_at.slice(0, 10)}
              </span>
              .
            </p>
          </header>

          <section className="mt-10 grid lg:grid-cols-2 gap-8 items-start">
            <ScoreCard
              score={score.total_score}
              subScores={subScores}
              caption={`${score.created_at.slice(0, 10)} · v${scoreVersion}`}
            />

            <div className="rounded-2xl border border-ink-700 bg-ink-900 p-6">
              <h2 className="text-lg font-semibold text-slate-50 inline-flex items-center gap-2">
                <Sparkles strokeWidth={1.75} className="h-5 w-5 text-brand-400" />
                Get your own free score
              </h2>
              <p className="mt-2 text-sm text-slate-400 leading-relaxed">
                BlockID gives every Australian founder a free Investor-Ready
                Score in 5 minutes — one number, five sub-scores, one
                shareable link. No credit card.
              </p>
              <div className="mt-5 flex flex-wrap gap-3">
                <Link href="/score" className="inline-flex">
                  <Button variant="primary">Generate my score</Button>
                </Link>
                <a
                  href={`/s/${score.id}/pdf`}
                  className="inline-flex"
                  target="_blank"
                  rel="noopener"
                >
                  <Button variant="secondary">
                    <Download strokeWidth={1.75} className="h-5 w-5" />
                    Download PDF
                  </Button>
                </a>
              </div>
              <hr className="my-6 border-ink-700" />
              <div className="grid sm:grid-cols-2 gap-3">
                <InfoStat
                  label="Confidence"
                  value={`${confidenceScore}/100`}
                  detail={
                    missingInputs.length
                      ? `${missingInputs.length} missing inputs`
                      : "Core inputs present"
                  }
                />
                <InfoStat
                  label="Benchmark"
                  value={benchmark.label}
                  detail={`${benchmark.band}; median ${benchmark.medianScore}`}
                />
              </div>
              {actionPlan.length > 0 && (
                <div className="mt-6 rounded-xl border border-ink-700 bg-ink-800/40 p-4">
                  <p className="text-xs uppercase tracking-[0.16em] text-slate-500">
                    Recommended actions
                  </p>
                  <ul className="mt-4 space-y-3">
                    {actionPlan.slice(0, 3).map((action) => (
                      <li key={action.title} className="text-sm">
                        <p className="font-medium text-slate-100">
                          {action.title}
                        </p>
                        <p className="mt-1 text-xs leading-relaxed text-slate-400">
                          {action.detail}
                        </p>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              <hr className="my-6 border-ink-700" />
              <dl className="grid grid-cols-2 gap-4 text-xs">
                <div>
                  <dt className="text-slate-500 uppercase tracking-[0.15em]">
                    Generated
                  </dt>
                  <dd className="mt-1 text-slate-300 font-mono tabular-nums">
                    {score.created_at.slice(0, 10)}
                  </dd>
                </div>
                <div>
                  <dt className="text-slate-500 uppercase tracking-[0.15em]">
                    Score version
                  </dt>
                  <dd className="mt-1 text-slate-300 font-mono tabular-nums">
                    v{scoreVersion}
                  </dd>
                </div>
                <div className="col-span-2">
                  <dt className="text-slate-500 uppercase tracking-[0.15em]">
                    Powered by
                  </dt>
                  <dd className="mt-1 text-slate-300">
                    BlockID — Persistent Identity & Trust Infrastructure for
                    Private Capital Markets. AU data residency.
                  </dd>
                </div>
              </dl>
            </div>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}

function InfoStat({
  label,
  value,
  detail,
}: {
  label: string;
  value: string;
  detail: string;
}) {
  return (
    <div className="rounded-xl border border-ink-700 bg-ink-800/40 px-4 py-3">
      <p className="text-[10px] uppercase tracking-[0.16em] text-slate-500">
        {label}
      </p>
      <p className="mt-1 text-sm font-medium text-slate-100">{value}</p>
      <p className="mt-1 text-xs text-slate-500">{detail}</p>
    </div>
  );
}
