/**
 * Accelerator Apply PDF — one page per prompt, drafts side-by-side with the
 * accelerator's own application question labels.
 */
import * as React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { AcceleratorProgram } from "@/lib/agents/accelerator-drafter";
import { PDF_THEME } from "./theme";

// G26: every colour from the one PDF theme (light paper, navy headings, ink body).
const C = {
  ink900: PDF_THEME.ink,
  ink700: "#374151",
  ink500: PDF_THEME.inkTertiary,
  ink400: PDF_THEME.inkFaint,
  surface200: PDF_THEME.border,
  surface100: PDF_THEME.hover,
  brand600: PDF_THEME.navy,
  brand50: PDF_THEME.navySoft,
  white: PDF_THEME.white,
};

const s = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    color: C.ink700,
    backgroundColor: C.white,
    paddingHorizontal: 42,
    paddingVertical: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.surface200,
    paddingBottom: 10,
  },
  brand: { fontSize: 14, fontFamily: "Helvetica-Bold", color: C.brand600 },
  subtitle: { fontSize: 8, color: C.ink400, marginTop: 2 },
  h1: { fontSize: 18, fontFamily: "Helvetica-Bold", color: C.ink900, marginTop: 6 },
  metaRow: { flexDirection: "row", gap: 10, marginBottom: 18 },
  metaCell: {
    flex: 1,
    padding: 8,
    backgroundColor: C.surface100,
    borderRadius: 4,
  },
  metaLabel: {
    fontSize: 7.5,
    color: C.ink500,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  metaValue: { fontSize: 11, fontFamily: "Helvetica-Bold", color: C.ink900, marginTop: 2 },
  promptBox: {
    borderLeftWidth: 3,
    borderLeftColor: C.brand600,
    backgroundColor: C.brand50,
    padding: 8,
    marginBottom: 6,
    borderRadius: 3,
  },
  promptLabel: { fontSize: 10, fontFamily: "Helvetica-Bold", color: C.ink900 },
  promptMeta: { fontSize: 8, color: C.ink500, marginTop: 2 },
  answer: {
    fontSize: 10,
    color: C.ink700,
    lineHeight: 1.5,
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  footer: {
    position: "absolute",
    bottom: 22,
    left: 42,
    right: 42,
    fontSize: 7.5,
    color: C.ink400,
  },
  disclaimer: {
    fontSize: 8,
    color: C.ink500,
    fontStyle: "italic",
    marginTop: 20,
    paddingTop: 10,
    borderTopWidth: 0.5,
    borderTopColor: C.surface200,
  },
});

export interface AcceleratorApplyPdfInput {
  startupName: string;
  program: AcceleratorProgram;
  drafts: Record<string, string>;
  email?: string;
  founderName?: string;
}

export function AcceleratorApplyPDF({ input }: { input: AcceleratorApplyPdfInput }) {
  const today = new Date().toLocaleDateString("en-AU", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  return (
    <Document
      title={`${input.startupName} — ${input.program.name} application draft`}
      author="BlockID.au"
    >
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.brand}>BlockID.au</Text>
            <Text style={s.subtitle}>Accelerator application draft</Text>
            <Text style={s.h1}>{input.startupName}</Text>
          </View>
          <View>
            <Text style={{ fontSize: 8, color: C.ink400, textAlign: "right" }}>{today}</Text>
            {input.email && (
              <Text style={{ fontSize: 8, color: C.ink400, textAlign: "right" }}>
                {input.email}
              </Text>
            )}
          </View>
        </View>

        <View style={s.metaRow}>
          <View style={s.metaCell}>
            <Text style={s.metaLabel}>Program</Text>
            <Text style={s.metaValue}>{input.program.name}</Text>
          </View>
          <View style={s.metaCell}>
            <Text style={s.metaLabel}>Cohort</Text>
            <Text style={s.metaValue}>{input.program.cohort}</Text>
          </View>
          <View style={s.metaCell}>
            <Text style={s.metaLabel}>Region</Text>
            <Text style={s.metaValue}>{input.program.region}</Text>
          </View>
        </View>

        {input.program.prompts.map((prompt) => {
          const answer =
            input.drafts[prompt.id]?.trim() ?? "(no draft generated)";
          return (
            <View key={prompt.id} wrap={false}>
              <View style={s.promptBox}>
                <Text style={s.promptLabel}>{prompt.label}</Text>
                <Text style={s.promptMeta}>
                  Max {prompt.maxChars} chars · Used {answer.length}
                </Text>
              </View>
              <Text style={s.answer}>{answer}</Text>
            </View>
          );
        })}

        <Text style={s.disclaimer}>
          Draft generated by BlockID.au for {input.startupName}. Review, edit,
          and submit at {input.program.url}. Numbers and traction claims should
          be verified before submission.
        </Text>

        <Text style={s.footer}>
          Prepared by BlockID.au · {input.program.name} application draft
        </Text>
      </Page>
    </Document>
  );
}

export async function renderAcceleratorApplyPdf(
  input: AcceleratorApplyPdfInput,
): Promise<Buffer> {
  const buf = await renderToBuffer(<AcceleratorApplyPDF input={input} />);
  return buf as Buffer;
}
