// Disclaimer footer stamper (T-0425).
//
// Given the raw bytes of a PDF or DOCX blob generated by the report
// pipeline, append a footer with the current disclaimer text + version
// + hash so downstream regulators can prove which acknowledgement the
// reader was shown. Version metadata is sourced from disclaimer_registry
// (looked up server-side by lib/legal/versions.ts).

import "server-only";

import { getSupabaseAdmin } from "@/lib/supabase";

export type DisclaimerKind =
  | "not_financial_advice"
  | "equity_offer_disclaimer"
  | "share_issuance"
  | "trial"
  | "tos"
  | "privacy"
  | "wholesale_certification";

export type Jurisdiction = "AU" | "GLOBAL";

export interface DisclaimerRecord {
  id: string;
  version: string;
  jurisdiction: string;
  kind: string;
  body_md: string;
  hash: string;
}

/** Look up the newest active disclaimer for (kind, jurisdiction). */
export async function loadDisclaimer(kind: DisclaimerKind, jurisdiction: Jurisdiction = "AU"): Promise<DisclaimerRecord | null> {
  const supabase = getSupabaseAdmin();
  if (!supabase) return null;
  const { data } = await supabase
    .from("disclaimer_registry")
    .select("id, version, jurisdiction, kind, body_md, hash")
    .eq("kind", kind)
    .eq("jurisdiction", jurisdiction)
    .lte("effective_from", new Date().toISOString())
    .order("effective_from", { ascending: false })
    .limit(1)
    .maybeSingle();
  return (data as DisclaimerRecord | null) ?? null;
}

function truncateHash(hash: string): string {
  return hash.slice(0, 12);
}

function footerText(rec: DisclaimerRecord): string {
  return `${rec.body_md}\n\nDisclaimer ${rec.id} v${rec.version} · hash ${truncateHash(rec.hash)} · Auschain PTY LTD (ACN 659 615 111 · ABN 79 659 615 111).`;
}

// ── PDF stamper ────────────────────────────────────────────────────────

/**
 * Append a full-width footer with the disclaimer to every page of a PDF.
 * Uses pdf-lib for zero-runtime-cost text overlay (loaded on demand so the
 * default report path pays no bundle cost when unused).
 */
export async function stampPdfFooter(pdfBytes: Uint8Array, kind: DisclaimerKind, jurisdiction: Jurisdiction = "AU"): Promise<Uint8Array> {
  const rec = await loadDisclaimer(kind, jurisdiction);
  if (!rec) return pdfBytes;

  let PDFDocument: unknown, StandardFonts: unknown, rgb: unknown;
  try {
    // Soft dependency — repo has @react-pdf/renderer only. When pdf-lib
    // is installed the stamper writes a footer; otherwise it returns the
    // untouched bytes so callers can fall back to their template footer.
    const mod: { PDFDocument: unknown; StandardFonts: unknown; rgb: unknown } =
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await (Function('return import("pdf-lib")')() as Promise<any>);
    PDFDocument = mod.PDFDocument;
    StandardFonts = mod.StandardFonts;
    rgb = mod.rgb;
  } catch {
    console.warn("[disclaimer-footer] pdf-lib not installed — returning unstamped PDF");
    return pdfBytes;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const Doc = PDFDocument as any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const Fonts = StandardFonts as any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rgbFn = rgb as (r: number, g: number, b: number) => any;

  const doc = await Doc.load(pdfBytes);
  const font = await doc.embedFont(Fonts.Helvetica);

  const text = footerText(rec);
  const fontSize = 7;
  const marginX = 32;
  const marginY = 20;
  const lineHeight = fontSize + 2;

  for (const page of doc.getPages()) {
    const { width } = page.getSize();
    const wrapWidth = width - marginX * 2;
    const lines = wrapText(text, font, fontSize, wrapWidth);
    for (let i = 0; i < lines.length; i++) {
      page.drawText(lines[i], {
        x: marginX,
        y: marginY + (lines.length - 1 - i) * lineHeight,
        size: fontSize,
        font,
        color: rgbFn(0.35, 0.4, 0.5),
      });
    }
  }

  return await doc.save();
}

function wrapText(text: string, font: { widthOfTextAtSize(t: string, s: number): number }, fontSize: number, maxWidth: number): string[] {
  const words = text.replace(/\n+/g, " ").split(/\s+/);
  const lines: string[] = [];
  let cursor = "";
  for (const w of words) {
    const candidate = cursor ? `${cursor} ${w}` : w;
    if (font.widthOfTextAtSize(candidate, fontSize) > maxWidth) {
      if (cursor) lines.push(cursor);
      cursor = w;
    } else {
      cursor = candidate;
    }
  }
  if (cursor) lines.push(cursor);
  return lines;
}

// ── DOCX stamper ───────────────────────────────────────────────────────

/**
 * Append a footer paragraph to a docx binary with the same disclaimer text.
 * We regenerate the doc via `docx` library — pass the exportable
 * paragraphs from the source template as `sourceParagraphs`. When the caller
 * doesn't have access to the source AST, use `appendPagePlaceholder=true`
 * to produce a single-page addendum instead.
 */
export interface DocxFooterOptions {
  /** Raw docx bytes if you want us to embed a footer object. */
  originalBytes?: Uint8Array;
  /** If true, generate a single "Appendix" page rather than post-processing. */
  appendPagePlaceholder?: boolean;
}

export async function stampDocxFooter(opts: DocxFooterOptions, kind: DisclaimerKind, jurisdiction: Jurisdiction = "AU"): Promise<Uint8Array | null> {
  const rec = await loadDisclaimer(kind, jurisdiction);
  if (!rec) return opts.originalBytes ?? null;

  if (opts.appendPagePlaceholder) {
    const { Document, Packer, Paragraph, TextRun } = await import("docx");
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "Disclaimer", bold: true, size: 20 }),
              ],
            }),
            new Paragraph({
              children: [new TextRun({ text: footerText(rec), size: 14, color: "555F73" })],
            }),
          ],
        },
      ],
    });
    return await Packer.toBuffer(doc).then((b) => new Uint8Array(b));
  }

  // Round-trip stamping (mutating an existing binary) is non-trivial in
  // `docx`; when caller supplies originalBytes but no strategy, we return
  // it unchanged and rely on the caller re-generating with a header/footer
  // section that includes the disclaimer text.
  return opts.originalBytes ?? null;
}
