/**
 * src/lib/agents/cmo-market-research.ts
 * BlockID.au CMO Domain Module
 * Focus: Startup Navigation System positioning and AU Market Intelligence
 */

export interface CompetitorProfile {
  /** Competitor company name */
  name: string;
  /** Competitor website URL */
  website: string;
  /** Competitor category */
  category: string;
  /** Competitor funding stage */
  fundingStage: string;
  /** Competitor estimated revenue */
  estimatedRevenue: string;
  /** Competitor strengths */
  strengths: string[];
  /** Competitor weaknesses */
  weaknesses: string[];
  /** Competitor market share (0‑1) */
  marketShare: number;
  /** Number of AI‑powered features */
  aiPoweredFeatures: number;
  /** Feature release frequency per quarter */
  featureReleaseFrequency: number;
  /** Adoption rate of cybersecurity features (0-1) */
  cybersecurityFeatureAdoption: number;
  /** Data refresh latency in minutes (Industry Benchmark: 4.2m) */
  dataRefreshLatencyMinutes?: number;
  /** AI valuation accuracy percentage (Industry Benchmark: 92%) */
  aiValuationAccuracy?: number;
}

/** Customer segment definition */
export interface CustomerSegment {
  /** Segment name */
  name: string;
  /** Segment size (number of companies) */
  size: number;
  /** Willingness to pay */
  willingness: 'high' | 'medium' | 'low';
  /** Primary focus: 'domestic' | 'global' */
  marketFocus: 'domestic' | 'global';
  /** Percentage of this segment prioritizing AI adoption (0-1) */
  aiPrioritizationRate: number;
}

/** Market research overview */
export interface MarketResearch {
  /** Total Addressable Market (AU$) */
  tam: number;
  /** Serviceable Available Market (AU$) */
  sam: number;
  /** Serviceable Obtainable Market (AU$) */
  som: number;
  /** TAM data source */
  tamSource: string;
  /** Industry */
  industry: string;
  /** Region */
  region: string;
  /** Annual growth rate (0‑1) */
  growthRate: number;
  /** Competitor profiles */
  competitors: CompetitorProfile[];
}

/** AU Startup Valuation Benchmarks based on 2024 data */
export const AU_MARKET_BENCHMARKS = {
  SEED_VALUATION: { min: 4000000, max: 7000000, currency: 'AUD' },
  REVENUE_MULTIPLE: { min: 4, max: 8 },
  AI_PREMIUM_MULTIPLIER: 1.3,
  RUNWAY_REQUIREMENT_MONTHS: { min: 18, max: 24 },
  NAV_SYSTEM_DILUTION_REDUCTION: 0.03, // Reduction from 12% to 9%
  NAV_SYSTEM_CAGR: 0.22, // 22% YoY growth for navigation platforms
  VALUATION_TOOL_CAGR: 0.13, // 13% YoY for pure valuation tools
};

/** Content Marketing & SEO Performance Metrics (AU B2B) */
export interface MarketingBenchmarks {
  blogConversionRate: { min: 0.021, max: 0.025 };
  videoEngagementRate: { min: 0.035, max: 0.05 };
  aiContentBudgetAllocation: { min: 0.15, max: 0.25 };
  costPerLeadAU: { min: 45, max: 120 };
  aiOverviewCtrReduction: { min: 0.18, max: 0.25 };
  aiContentVolatility: { min: 0.3, max: 0.5 };
}

export const CURRENT_MARKETING_BENCHMARKS: MarketingBenchmarks = {
  blogConversionRate: { min: 0.021, max: 0.025 },
  videoEngagementRate: { min: 0.035, max: 0.05 },
  aiContentBudgetAllocation: { min: 0.15, max: 0.25 },
  costPerLeadAU: { min: 45, max: 120 },
  aiOverviewCtrReduction: { min: 0.18, max: 0.25 },
  aiContentVolatility: { min: 0.3, max: 0.5 },
};

/**
 * Calculates the estimated valuation of an AU SaaS startup
 * @param arr Annual Recurring Revenue
 * @param isAiPowered Whether the company has a core AI component
 * @returns Estimated post-money valuation (AUD)
 */
export function calculateAUStartupValuation(arr: number, isAiPowered: boolean): number {
  const medianMultiple = (AU_MARKET_BENCHMARKS.REVENUE_MULTIPLE.min + AU_MARKET_BENCHMARKS.REVENUE_MULTIPLE.max) / 2;
  let valuation = arr * medianMultiple;
  if (isAiPowered) {
    valuation *= AU_MARKET_BENCHMARKS.AI_PREMIUM_MULTIPLIER;
  }
  return valuation;
}

/**
 * Estimates the equity dilution savings when using a 'Startup Navigation System' vs traditional tools
 * @param currentDilution Current estimated dilution (e.g., 0.12 for 12%)
 * @returns The absolute reduction in dilution percentage
 */
export function calculateDilutionSavings(currentDilution: number): number {
  return currentDilution - (currentDilution - AU_MARKET_BENCHMARKS.NAV_SYSTEM_DILUTION_REDUCTION);
}

/**
 * Predicts the growth of the Navigation SaaS market vs Valuation SaaS market
 * @param currentMarketSize Current market size in USD
 * @param years Projection period in years
 * @param type 'navigation' | 'valuation'
 * @returns Projected market size
 */
export function projectMarketGrowth(currentMarketSize: number, years: number, type: 'navigation' | 'valuation'): number {
  const growthRate = type === 'navigation' 
    ? AU_MARKET_BENCHMARKS.NAV_SYSTEM_CAGR 
    : AU_MARKET_BENCHMARKS.VALUATION_TOOL_CAGR;
  return currentMarketSize * Math.pow(1 + growthRate, years);
}

/**
 * Analyzes SEO risk based on AI-content density and EEAT signals
 * @param aiContentPercentage Percentage of content generated by AI (0-1)
 * @param hasStrongEEAT Whether the site has strong Experience, Expertise, Authoritativeness, and Trustworthiness signals
 * @returns Volatility risk score (0-1)
 */
export function analyzeSEORisk(aiContentPercentage: number, hasStrongEEAT: boolean): number {
  let risk = aiContentPercentage * ((CURRENT_MARKETING_BENCHMARKS.aiContentVolatility.min + CURRENT_MARKETING_BENCHMARKS.aiContentVolatility.max) / 2);
  if (hasStrongEEAT) {
    risk *= 0.5; // Strong EEAT significantly stabilizes ranking
  }
  return Math.min(risk, 1);
}

/**
 * Calculates the required monthly burn to maintain the AU industry standard runway
 * @param totalFunding Total funding raised (AUD)
 * @returns Recommended monthly expenditure limit
 */
export function calculateRecommendedMonthlyBurn(totalFunding: number): number {
  const avgRunway = (AU_MARKET_BENCHMARKS.RUNWAY_REQUIREMENT_MONTHS.min + AU_MARKET_BENCHMARKS.RUNWAY_REQUIREMENT_MONTHS.max) / 2;
  return totalFunding / avgRunway;
}
