/**
 * src/lib/agents/cmo-market-research.ts
 * BlockID.au CMO Domain Module
 * Focus: Startup Navigation System positioning and AU Market Intelligence
 */

export interface CompetitorProfile {
  /** Competitor company name */
  name: string;
  /** Competitor website URL */
  website: string;
  /** Competitor category */
  category: string;
  /** Competitor funding stage */
  fundingStage: string;
  /** Competitor estimated revenue */
  estimatedRevenue: string;
  /** Competitor strengths */
  strengths: string[];
  /** Competitor weaknesses */
  weaknesses: string[];
  /** Competitor market share (0‑1) */
  marketShare: number;
  /** Number of AI‑powered features */
  aiPoweredFeatures: number;
  /** Feature release frequency per quarter */
  featureReleaseFrequency: number;
  /** Adoption rate of cybersecurity features (0-1) */
  cybersecurityFeatureAdoption: number;
  /** Data refresh latency in minutes (Industry Benchmark: 4.2m) */
  dataRefreshLatencyMinutes?: number;
  /** AI valuation accuracy percentage (Industry Benchmark: 92%) */
  aiValuationAccuracy?: number;
}

/** Customer segment definition */
export interface CustomerSegment {
  /** Segment name */
  name: string;
  /** Segment size (number of companies) */
  size: number;
  /** Willingness to pay */
  willingness: 'high' | 'medium' | 'low';
  /** Primary focus: 'domestic' | 'global' */
  marketFocus: 'domestic' | 'global';
  /** Percentage of this segment prioritizing AI adoption (0-1) */
  aiPrioritizationRate: number;
}

/** Market research overview */
export interface MarketResearch {
  /** Total Addressable Market (AU$) */
  tam: number;
  /** Serviceable Available Market (AU$) */
  sam: number;
  /** Serviceable Obtainable Market (AU$) */
  som: number;
  /** TAM data source */
  tamSource: string;
  /** Industry */
  industry: string;
  /** Region */
  region: string;
  /** Annual growth rate (0‑1) */
  growthRate: number;
  /** Competitor profiles */
  competitors: CompetitorProfile[];
}

/** AU SaaS Valuation Benchmarks based on 2024 Market Sentiment */
export const AU_MARKET_BENCHMARKS = {
  SEED_VALUATION: { min: 4000000, max: 7000000, currency: 'AUD' },
  REVENUE_MULTIPLE: { min: 4, max: 8 },
  AI_PREMIUM_MULTIPLIER: 1.3,
  AVG_RUNWAY_REQUIREMENT_MONTHS: { min: 18, max: 24 },
  CPL_CONTENT_AVG: { min: 45, max: 120, currency: 'AUD' },
};

/** Content Marketing Performance Benchmarks 2024 */
export const CONTENT_BENCHMARKS = {
  B2B_BLOG_CONVERSION: { min: 0.021, max: 0.025 },
  SHORT_FORM_VIDEO_ENGAGEMENT: { min: 0.035, max: 0.050 },
  AI_TOOL_BUDGET_ALLOCATION: { min: 0.15, max: 0.25 },
  SEO_AI_OVERVIEW_CTR_REDUCTION: { min: 0.18, max: 0.25 },
};

/** Navigation System Positioning Data */
export const POSITIONING_METRICS = {
  NAVIGATION_VS_VALUATION_GROWTH: {
    navigationSaaSYoY: 0.22,
    valuationOnlyYoY: 0.13,
    projectedMarket2028: 4100000000,
  },
  DILUTION_IMPACT: {
    pureValuationToolAvg: 0.12,
    navigationPlatformAvg: 0.09,
  },
};

/**
 * Calculates the estimated post-money valuation for an AU SaaS startup
 * incorporating the AI Premium Multiplier if applicable.
 * @param arr Annual Recurring Revenue
 * @param isAICompany Whether the company leverages core AI technology
 * @param multiple Custom revenue multiple (defaults to AU median)
 */
export function calculateAUValuation(
  arr: number,
  isAICompany: boolean,
  multiple?: number
): number {
  const baseMultiple = multiple || (AU_MARKET_BENCHMARKS.REVENUE_MULTIPLE.min + AU_MARKET_BENCHMARKS.REVENUE_MULTIPLE.max) / 2;
  const multiplier = isAICompany ? AU_MARKET_BENCHMARKS.AI_PREMIUM_MULTIPLIER : 1.0;
  return arr * baseMultiple * multiplier;
}

/**
 * Estimates the dilution reduction benefit of moving from a 
 * pure valuation tool to a holistic 'Startup Navigation System'.
 * @param currentDilution Current estimated dilution rate (0-1)
 * @returns The projected dilution rate after adopting a navigation system
 */
export function estimateDilutionReduction(currentDilution: number): number {
  const reductionFactor = POSITIONING_METRICS.DILUTION_IMPACT.navigationPlatformAvg / POSITIONING_METRICS.DILUTION_IMPACT.pureValuationToolAvg;
  return currentDilution * reductionFactor;
}

/**
 * Calculates the projected cost per lead (CPL) for a content campaign
 * adjusted for AU market averages.
 * @param budget Total content budget
 * @param expectedConversionRate Expected conversion rate (0-1)
 * @returns Projected number of leads
 */
export function projectLeadVolume(budget: number, expectedConversionRate: number): number {
  const avgCPL = (AU_MARKET_BENCHMARKS.CPL_CONTENT_AVG.min + AU_MARKET_BENCHMARKS.CPL_CONTENT_AVG.max) / 2;
  const baseLeads = budget / avgCPL;
  return baseLeads * (expectedConversionRate / CONTENT_BENCHMARKS.B2B_BLOG_CONVERSION.min);
}

/**
 * Analyzes SEO risk based on current AI Overview trends.
 * @param organicTraffic Current organic traffic volume
 * @param aiContentPercentage Percentage of content generated by AI (0-1)
 * @returns Projected traffic volatility and potential CTR loss
 */
export function analyzeSEORisk(organicTraffic: number, aiContentPercentage: number) {
  const ctrLoss = (CONTENT_BENCHMARKS.SEO_AI_OVERVIEW_CTR_REDUCTION.min + CONTENT_BENCHMARKS.SEO_AI_OVERVIEW_CTR_REDUCTION.max) / 2;
  const volatility = aiContentPercentage > 0.5 ? 0.5 : 0.3;
  return {
    projectedTrafficLoss: organicTraffic * ctrLoss,
    volatilityIndex: volatility,
    riskLevel: aiContentPercentage > 0.7 ? 'High' : 'Medium',
  };
}
