// GET/POST /api/investor-pack/preview
//
// T-1201 preview endpoint for the Goal 5B investor pack (v2).
//
// Composes an `InvestorPackData` payload from whatever workspace state is
// currently readable for the authenticated founder, then renders it via
// `renderInvestorPack()` and returns the PDF binary.
//
// Query params:
//   ?download=1   → Content-Disposition: attachment
//   (otherwise)   → Content-Disposition: inline (browser preview)
//
// Guardrails:
// - Requires auth (401 if unauthenticated).
// - Never fabricates numbers: when a table or series is missing, the PDF
//   template renders "Data unavailable" placeholders rather than random
//   figures.
// - Assemble here is intentionally simple. The full state assembler is
//   T-1202; this route uses best-effort direct lookups so the preview
//   works today.

import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { getProjectIdFromRequest } from "@/lib/projects";
import { getSupabaseAdmin } from "@/lib/supabase";
import {
  renderInvestorPack,
  SVI_13_CRITERIA,
  type InvestorPackData,
} from "@/lib/pdf/investor-pack";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

function sanitizeFilenamePart(input: string): string {
  return input
    .replace(/[^\w\s-]+/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60)
    .toLowerCase() || "startup";
}

function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

/* eslint-disable @typescript-eslint/no-explicit-any */
async function assemble(
  userId: string,
  userEmail: string,
  projectId: string | null,
): Promise<InvestorPackData> {
  const admin = getSupabaseAdmin();
  const asOfDate = todayIsoDate();

  let startupName = userEmail ? userEmail.split("@")[0] : "Startup";
  let tagline: string | undefined;
  let sector: string | undefined;

  // Best-effort project lookup — pass through gracefully when the row or the
  // supabase client is absent.
  if (admin && projectId) {
    try {
      const { data: proj } = await admin
        .from("projects")
        .select("name, description, industry")
        .eq("id", projectId)
        .maybeSingle();
      if (proj) {
        if (typeof proj.name === "string" && proj.name.trim()) {
          startupName = proj.name;
        }
        if (typeof proj.description === "string" && proj.description.trim()) {
          tagline = proj.description as string;
        }
        if (typeof proj.industry === "string" && proj.industry.trim()) {
          sector = proj.industry as string;
        }
      }
    } catch {
      /* fall through to defaults */
    }
  }

  // Best-effort app_users lookup — captures plan + fallback display name.
  if (admin) {
    try {
      const { data: appUser } = await admin
        .from("app_users")
        .select("display_name")
        .eq("id", userId)
        .maybeSingle();
      if (
        appUser &&
        typeof (appUser as any).display_name === "string" &&
        (appUser as any).display_name.trim() &&
        !tagline
      ) {
        tagline = `Prepared by ${(appUser as any).display_name}`;
      }
    } catch {
      /* ignore — display name is decorative */
    }
  }

  // SVI grade + score + criteria placeholder. The full assembler (T-1202)
  // joins svi_reports + svi_report_evidence. Until then, we ship the 13
  // canonical criteria with unscored rows so the table always paints.
  const svi: InvestorPackData["svi"] = {
    grade: "—",
    score: 0,
    delta30d: undefined,
    criteria: SVI_13_CRITERIA.map((c) => ({
      id: c.id,
      label: c.label,
      score: NaN,
    })),
  };

  return {
    startup: { name: startupName, tagline, sector, asOfDate },
    svi,
    capTable: undefined,
    traction: { mrrHistory: [] },
    teaser: {
      headline: startupName,
      oneliner:
        "Investor pack generated by BlockID.au — preview render. Complete your workspace to fill every section.",
    },
  };
}
/* eslint-enable @typescript-eslint/no-explicit-any */

async function handle(request: Request): Promise<Response> {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json(
        { ok: false, error: "Authentication required" },
        { status: 401 },
      );
    }

    const url = new URL(request.url);
    const download = url.searchParams.get("download") === "1";

    const projectId = await getProjectIdFromRequest();
    const data = await assemble(user.id, user.email, projectId);
    const buffer = await renderInvestorPack(data);

    const filenamePart = sanitizeFilenamePart(data.startup.name);
    const filename = `investor-pack-${filenamePart}.pdf`;
    const disposition = download
      ? `attachment; filename="${filename}"`
      : `inline; filename="${filename}"`;

    return new NextResponse(new Uint8Array(buffer), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": disposition,
        "Cache-Control": "no-store",
        "X-Investor-Pack-Version": "v2-preview",
      },
    });
  } catch (err) {
    console.error("[investor-pack:preview]", err);
    return NextResponse.json(
      { ok: false, error: "PDF preview failed" },
      { status: 500 },
    );
  }
}

export async function GET(request: Request): Promise<Response> {
  return handle(request);
}

export async function POST(request: Request): Promise<Response> {
  return handle(request);
}
