/**
 * Post-deploy hydrated smoke — Playwright.
 *
 * Runs AFTER a successful deploy (curl-based gates already passed) to catch
 * regressions the SSR-only curl grep in scripts/deploy-live.sh can't see:
 * client-side rendered content behind interactive tabs, hydrated widgets,
 * and image responses generated by App Router opengraph-image routes.
 *
 * The 2026-07-23 outage that prompted this file: the Accelerator tab on
 * /pricing swapped its plan matrix client-side (SegmentTabs). The old curl
 * probe fetched HTML that only contained the Founder tab's plans, so a
 * regression that broke the Accelerator surface (missing "Cohort Enterprise")
 * would not have been caught by grep.
 *
 * Constraints:
 *   - Reuses playwright.config.ts baseURL (PLAYWRIGHT_BASE_URL env, defaults
 *     to https://blockid.au via package.json script).
 *   - Target <90s wall time. Chromium only. Every S7-B test below is
 *     capped at 15 s (test.setTimeout) so a stuck page cannot hang Gate 12.
 */

import { test, expect } from "@playwright/test";

// Give each hydrated page a hard ceiling so a stuck deploy doesn't hang CI.
const PAGE_TIMEOUT = 15_000;

test.describe("Post-deploy hydrated smoke", () => {
  test.setTimeout(45_000);

  test("/pricing — 3-rung ladder renders three tier cards (Free/Growth/Pro)", async ({
    page,
  }) => {
    // Post-Workstream B (v3.9.23): /pricing collapsed from 4-tab persona
    // segmentation to a Universal 3-rung ladder + ContactSalesRow below.
    // G12 (2026-09-10) added a two-way Founder | Evaluator switch; the
    // Founder tab is the default, so the bare URL must still render the
    // three canonical founder tier fragment IDs for the deep-link surface.
    test.setTimeout(30_000);
    await page.goto("/pricing", { waitUntil: "domcontentloaded" });
    for (const id of ["tier-free", "tier-growth", "tier-pro"]) {
      await expect(page.locator(`#${id}`)).toBeVisible({
        timeout: PAGE_TIMEOUT,
      });
    }
  });

  test("/pricing?segment=evaluator — Evaluator tab renders Scout / Firm / Program", async ({
    page,
  }) => {
    // G12 (2026-09-10, T0268): /pricing carries a two-way Founder |
    // Evaluator switch. The deep link must land on the Evaluator ladder
    // (investor_angel / investor_advisor / investor_vc_small) and every
    // rung must route to the evaluator signup, not contact-sales.
    test.setTimeout(30_000);
    await page.goto("/pricing?segment=evaluator", {
      waitUntil: "domcontentloaded",
    });
    for (const id of ["tier-scout", "tier-firm", "tier-program"]) {
      await expect(page.locator(`#${id}`)).toBeVisible({
        timeout: PAGE_TIMEOUT,
      });
    }
    await expect(
      page.locator('a[href*="/signup?segment=evaluator&plan=investor_angel"]'),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
  });

  test("/pricing — ContactSalesRow surfaces Accelerator + VC Enterprise + Enterprise", async ({
    page,
  }) => {
    // Accelerator/VC Enterprise/Enterprise SKUs live in the ContactSalesRow
    // beneath both ladders. Copy source: pricing/page.tsx ContactSalesRow.
    test.setTimeout(30_000);
    await page.goto("/pricing", { waitUntil: "domcontentloaded" });
    await expect(page.getByText(/accelerator/i).first()).toBeVisible({
      timeout: PAGE_TIMEOUT,
    });
    await expect(page.getByText(/enterprise/i).first()).toBeVisible({
      timeout: PAGE_TIMEOUT,
    });
  });

  test("/roadmap — Recently landed section renders", async ({ page }) => {
    await page.goto("/roadmap", { waitUntil: "domcontentloaded" });
    await expect(
      page.getByRole("heading", { name: /recently landed/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
  });

  test("/workspace/branding — loads or redirects to /auth/login", async ({
    page,
  }) => {
    const resp = await page.goto("/workspace/branding", {
      waitUntil: "domcontentloaded",
    });
    expect(resp, "no response for /workspace/branding").not.toBeNull();
    const status = resp!.status();
    // Signed-out users are redirected to /auth/login; signed-in reach the page.
    // Both count as healthy; a 4xx/5xx here is the regression we're catching.
    expect([200, 302, 307], `unexpected status ${status}`).toContain(status);
    const finalUrl = page.url();
    const okUrl =
      /\/workspace\/branding($|\?)/.test(finalUrl) ||
      /\/auth\/login($|\?)/.test(finalUrl);
    expect(okUrl, `unexpected final URL ${finalUrl}`).toBe(true);
  });

  // ── /workspace/audit-log + /workspace/projects (iter-12) ────────────
  // Both pages call `redirect("/auth/login?next=...")` inside an async
  // Server Component when getCurrentUser() returns null. Because they
  // sit under app/workspace/loading.tsx, Next 16 streams a shell + the
  // NEXT_REDIRECT template rather than returning a raw 307 to the wire.
  // A `curl -sI` sees HTTP 200 and (incorrectly) flags this as an auth
  // leak — the client runtime honours the template and lands on
  // /auth/login. This hydrated smoke asserts the visible behaviour so
  // the false-positive from the iter-12 curl-only gate can't recur.
  // /dashboard/portfolio (iter-14, shipped 7ed825be) shares the same
  // getCurrentUser()→redirect() auth-gate pattern, so it lives in the
  // same loop.
  for (const path of [
    "/workspace/audit-log",
    "/workspace/projects",
    "/workspace/projects/archived",
    "/dashboard/portfolio",
  ] as const) {
    test(`${path} — anonymous lands on /auth/login (hydrated)`, async ({
      page,
      context,
    }) => {
      await context.clearCookies();
      const resp = await page.goto(path, { waitUntil: "domcontentloaded" });
      expect(resp, `no response for ${path}`).not.toBeNull();
      const status = resp!.status();
      // 200 (streamed shell) or a raw 307/302 both count — regression is 4xx/5xx.
      expect([200, 302, 307], `unexpected status ${status}`).toContain(status);
      // Once hydration processes the NEXT_REDIRECT template the URL must
      // settle on /auth/login (anonymous session).
      await page.waitForURL(/\/auth\/login/, { timeout: PAGE_TIMEOUT });
      // Next.js 16 emits `next=` with the raw path (not percent-encoded), but
      // some intermediate proxies may re-encode `/`. Accept either form so
      // this stays a behavior assertion, not an encoding assertion.
      const encoded = path.replace(/\//g, "%2F");
      expect(page.url()).toMatch(
        new RegExp(`/auth/login.*next=.*(?:${path}|${encoded})`),
      );
    });
  }

  test("/workspace/audit-log — login redirect carries exact next param", async ({
    page,
    context,
  }) => {
    // iter-18 hardening: the loop above only checks that *some* next param
    // survives. This narrower assertion pins the exact target so a silent
    // change to the redirect helper — dropping `next`, pointing it at a
    // fallback like /dashboard, or double-encoding it — fails loudly on
    // the audit-log surface the compliance team deep-links into after
    // sign-in. Anonymous only; no auth-fixture needed.
    //
    // Compared after one decode rather than as a raw substring. The proxy
    // builds `next` with encodeURIComponent (required: an unencoded `&`
    // in a deep link would truncate the value at the query parser), and
    // login-form.tsx reads it via searchParams.get(), which decodes once.
    // Asserting the decoded value pins the contract that actually matters
    // — where the user lands — and still catches double-encoding, since
    // `%252F…` decodes to `%2F…` and fails this equality.
    await context.clearCookies();
    await page.goto("/workspace/audit-log", { waitUntil: "domcontentloaded" });
    await page.waitForURL(/\/auth\/login/, { timeout: PAGE_TIMEOUT });
    const finalUrl = page.url();
    const nextParam = new URL(finalUrl).searchParams.get("next");
    expect(
      nextParam,
      `expected next=/workspace/audit-log after one decode, got ${finalUrl}`,
    ).toBe("/workspace/audit-log");
  });

  test("/dashboard/portfolio — post-redirect login shell hydrates", async ({
    page,
    context,
  }) => {
    // After the auth-gate redirect, the /auth/login page must render its
    // canonical hero shell — protects the empty-state / column layout on
    // /dashboard/portfolio from a silent regression that turns the redirect
    // into a blank page (e.g. a broken WorkspaceLayout import).
    await context.clearCookies();
    await page.goto("/dashboard/portfolio", { waitUntil: "domcontentloaded" });
    await page.waitForURL(/\/auth\/login/, { timeout: PAGE_TIMEOUT });
    await expect(
      page.getByRole("heading", { name: /sign in to blockid/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
  });

  test("/showcase/blockid — opengraph-image returns image/png", async ({
    request,
  }) => {
    const resp = await request.get("/showcase/blockid/opengraph-image");
    expect(resp.status()).toBe(200);
    const ct = resp.headers()["content-type"] ?? "";
    expect(ct.toLowerCase()).toContain("image/png");
  });

  // ── S7-B (2026-09-10): Money Finder + G12 marketing surfaces ──────────
  // Each of these is a hydrated journey the curl gates cannot see: the
  // /funding intake is a client form that only enables its submit button
  // after React state fills in, the preview card is fetched from the live
  // /api/funding/preview route (nothing stubbed — the point is to catch a
  // broken catalogue read or matcher), and the sample report / unlock
  // tables / comparison table / pilot CTA are the pages the ProductHunt kit
  // and the G12 evaluator funnel link to. Every test keeps a 15 s ceiling.

  test("/funding — hero + 3-question intake, live preview after NSW / MVP / agtech", async ({
    page,
  }) => {
    test.setTimeout(15_000);
    await page.goto("/funding", { waitUntil: "domcontentloaded" });
    // Hero H1 is live-computed ("There's A$X in Australian grants…") or the
    // fallback ("Australian startup grants, programs and investors…") — both
    // name grants.
    await expect(
      page.getByRole("heading", { level: 1, name: /grants/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
    await expect(
      page.getByRole("heading", { name: /what could you apply for this year/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });

    // Hydration probe: the "Improve my match" drawer toggle only flips
    // aria-expanded once React owns the form. Re-click while it does not,
    // instead of sleeping — a click that lands pre-hydration is simply lost.
    const drawer = page.getByRole("button", { name: /improve my match/i });
    await expect(drawer).toBeVisible({ timeout: PAGE_TIMEOUT });
    await expect(async () => {
      await drawer.click();
      await expect(drawer).toHaveAttribute("aria-expanded", "true", { timeout: 1_000 });
    }).toPass({ timeout: PAGE_TIMEOUT });

    await page
      .getByLabel(/what are you building/i)
      .fill("Soil-moisture sensors and an app that tell grain farmers when to irrigate");
    await page.getByLabel(/where is the company registered/i).selectOption("NSW");
    await page.getByRole("radio", { name: /^MVP/i }).check();
    const agtech = page.getByRole("button", { name: /agtech \/ food/i });
    await agtech.click();
    await expect(agtech).toHaveAttribute("aria-pressed", "true", { timeout: PAGE_TIMEOUT });

    const submit = page.getByRole("button", { name: /show my matches/i });
    await expect(submit).toBeEnabled({ timeout: PAGE_TIMEOUT });
    await submit.click();

    // Live preview: the D-3 sentence, or the never-blank national fallback.
    await expect(
      page.getByRole("heading", {
        name: /^We found \d+ grants|^No exact matches yet/i,
      }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
  });

  // S8-B (2026-09-11) mobile check: at a 400px viewport the /funding page
  // must not scroll sideways. The intake form, the compact Money Radar tile
  // and the marketing tables all wrap or live inside overflow-x-auto
  // containers; any element wider than the viewport shows up here as
  // documentElement.scrollWidth > innerWidth.
  test("/funding — no horizontal page overflow at a 400px viewport", async ({ page }) => {
    test.setTimeout(20_000);
    await page.setViewportSize({ width: 400, height: 800 });
    await page.goto("/funding", { waitUntil: "domcontentloaded" });
    await expect(page.locator("form[data-funding-intake]")).toBeVisible({ timeout: PAGE_TIMEOUT });
    // Late web-font swaps and lazy images can widen inline content after
    // first paint — settle both before measuring.
    await page.waitForLoadState("networkidle", { timeout: 3_000 }).catch(() => {});
    await page.evaluate(() => document.fonts.ready).catch(() => {});
    const overflow = await page.evaluate(() => ({
      scrollWidth: document.documentElement.scrollWidth,
      innerWidth: window.innerWidth,
    }));
    expect(overflow.scrollWidth, `scrollWidth ${overflow.scrollWidth} > innerWidth ${overflow.innerWidth}`).toBeLessThanOrEqual(
      overflow.innerWidth,
    );
  });

  test("/funding/report/demo — sample banner, >= 3 grant cards, Gantt, A$3 CTA", async ({
    page,
  }) => {
    test.setTimeout(15_000);
    await page.goto("/funding/report/demo", { waitUntil: "domcontentloaded" });
    await expect(page.getByTestId("demo-report-banner")).toBeVisible({ timeout: PAGE_TIMEOUT });
    await expect(page.getByTestId("demo-report-cta")).toHaveAttribute("href", "/funding?intent=money");
    const cards = page.getByRole("region", { name: /grants, ranked/i }).getByRole("listitem");
    await expect(cards.nth(2)).toBeVisible({ timeout: PAGE_TIMEOUT });
    expect(await cards.count()).toBeGreaterThanOrEqual(3);
    await expect(
      page.getByRole("img", { name: /12-month funding timeline/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
    // Nothing a paid viewer would see.
    await expect(page.getByRole("link", { name: /download pdf/i })).toHaveCount(0);
  });

  test("/docs/unlocks — renders the unlock matrix and the rules table", async ({
    page,
  }) => {
    test.setTimeout(15_000);
    await page.goto("/docs/unlocks", { waitUntil: "domcontentloaded" });
    await expect(page.getByTestId("unlock-matrix-table")).toBeVisible({ timeout: PAGE_TIMEOUT });
    await expect(page.getByTestId("unlock-rules-table")).toBeVisible({ timeout: PAGE_TIMEOUT });
    expect(await page.getByTestId("unlock-matrix-table").getByRole("row").count()).toBeGreaterThan(1);
    expect(await page.getByTestId("unlock-rules-table").getByRole("row").count()).toBeGreaterThan(1);
  });

  test("/compare/chatgpt — renders the BlockID vs ChatGPT comparison table", async ({
    page,
  }) => {
    test.setTimeout(15_000);
    await page.goto("/compare/chatgpt", { waitUntil: "domcontentloaded" });
    const table = page.getByRole("table").first();
    await expect(table).toBeVisible({ timeout: PAGE_TIMEOUT });
    await expect(table.getByRole("columnheader", { name: /^BlockID$/ })).toBeVisible();
    await expect(table.getByRole("columnheader", { name: /^ChatGPT$/ })).toBeVisible();
    expect(await table.getByRole("row").count()).toBeGreaterThan(3);
  });

  test("/solutions/accelerator — pilot offer CTA links the Program trial", async ({
    page,
  }) => {
    test.setTimeout(15_000);
    await page.goto("/solutions/accelerator", { waitUntil: "domcontentloaded" });
    await expect(page.getByTestId("pilot-cta")).toBeVisible({ timeout: PAGE_TIMEOUT });
    const link = page.getByTestId("pilot-cta-link");
    await expect(link).toBeVisible({ timeout: PAGE_TIMEOUT });
    await expect(link).toHaveAttribute("href", /\/signup\?plan=investor_vc_small&trial=1&from=pilot/);
  });
});
