/**
 * Post-deploy hydrated smoke — Playwright.
 *
 * Runs AFTER a successful deploy (curl-based gates already passed) to catch
 * regressions the SSR-only curl grep in scripts/deploy-live.sh can't see:
 * client-side rendered content behind interactive tabs, hydrated widgets,
 * and image responses generated by App Router opengraph-image routes.
 *
 * The 2026-07-23 outage that prompted this file: the Accelerator tab on
 * /pricing swapped its plan matrix client-side (SegmentTabs). The old curl
 * probe fetched HTML that only contained the Founder tab's plans, so a
 * regression that broke the Accelerator surface (missing "Cohort Enterprise")
 * would not have been caught by grep.
 *
 * Constraints:
 *   - Reuses playwright.config.ts baseURL (PLAYWRIGHT_BASE_URL env, defaults
 *     to https://blockid.au via package.json script).
 *   - <10 assertions total, target <60s wall time. Chromium only.
 */

import { test, expect } from "@playwright/test";

// Give each hydrated page a hard ceiling so a stuck deploy doesn't hang CI.
const PAGE_TIMEOUT = 15_000;

test.describe("Post-deploy hydrated smoke", () => {
  test.setTimeout(45_000);

  test("/pricing — Accelerator tab reveals Cohort Enterprise", async ({
    page,
  }) => {
    // iter-17 flake safeguard B: cold Next.js hydration on the very
    // first probe of /pricing after a swap can push the Cohort
    // Enterprise reveal past the 15s PAGE_TIMEOUT ceiling. Double this
    // test's overall budget (still under the 45s file-scope cap) so a
    // slow warm-up doesn't false-fail, while keeping the assertion
    // itself real — anything past 30s IS a regression.
    test.setTimeout(30_000);

    await page.goto("/pricing", { waitUntil: "domcontentloaded" });

    const acceleratorTab = page.getByRole("tab", { name: /accelerator/i });
    await expect(acceleratorTab).toBeVisible({ timeout: PAGE_TIMEOUT });
    await acceleratorTab.click();

    // After hydration + tab switch, the accelerator plan matrix renders.
    // "Cohort Enterprise" is the top accelerator tier (plans-v2.ts).
    // Flake-prone assertion: bumped to 30s per iter-17 flake analysis.
    await expect(page.getByText(/cohort enterprise/i).first()).toBeVisible({
      timeout: 30_000,
    });
  });

  test("/roadmap — Recently landed section renders", async ({ page }) => {
    await page.goto("/roadmap", { waitUntil: "domcontentloaded" });
    await expect(
      page.getByRole("heading", { name: /recently landed/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
  });

  test("/workspace/branding — loads or redirects to /auth/login", async ({
    page,
  }) => {
    const resp = await page.goto("/workspace/branding", {
      waitUntil: "domcontentloaded",
    });
    expect(resp, "no response for /workspace/branding").not.toBeNull();
    const status = resp!.status();
    // Signed-out users are redirected to /auth/login; signed-in reach the page.
    // Both count as healthy; a 4xx/5xx here is the regression we're catching.
    expect([200, 302, 307], `unexpected status ${status}`).toContain(status);
    const finalUrl = page.url();
    const okUrl =
      /\/workspace\/branding($|\?)/.test(finalUrl) ||
      /\/auth\/login($|\?)/.test(finalUrl);
    expect(okUrl, `unexpected final URL ${finalUrl}`).toBe(true);
  });

  // ── /workspace/audit-log + /workspace/projects (iter-12) ────────────
  // Both pages call `redirect("/auth/login?next=...")` inside an async
  // Server Component when getCurrentUser() returns null. Because they
  // sit under app/workspace/loading.tsx, Next 16 streams a shell + the
  // NEXT_REDIRECT template rather than returning a raw 307 to the wire.
  // A `curl -sI` sees HTTP 200 and (incorrectly) flags this as an auth
  // leak — the client runtime honours the template and lands on
  // /auth/login. This hydrated smoke asserts the visible behaviour so
  // the false-positive from the iter-12 curl-only gate can't recur.
  // /dashboard/portfolio (iter-14, shipped 7ed825be) shares the same
  // getCurrentUser()→redirect() auth-gate pattern, so it lives in the
  // same loop.
  for (const path of [
    "/workspace/audit-log",
    "/workspace/projects",
    "/workspace/projects/archived",
    "/dashboard/portfolio",
  ] as const) {
    test(`${path} — anonymous lands on /auth/login (hydrated)`, async ({
      page,
      context,
    }) => {
      await context.clearCookies();
      const resp = await page.goto(path, { waitUntil: "domcontentloaded" });
      expect(resp, `no response for ${path}`).not.toBeNull();
      const status = resp!.status();
      // 200 (streamed shell) or a raw 307/302 both count — regression is 4xx/5xx.
      expect([200, 302, 307], `unexpected status ${status}`).toContain(status);
      // Once hydration processes the NEXT_REDIRECT template the URL must
      // settle on /auth/login (anonymous session).
      await page.waitForURL(/\/auth\/login/, { timeout: PAGE_TIMEOUT });
      // Next.js 16 emits `next=` with the raw path (not percent-encoded), but
      // some intermediate proxies may re-encode `/`. Accept either form so
      // this stays a behavior assertion, not an encoding assertion.
      const encoded = path.replace(/\//g, "%2F");
      expect(page.url()).toMatch(
        new RegExp(`/auth/login.*next=.*(?:${path}|${encoded})`),
      );
    });
  }

  test("/workspace/audit-log — login redirect carries exact next param", async ({
    page,
    context,
  }) => {
    // iter-18 hardening: the loop above accepts either the raw path or a
    // percent-encoded fallback in `next=`. This narrower assertion pins
    // the Next 16 emission shape (raw `/workspace/audit-log`) so a silent
    // change to the redirect helper — e.g. dropping the `next` param or
    // encoding it inconsistently — fails loudly on the audit-log surface
    // that the compliance team relies on for deep-linking back after
    // sign-in. Anonymous only; no auth-fixture needed.
    await context.clearCookies();
    await page.goto("/workspace/audit-log", { waitUntil: "domcontentloaded" });
    await page.waitForURL(/\/auth\/login/, { timeout: PAGE_TIMEOUT });
    const finalUrl = page.url();
    expect(
      finalUrl.includes("next=/workspace/audit-log"),
      `expected exact next=/workspace/audit-log substring, got ${finalUrl}`,
    ).toBe(true);
  });

  test("/dashboard/portfolio — post-redirect login shell hydrates", async ({
    page,
    context,
  }) => {
    // After the auth-gate redirect, the /auth/login page must render its
    // canonical hero shell — protects the empty-state / column layout on
    // /dashboard/portfolio from a silent regression that turns the redirect
    // into a blank page (e.g. a broken WorkspaceLayout import).
    await context.clearCookies();
    await page.goto("/dashboard/portfolio", { waitUntil: "domcontentloaded" });
    await page.waitForURL(/\/auth\/login/, { timeout: PAGE_TIMEOUT });
    await expect(
      page.getByRole("heading", { name: /sign in to blockid/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
  });

  test("/showcase/blockid — opengraph-image returns image/png", async ({
    request,
  }) => {
    const resp = await request.get("/showcase/blockid/opengraph-image");
    expect(resp.status()).toBe(200);
    const ct = resp.headers()["content-type"] ?? "";
    expect(ct.toLowerCase()).toContain("image/png");
  });
});
