/**
 * Post-deploy hydrated smoke — Playwright.
 *
 * Runs AFTER a successful deploy (curl-based gates already passed) to catch
 * regressions the SSR-only curl grep in scripts/deploy-live.sh can't see:
 * client-side rendered content behind interactive tabs, hydrated widgets,
 * and image responses generated by App Router opengraph-image routes.
 *
 * The 2026-07-23 outage that prompted this file: the Accelerator tab on
 * /pricing swapped its plan matrix client-side (SegmentTabs). The old curl
 * probe fetched HTML that only contained the Founder tab's plans, so a
 * regression that broke the Accelerator surface (missing "Cohort Enterprise")
 * would not have been caught by grep.
 *
 * Constraints:
 *   - Reuses playwright.config.ts baseURL (PLAYWRIGHT_BASE_URL env, defaults
 *     to https://blockid.au via package.json script).
 *   - <10 assertions total, target <60s wall time. Chromium only.
 */

import { test, expect } from "@playwright/test";

// Give each hydrated page a hard ceiling so a stuck deploy doesn't hang CI.
const PAGE_TIMEOUT = 15_000;

test.describe("Post-deploy hydrated smoke", () => {
  test.setTimeout(45_000);

  test("/pricing — Accelerator tab reveals Cohort Enterprise", async ({
    page,
  }) => {
    await page.goto("/pricing", { waitUntil: "domcontentloaded" });

    const acceleratorTab = page.getByRole("tab", { name: /accelerator/i });
    await expect(acceleratorTab).toBeVisible({ timeout: PAGE_TIMEOUT });
    await acceleratorTab.click();

    // After hydration + tab switch, the accelerator plan matrix renders.
    // "Cohort Enterprise" is the top accelerator tier (plans-v2.ts).
    await expect(page.getByText(/cohort enterprise/i).first()).toBeVisible({
      timeout: PAGE_TIMEOUT,
    });
  });

  test("/roadmap — Recently landed section renders", async ({ page }) => {
    await page.goto("/roadmap", { waitUntil: "domcontentloaded" });
    await expect(
      page.getByRole("heading", { name: /recently landed/i }),
    ).toBeVisible({ timeout: PAGE_TIMEOUT });
  });

  test("/workspace/branding — loads or redirects to /auth/login", async ({
    page,
  }) => {
    const resp = await page.goto("/workspace/branding", {
      waitUntil: "domcontentloaded",
    });
    expect(resp, "no response for /workspace/branding").not.toBeNull();
    const status = resp!.status();
    // Signed-out users are redirected to /auth/login; signed-in reach the page.
    // Both count as healthy; a 4xx/5xx here is the regression we're catching.
    expect([200, 302, 307], `unexpected status ${status}`).toContain(status);
    const finalUrl = page.url();
    const okUrl =
      /\/workspace\/branding($|\?)/.test(finalUrl) ||
      /\/auth\/login($|\?)/.test(finalUrl);
    expect(okUrl, `unexpected final URL ${finalUrl}`).toBe(true);
  });

  test("/showcase/blockid — opengraph-image returns image/png", async ({
    request,
  }) => {
    const resp = await request.get("/showcase/blockid/opengraph-image");
    expect(resp.status()).toBe(200);
    const ct = resp.headers()["content-type"] ?? "";
    expect(ct.toLowerCase()).toContain("image/png");
  });
});
