// rubric@v1 — MPC (lead CMO): 13 guiding questions + overlays MPC-08/09.
// Benchmarks are percentile bands with a source year, never hard cut-offs.

import type { RubricInput } from "./define";

export const MPC_RUBRIC: readonly RubricInput[] = [
  {
    id: "blockid:question:idea:fc1b2eb085dbce9b", item: "MPC-01",
    question: "What problem does your idea solve?",
    anchors: [
      "Evidence shows the stated problem is not experienced by the named customer (customers deny it or the workflow does not exist).",
      "The problem is described in buzzwords with no customer, situation or consequence.",
      "A specific customer and problem are stated in one clear sentence, founder-stated.",
      "The specific problem is stated clearly and its cost or frequency for the customer is supported by customer evidence or a sourced figure.",
      "The problem statement is specific, quantified from sourced data, and confirmed in the customers' own words (interviews, LOIs, support tickets).",
    ],
    checklist: [
      "Is the customer named specifically (role, segment)?",
      "Is the problem stated in one plain sentence without buzzwords?",
      "Is the cost or frequency of the problem backed by a source or customer evidence?",
    ],
    examples: {
      level2: "\"Small AU builders lose days chasing subcontractor compliance documents.\" No data yet.",
      level4: "Same sentence plus 25 interview notes and an industry survey showing 6 hours a week lost per site manager.",
    },
    evidenceTypes: ["deck", "document", "reference", "public_url"],
    level4Tiers: ["T2", "T3"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "Never N/A: every company must state the problem it solves.",
  },
  {
    id: "blockid:question:idea:e12890bcd2a729a5", item: "MPC-06",
    question: "How is your solution different from existing alternatives?",
    anchors: [
      "Evidence shows an existing alternative already does the same thing at similar or better terms.",
      "Difference is claimed as 'better/faster/easier' with no named alternative.",
      "Named alternatives and a specific difference are described, founder-stated.",
      "The difference is shown against named alternatives with a comparison customers confirm (win/loss notes, switching reasons).",
      "The difference is measurable (cost, time, outcome), confirmed by win/loss records or switching customers, and hard for named rivals to copy.",
    ],
    checklist: [
      "Are the alternatives named (including 'do nothing' or spreadsheets)?",
      "Is the difference specific and measurable?",
      "Do customers confirm the difference (win/loss, switching reasons)?",
    ],
    examples: {
      level2: "\"Unlike Procore we price per project, not per seat.\" No customer evidence.",
      level4: "Win/loss log of 30 deals shows 70% cite per-project pricing; two customers switched from Procore on record.",
    },
    evidenceTypes: ["crm", "document", "deck", "reference"],
    level4Tiers: ["T1", "T2", "T3"],
    notApplicable: "Never N/A: every product has alternatives, including doing nothing.",
  },
  {
    id: "blockid:question:idea:6a184fd6e5509608", item: "MPC-06",
    question: "What is your unique insight or unfair advantage?",
    anchors: [
      "Evidence shows the claimed advantage is common to every competitor or already lost.",
      "An advantage is claimed with no mechanism ('passion', 'execution').",
      "A specific insight or advantage is named with a plausible mechanism, founder-stated.",
      "The advantage is supported by evidence the company holds it (exclusive data, contract, channel, distribution partner).",
      "The advantage is evidenced, exclusive or compounding, and competitors cannot obtain it quickly (signed exclusivity, proprietary data at scale).",
    ],
    checklist: [
      "Is the advantage specific rather than 'execution' or 'passion'?",
      "Is there evidence the company actually holds it?",
      "Would a well-funded rival struggle to get it within a year?",
    ],
    examples: {
      level2: "Founder claims early access to state building-permit data through a pilot programme.",
      level4: "Signed 3-year exclusive data agreement with the state regulator, in the data room.",
    },
    evidenceTypes: ["contract", "document", "deck", "public_url"],
    level4Tiers: ["T1", "T2"],
    notApplicable: "Never N/A.",
  },
  {
    id: "blockid:question:idea:ec82a16208aea1ee", item: "MPC-02",
    question: "Have you validated the idea with potential customers?",
    anchors: [
      "Evidence shows customers were asked and rejected the offer, or no customer was ever contacted.",
      "Validation is claimed with no count, names or method.",
      "Interviews are counted and summarised with notes, founder-stated.",
      "Signed LOIs, pre-orders or pilots from target customers confirm demand.",
      "Paid pilots or pre-payments from several target customers converted, with signed documents or billing records.",
    ],
    checklist: [
      "Were target customers interviewed with notes kept?",
      "Is there a signed LOI, pre-order or pilot?",
      "Has any customer paid?",
    ],
    examples: {
      level2: "22 interview notes with site managers; no commitments yet.",
      level4: "5 paid pilots at A$2k each; invoices paid and 3 converted to annual plans.",
    },
    evidenceTypes: ["contract", "document", "stripe", "xero", "reference"],
    level4Tiers: ["T1", "T2"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "N/A at A/B+ when recurring revenue is verified (TRE-01 carries the evidence instead).",
  },
  {
    id: "blockid:question:market:0b506ec9a327339a", item: "MPC-04",
    question: "What is your Total Addressable Market (TAM)?",
    anchors: [
      "Evidence shows the market figure is wrong by an order of magnitude or measures a different market.",
      "A top-down figure ('1% of a $50B market') is given with no source.",
      "A TAM figure is given with a named source and year, top-down.",
      "TAM is built bottom-up (number of buyers × price) from sourced counts and a real price point.",
      "Bottom-up TAM uses sourced buyer counts and observed prices, reconciles to a dated top-down source, and states its assumptions.",
    ],
    checklist: [
      "Is the figure built bottom-up (buyers × price)?",
      "Are sources named with a year?",
      "Is the price point observed (price list, contracts) rather than assumed?",
    ],
    examples: {
      level2: "\"AU construction software TAM A$1.2B (IBISWorld 2024)\", top-down.",
      level4: "92k AU builders (ABS 2025) × A$1,800 observed ACV = A$166M, cross-checked with IBISWorld 2024.",
    },
    evidenceTypes: ["deck", "financial_model", "public_url", "document"],
    notApplicable: "Never N/A.",
  },
  {
    id: "blockid:question:market:61d61b023e6cda19", item: "MPC-04",
    question: "What is your Serviceable Addressable Market (SAM)?",
    anchors: [
      "Evidence shows the SAM includes segments the product cannot serve (wrong geography, regulation, platform).",
      "SAM is given as a percentage of TAM with no reasoning.",
      "SAM is defined by named segment and geography, founder-stated.",
      "SAM is sized bottom-up for the segments the product serves today, with sources.",
      "Sourced bottom-up SAM matches the segments current customers come from, and the path from SAM to TAM is sequenced.",
    ],
    checklist: [
      "Is the SAM limited to segments the product serves today?",
      "Is it sized from sourced counts?",
      "Do current customers come from the SAM segments?",
    ],
    examples: {
      level2: "SAM = residential builders in NSW and VIC, stated without counts.",
      level4: "18k residential builders in NSW/VIC (ABS 2025) × observed ACV; 90% of current customers are in that segment.",
    },
    evidenceTypes: ["deck", "financial_model", "public_url", "crm"],
    notApplicable: "Never N/A.",
  },
  {
    id: "blockid:question:market:b595fad4fbfe0839", item: "MPC-05",
    question: "Why is now the right time for this market?",
    anchors: [
      "Evidence shows the named catalyst is reversed, delayed or irrelevant to the product.",
      "Timing is claimed with no catalyst ('the market is ready').",
      "A named shift (technology, regulation, behaviour, cost) is described, uncited.",
      "The named shift is dated and cited, and the product depends on it.",
      "A cited, dated shift is shown to change customer behaviour now, with evidence the company is capturing it (demand spike, regulation deadline).",
    ],
    checklist: [
      "Is a specific shift named?",
      "Is the shift cited and dated?",
      "Does the product depend on the shift?",
    ],
    examples: {
      level2: "\"New building-compliance rules are coming.\" No citation.",
      level4: "NCC 2025 amendments (cited, effective 1 May 2025) require digital records; inbound demos tripled since.",
    },
    evidenceTypes: ["public_url", "deck", "document", "analytics"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "N/A at B+ when the category is established and timing is no longer a thesis question.",
  },
  {
    id: "blockid:question:market:d6eae1d178553aef", item: "MPC-06",
    question: "Who are the main competitors?",
    anchors: [
      "The company claims 'no competitors' or omits a well-known direct rival.",
      "Competitors are listed without any comparison.",
      "3–5 named rivals (direct, indirect, do-nothing) with a feature comparison, founder-stated.",
      "Named rivals with a sourced comparison (pricing pages, reviews) and a clear wedge where the company wins.",
      "Named rivals with sourced comparison plus win/loss evidence showing where the company wins and loses, including AU and global players.",
    ],
    checklist: [
      "Are 3–5 rivals named, including indirect ones?",
      "Is the comparison sourced (pricing pages, reviews, filings)?",
      "Is there win/loss evidence?",
    ],
    examples: {
      level2: "Table of Procore, Buildxact and spreadsheets with feature ticks.",
      level4: "Sourced comparison of 5 rivals plus a 40-deal win/loss log by rival.",
    },
    evidenceTypes: ["public_url", "crm", "document", "deck"],
    notApplicable: "Never N/A.",
  },
  {
    id: "blockid:question:website:45a822d8b7528dfa", item: "MPC-07",
    question: "What is your conversion rate?",
    anchors: [
      "Evidence shows conversion is near zero or falling with no diagnosis.",
      "A rate is stated with no funnel definition or period.",
      "A rate is stated with a defined funnel step and period, founder-stated.",
      "The rate is exported from analytics or CRM with funnel steps and period.",
      "Analytics/CRM show the rate by channel over several periods, sitting in or above the dated benchmark band for the model, with tests that moved it.",
    ],
    checklist: [
      "Are the funnel steps defined (visit → signup → paid)?",
      "Is the period stated?",
      "Is the figure exported from analytics or CRM?",
    ],
    examples: {
      level2: "\"3% visitor-to-trial last month.\" No export.",
      level4: "GA4 and Stripe exports show 3.1% visit-to-trial and 22% trial-to-paid over 6 months, by channel.",
    },
    evidenceTypes: ["analytics", "crm", "stripe"],
    level4Tiers: ["T1"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "N/A when there is no live product or sales funnel yet (pre-launch).",
  },
  {
    id: "blockid:question:gtm_strategy:1dbb551dd4a50ae3", item: "MPC-07",
    question: "What are your primary distribution channels?",
    anchors: [
      "Evidence shows all customers came through one founder's personal network with no channel beyond it (at A+ a red flag).",
      "Channels are listed as intentions ('SEO, partnerships, ads') with no results.",
      "Named channels with early results (leads, customers) are given, founder-stated.",
      "CRM or ad accounts attribute customers to named channels with counts.",
      "CRM/ad accounts show at least one channel acquiring customers repeatably over several periods, with cost and cycle per channel.",
    ],
    checklist: [
      "Is each channel named with results, not intentions?",
      "Are customers attributed to channels in CRM or ad accounts?",
      "Has one channel produced customers repeatably over several periods?",
    ],
    examples: {
      level2: "Founder says 60% of customers come from builder-association events.",
      level4: "HubSpot attribution over 4 quarters: events 55%, partner referrals 30%, with cost and cycle per channel.",
    },
    evidenceTypes: ["crm", "analytics", "document"],
    level4Tiers: ["T1"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "N/A at PS when the company has no customers or pilots yet.",
  },
  {
    id: "blockid:question:gtm_strategy:7dcd677e15986fef", item: "MPC-03",
    question: "What is your pricing model?",
    anchors: [
      "Evidence shows the price does not cover delivery cost or no customer has accepted it.",
      "Pricing is 'to be decided' or stated only as 'freemium'.",
      "A pricing model (unit, tiers, price) is published or stated, not yet accepted by paying customers.",
      "Paying customers accept the price, shown in billing records or signed contracts, and the payer versus user is identified.",
      "Billing records show the price holding or rising across cohorts, the pricing unit tracks customer value, and payer and user are distinct and known.",
    ],
    checklist: [
      "Are the pricing unit, tiers and price stated?",
      "Have paying customers accepted this price (billing, contracts)?",
      "Is it clear who pays versus who uses?",
    ],
    examples: {
      level2: "Pricing page: A$99/project/month; no paying customers yet.",
      level4: "Stripe shows 140 customers on per-project plans; average price up 12% after last year's increase with no churn spike.",
    },
    evidenceTypes: ["stripe", "xero", "contract", "public_url"],
    level4Tiers: ["T1", "T2"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "N/A at PS before any price is set (the company is testing willingness to pay under MPC-02).",
  },
  {
    id: "blockid:question:gtm_strategy:6a1c3f59b63f5f02", item: "MPC-07",
    question: "What is your customer acquisition cost (CAC)?",
    anchors: [
      "Evidence shows CAC exceeds the gross profit a customer brings over its observed lifetime.",
      "CAC is stated as a number with no cost base or period.",
      "CAC is calculated with a stated cost base (sales + marketing) and period, founder-stated.",
      "CAC is calculated from ledger spend and CRM new-customer counts for the same period.",
      "Ledger-based CAC is tracked by channel over several periods, with payback in or better than the dated stage benchmark band.",
    ],
    checklist: [
      "Does the cost base include sales salaries and marketing spend?",
      "Are costs and new customers from the same period?",
      "Is it built from ledger and CRM data?",
    ],
    examples: {
      level2: "\"CAC is about A$400\" from ad spend only.",
      level4: "Xero S&M spend ÷ CRM new customers per quarter for 4 quarters, by channel; payback 9 months.",
    },
    evidenceTypes: ["xero", "crm", "analytics", "financial_model"],
    level4Tiers: ["T1"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "N/A while the company has no paid acquisition or sales cost to measure (pre-launch).",
  },
  {
    id: "blockid:question:gtm_strategy:3d8820fc15e09ac4", item: "MPC-07",
    question: "How do you plan to scale customer acquisition?",
    anchors: [
      "Evidence shows the plan relies on a channel that has already failed or is closed to the company.",
      "Scaling is described as 'more marketing' with no channel or budget.",
      "Named channels, budget and targets are planned, not yet tested.",
      "The plan scales channels that already work, with budget, targets and expected payback in the model.",
      "The plan scales proven channels with tested unit economics, adds a tested second channel, and hires/tools are budgeted against targets.",
    ],
    checklist: [
      "Does the plan build on a channel that already produces customers?",
      "Are budget and targets stated?",
      "Has a second channel been tested?",
    ],
    examples: {
      level2: "Plan: hire 2 SDRs and run LinkedIn ads; budget A$120k; untested.",
      level4: "Partner channel proven over 3 quarters; plan doubles partners with modelled payback; LinkedIn pilot gave 11 customers.",
    },
    evidenceTypes: ["financial_model", "crm", "document", "analytics"],
    level4Tiers: ["T1", "T3"],
    stages: ["PS", "S", "A", "B+"],
    notApplicable: "Never N/A.",
  },
  {
    id: "MPC-08",
    anchors: [
      "Evidence shows the market is AU-only by structure (regulation, product) with no stated path beyond it.",
      "International ambition is stated with no market, customer or plan.",
      "A named first international market with a reason and plan is given, no revenue yet.",
      "Revenue or signed pipeline from outside Australia is shown in the ledger or CRM.",
      "A material, growing share of revenue from outside Australia is confirmed by the ledger, across more than one market.",
    ],
    checklist: [
      "Is a first non-AU market named with a reason?",
      "Is there revenue or signed pipeline outside Australia?",
      "Is the geographic split confirmed by ledger or CRM?",
    ],
    examples: {
      level2: "Plan to enter NZ in 2027 because the building code is similar.",
      level4: "Xero shows 28% of revenue from NZ and UK customers, up from 10% a year ago.",
    },
    notApplicable: "N/A when the business is deliberately domestic by nature (e.g. regulated AU-only service) and states so.",
  },
  {
    id: "MPC-09",
    anchors: [
      "Evidence shows one customer is a very large share of revenue with a short or ending contract.",
      "Concentration is not disclosed.",
      "Top-customer share is stated, founder-stated.",
      "Top-customer and top-5 shares come from the receivables ledger and sit within the dated benchmark band.",
      "Ledger shows low and falling concentration over several periods, with the largest contracts on multi-year terms.",
    ],
    checklist: [
      "Is the largest customer's share of revenue disclosed?",
      "Does it come from the ledger?",
      "Are the largest contracts multi-year?",
    ],
    examples: {
      level2: "\"Largest customer is about 20% of revenue.\"",
      level4: "Ledger: top customer 8%, top 5 at 25%, down over 4 quarters; top 3 on 2-year contracts.",
    },
    notApplicable: "N/A before revenue.",
  },
];
