// Account erasure map (S24-B, 2026-09-12; 125th FK `connector_snapshots` added S25-A, 2026-09-13; 126th FK `fundraise_commitments.created_by` added S26-A, 2026-09-13; 127th FK `sector_multiples_overrides.approved_by` added S27-C and 128th FK `secondary_sim_orders.user_id` added S27-B, 2026-09-13; FKs 130–132 `investor_organisations.owner_user_id` / `investor_organisation_members.user_id` / `investor_mandates.owner_user_id` added G13 S-T2 (migration 0393, 2026-09-16 — fixture rows added by hand until 0393 is applied; `--check` reconciles); 133rd FK `program_intakes.owner_user_id` added G14 S35 (migration 0405, 2026-09-16 — fixture row by hand until applied); 134th FK `founder_feedback_letters.founder_user_id` added G14 S34 (migration 0406, 2026-09-17 — fixture row by hand until applied); FKs 135–138 `claims.created_by` / `evidence_records.submitted_by` / `evidence_records.verified_by` / `claim_versions.changed_by` added G21 P1-A (migration 0417, 2026-09-20 — fixture rows by hand until applied); FKs 140–141 `intake_templates.owner_user_id` / `cohort_snapshots.created_by` added G21 P2-A (migration 0422, 2026-09-20 — fixture rows by hand until applied); FKs 142–143 `corrections.submitted_by` / `corrections.resolved_by` added G21 P1-C (migration 0418, applied 2026-09-20 — mapped after the post-ship review found them missing; the union is re-emitted by 0425); FKs 144–147 `assessment_overrides.reviewer_id` / `evaluation_batch_items.reviewer_id` / `evaluation_batch_members.invited_by` (detach) / `evaluation_batch_members.user_id` (delete) added G21 P2-B (migration 0423, applied 2026-09-20 — re-emitted by 0426); FKs 148–149 `startup_outcomes.recorded_by` / `startup_outcomes.confirmed_by` added G21 P3-A (migration 0427, 2026-09-20 — fixture rows by hand until applied; re-emitted by 0429).
//
// `DELETE FROM app_users` is impossible in production: 141 foreign keys
// reference `app_users(id)` (fixture: `__fixtures__/app_users_fks.json`,
// regenerated by `scripts/db/app-users-fk-inventory.mjs --fixture`). Fourteen
// are `NO ACTION`, six `RESTRICT`, and two of the RESTRICT targets
// (`app_user_audit_log`, `reseller_audit_log`) are append-only ledgers whose
// rows can be neither updated nor deleted. Several financial ledgers
// (`credit_transactions`, `usage_logs`, `coupon_redemptions`,
// `referral_events`) carry a NOT NULL user reference and must be kept for
// the 7-year period the Privacy Policy states (clause 4, "Financial
// records"; s262A ITAA 1936, s286 Corporations Act 2001).
//
// So the erasure routine never deletes the `app_users` row. It walks this
// map inside one transaction (`erase_account()` RPC, migration 0348, re-created with the 125-entry map by 0351, the 126-entry map by 0356, the 127-entry maps by 0368/0370 — parallel branches — the merged 128-entry map by 0371, the 129-entry map by 0384–0386, the 132-entry map by 0393, the 133-entry map by 0405, the 134-entry map by 0406, the 138-entry map by 0417, the 139-entry map by 0421 and the 141-entry map by 0425) and
// finally turns the row into a pseudonymous TOMBSTONE — every PII column
// nulled, `email = 'deleted+<hash>@erased.blockid.au'`, `display_name =
// 'Deleted user'`, `erased_at` stamped — which the NOT NULL ledger references
// keep pointing at. The tombstone holds no personal information: the id is a
// random uuid and the hash is of that id, so nothing on the row identifies
// the person (APP 11.2 — "destroy or de-identify").
//
// Every FK in the fixture has exactly one entry here (pinned by
// `erasure-map.test.ts`, which also parses the VALUES list inside the
// migration so SQL and TypeScript cannot drift). Modes:
//
//   delete     the row is the user's own data → removed (cascades follow)
//   anonymise  the row is a ledger / legal record → kept; the user reference
//              is nulled when the column allows it and the row is telemetry
//              (`nullRef`), otherwise it stays on the tombstone; PII columns
//              are scrubbed (`scrub`); append-only ledgers are only counted
//              (`immutable`)
//   detach     the reference is to an actor on someone else's row
//              (referred_by, verified_by, reviewed_by, created_by, …) → NULL
//
// Retention exceptions (documented for the policy's "or on request" rows):
//   • Financial records (7 y): credit_transactions, usage_logs, revenue_events,
//     coupon_redemptions, referral_events, referrals, report_orders,
//     startup_package_purchases, checkout_session_reseller_commissions,
//     reseller_credit_grants, reseller_requests, reseller_attributions,
//     valuation_certificates (issued document), guest_analyses (Stripe ids).
//     Stripe itself keeps the customer + invoices; we cancel subscriptions
//     and detach payment methods but never delete the Stripe customer.
//   • Consent records (life of account + 7 y): consent_events, consents,
//     share_packages, equity_requests.
//   • Append-only security/audit ledgers: app_user_audit_log,
//     reseller_audit_log, audit_events (FK dropped in 0347 — the pseudonymous
//     actor id stays). upload_scans is a malware-scan log (30 d class).
//   • Cap-table / share-issuance records (life of entity + 7 y):
//     esop_option_grants (no FK — keyed by user_id without a constraint) are
//     left untouched on purpose.
//   • Evidence stored in Google Drive (evidence.storage_path is a Drive link)
//     is deleted at the row level only; the Drive object lives in the
//     user's own Drive, not ours.

export type ErasureMode = "delete" | "anonymise" | "detach";

export interface ErasureEntry {
  table: string;
  column: string;
  mode: ErasureMode;
  /**
   * Execution bucket, lower first. 10 = credentials, 15 = detaches,
   * 20 = children that must go before a parent with NO ACTION, 30 = user
   * data, 40 = parents whose cascades fan out, 50 = ledgers.
   */
  order: number;
  /** anonymise: also set the user column to NULL (column must be nullable). */
  nullRef?: boolean;
  /**
   * anonymise / detach: SQL `SET` fragment applied to matching rows.
   * `{anon_email}` is replaced with the tombstone address (quoted literal).
   */
  scrub?: string;
  /** anonymise: append-only ledger — counted, never written. */
  immutable?: boolean;
  note: string;
}

const D = (table: string, column: string, note: string, order = 30): ErasureEntry => ({ table, column, mode: "delete", order, note });
const X = (table: string, column: string, note: string, scrub?: string): ErasureEntry => ({ table, column, mode: "detach", order: 15, note, ...(scrub ? { scrub } : {}) });
const A = (
  table: string,
  column: string,
  note: string,
  extra: { nullRef?: boolean; scrub?: string; immutable?: boolean; order?: number } = {},
): ErasureEntry => ({ table, column, mode: "anonymise", order: extra.order ?? 50, note, ...extra });

/** Tombstone address: deterministic from the user id, contains no PII. */
export function tombstoneEmail(userId: string, hash24: string): string {
  void userId;
  return `deleted+${hash24}@erased.blockid.au`;
}
export const TOMBSTONE_DOMAIN = "erased.blockid.au";
export const TOMBSTONE_NAME = "Deleted user";

export const ERASURE_MAP: readonly ErasureEntry[] = Object.freeze([
  // ── 10 · credentials & integrations: die first so nothing can act as the user mid-transaction
  D("sessions", "user_id", "Login sessions — revoked.", 10),
  D("api_keys", "user_id", "Personal API keys — revoked.", 10),
  D("svi_api_keys", "user_id", "SVI API keys (the Stripe API-tier subscription is cancelled by the Stripe step).", 10),
  D("webhook_endpoints", "user_id", "Outbound webhook endpoints + encrypted secrets — revoked.", 10),
  D("oauth2_tokens", "subject_user_id", "OAuth2 access/refresh tokens issued for the user — revoked.", 10),
  D("password_reset_tokens", "user_id", "Outstanding reset tokens (email column) — removed.", 10),

  // ── 15 · detaches: the user acted on somebody else's row
  X("app_users", "referred_by", "Other users referred by this one keep their account; the pointer is cleared."),
  X("app_users", "verified_by", "Wholesale verifications this admin performed stay; the verifier pointer is cleared."),
  X("claim_versions", "changed_by", "Who filed a correction version on a project's claim (G21 P1-A, 0417) — the version is part of the project's evidence history; the actor pointer is cleared."),
  X("claims", "created_by", "Who first recorded a project's claim (G21 P1-A, 0417) — the claim belongs to the project; the creator pointer is cleared."),
  X("cohort_snapshots", "created_by", "Who took a cohort snapshot (G21 P2-A, 0422) — the snapshot belongs to the batch (cascades with evaluation_batches); the actor pointer is cleared."),
  X("corrections", "submitted_by", "Founder who filed a correction request on a project (G21 P1-C, 0418; mapped by 0425) — the request belongs to the project and its `message` is the founder's own free text about their own startup, not third-party PII, so it is kept; the submitter pointer is cleared."),
  X("corrections", "resolved_by", "Admin who accepted / rejected a correction request (G21 P1-C, 0418; mapped by 0425) — the resolution is part of the project's correction history; the resolver pointer is cleared."),
  X("assessment_overrides", "reviewer_id", "Reviewer who overrode a dimension score inside a BlockID Cohort view (G21 P2-B, 0423) — the override row belongs to the batch item (cascades with it); the reviewer pointer is cleared, the reason code and note stay in the cohort's decision log."),
  X("evaluation_batch_items", "reviewer_id", "Reviewer assigned to a cohort item (G21 P2-B, 0423) — the assignment pointer is cleared."),
  X("evaluation_batch_members", "invited_by", "Who invited a reviewer / viewer to a cohort (G21 P2-B, 0423) — the inviter pointer is cleared."),
  D("evaluation_batch_members", "user_id", "The erased account's own reviewer / viewer seats on other evaluators' cohorts (G21 P2-B, 0423) — deleted; the cohort and its decisions belong to the batch owner."),
  X("equity_requests", "reviewer_id", "Reviewer of other users' equity requests."),
  X("evidence_records", "submitted_by", "Who submitted an evidence record on a project's claim (G21 P1-A, 0417) — the record stays with the project; the submitter pointer is cleared."),
  X("evidence_records", "verified_by", "Reviewer who verified an evidence record (G21 P1-A, 0417) — the verification stays; the verifier pointer is cleared."),
  X("evaluations", "founder_user_id", "Founder who claimed an evaluator's entry: pointer + the founder's email cleared (clause 2C); the evaluator keeps the evaluation.", "founder_email = NULL"),
  X("evidence_versions", "created_by", "Author of a version on a business's evidence."),
  X("fundraise_commitments", "created_by", "Who recorded a cheque on a project's fundraise round (S26-A, 0355) — the round and its commitments belong to the project owner; the recorder pointer is cleared."),
  X("mentor_access_grants", "founder_user_id", "Mentor access granted for this founder — grant row stays with the reseller, founder pointer cleared."),
  X("project_members", "invited_by", "Inviter of other members."),
  X("reseller_credit_grants", "granted_by_user_id", "Reseller admin who granted credits."),
  X("reseller_customers", "stage_set_by", "Reseller admin who set a customer stage."),
  X("reseller_notes", "author_user_id", "Author of reseller CRM notes about a business."),
  X("reseller_requests", "decision_by", "Admin who decided a reseller request."),
  X("revocations", "revoked_by_user_id", "Actor of a share/consent revocation (the revocation itself is a legal record)."),
  X("secondary_offers", "reviewed_by", "Admin reviewer of other users' secondary offers."),
  X("startup_outcomes", "recorded_by", "Who recorded or proposed an outcome on a project (G21 P3-A, 0427) — the observation belongs to the project's longitudinal record and feeds calibration only once confirmed; the recorder pointer is cleared."),
  X("startup_outcomes", "confirmed_by", "Who confirmed / rejected an outcome (G21 P3-A, 0427) — the status stays with the project's record; the reviewer pointer is cleared."),
  X("sector_multiples_overrides", "approved_by", "Admin who approved a cited sector-multiple override (S27-C, 0369) — the override is a platform-wide valuation input, not the admin's data; the approver pointer is cleared, the audit_events row keeps the actor."),
  X("svi_dimension_evidence", "verified_by_user_id", "Verifier of a project's SVI evidence."),

  // ── 20 · children that must go before their NO ACTION parent
  D("compliance_s708_certs", "user_id", "s708 certificates (investor_email, accountant) — before dataroom_files (dataroom_file_id NO ACTION).", 20),
  D("founder_packs", "user_id", "Founder packs — before idea_evaluations / equity_splits / funding_plans (NO ACTION refs).", 20),
  D("dataroom_files", "user_id", "Data-room file index (email, Drive ids, storage_path → purged from the `dataroom` bucket after the transaction) — before user_source_folders.", 20),
  A("valuation_certificates", "user_id", "Issued certificate (certificate_no, content_hash, payload, credits) is a financial + integrity record → kept on the tombstone; score_history_id cleared so startup_score_history can go.", {
    order: 20,
    scrub: "score_history_id = NULL",
  }),

  // ── 30 · the user's own data
  D("ab_assignments", "user_id", "Experiment assignments."),
  D("advisor_client_roster", "advisor_id", "Advisor's client roster (client names)."),
  D("advisor_clients", "advisor_id", "Advisor↔client link (advisor side)."),
  D("advisor_clients", "client_id", "Advisor↔client link (client side)."),
  D("advisor_invites", "advisor_id", "Advisor invitations (advisor_email, invited_email)."),
  D("advisor_notes", "advisor_id", "Advisor's notes."),
  D("advisor_portal", "advisor_id", "Advisor portal rows (founder_name)."),
  D("analyses", "user_id", "SVI analyses claimed by the user (intake, input text, summary_email)."),
  D("analysis_refreshes", "user_id", "Quarterly analysis refreshes."),
  D("assembled_reports", "user_id", "Assembled multi-agent reports (credits ledger keeps the charge)."),
  D("brand_settings", "user_id", "White-label branding."),
  D("competitors", "user_id", "Competitor entries."),
  D("compliance_esic_assessments", "user_id", "ESIC self-assessments."),
  D("compliance_gst_status", "user_id", "GST status checks."),
  D("compliance_modern_slavery_status", "user_id", "Modern-slavery checks."),
  D("compliance_rd_registrations", "user_id", "R&D registrations."),
  D("compliance_tax_invoice_checks", "user_id", "Tax-invoice checks."),
  D("compliance_wgea_status", "user_id", "WGEA checks."),
  D("contact_unlock_requests", "investor_id", "Investor's contact-unlock requests (founder_email)."),
  D("credit_balances", "user_id", "Current balance (the credit_transactions ledger is the record)."),
  D("email_preferences", "user_id", "Email preferences + unsubscribe token (email column)."),
  D("entitlements", "user_id", "Feature entitlements."),
  D("eoi_book", "investor_id", "Expressions of interest the investor lodged (no money moved on-platform)."),
  D("equity_splits", "user_id", "Equity split calculator sessions (founders jsonb)."),
  D("evaluation_batches", "user_id", "Evaluator batches."),
  D("program_intakes", "owner_user_id", "Program intake links the evaluator created (G14 S35) — cascades to intake_submissions."),
  D("intake_templates", "owner_user_id", "Reusable intake templates the evaluator authored (G21 P2-A, 0422: questions, rubric weights, consent text) — deleted; program_intakes.template_id / evaluation_batches.template_id are SET NULL by the FK."),
  D("evaluation_reports", "user_id", "Evaluator reports (credits ledger keeps the charge)."),
  D("evaluations", "evaluator_user_id", "Startups the evaluator entered — life of the evaluator's account (clause 4)."),
  D("evaluator_progress_sends", "user_id", "Evaluator progress email payloads."),
  D("evidence_items", "user_id", "SVI evidence items."),
  D("feedback_submissions", "user_id", "In-app feedback bodies (credits ledger keeps the award)."),
  D("first_principles_sessions", "user_id", "First-principles sessions (email, idea text)."),
  D("founder_feedback_letters", "founder_user_id", "'What investors said' letters addressed to the founder (G14 S34, 0406: anonymised k-aggregate + rendered markdown) — deleted; evaluation_assessments.feedback_letter_id is SET NULL by the FK."),
  D("founder_profiles", "account_id", "Founder profile (full_name, linkedin_url, bio, co-founders, advisors)."),
  D("funding_matches", "user_id", "Founder Radar matches."),
  D("funding_plans", "user_id", "Funding plans."),
  D("funding_reports", "user_id", "Member Money Finder reports — life of the account (clause 4); Stripe-paid ones keep their Stripe record in Stripe + revenue_events."),
  D("grant_application_drafts", "user_id", "Grant application drafts."),
  D("gtm_strategies", "user_id", "GTM strategies."),
  D("idea_evaluations", "user_id", "Idea evaluations."),
  D("investor_links", "founder_user_id", "Investor share links (investor_email, investor_name, created_by_email)."),
  D("investor_mandates", "owner_user_id", "Investment mandates the user authored (G13 S-T2, 0393: thesis, cheque range, floors) — deleted; mandate_fit_scores cascade."),
  D("investor_organisation_members", "user_id", "Seat memberships in investor organisations (0393) — removed; the organisation stays with its other seats."),
  D("investor_organisations", "owner_user_id", "The user's personal investor organisation (0393, is_personal) — deleted; members, mandates and fit scores cascade. Shared Firm/Program orgs are not created by the app yet (seats ship in S-D3); when they are, ownership must be transferred first (409 like shared projects)."),
  D("investor_portfolio", "investor_user_id", "Investor portfolio (notes)."),
  D("lifecycle_state", "user_id", "Lifecycle mailer state."),
  D("mentor_check_ins", "founder_user_id", "Founder's weekly check-ins (wins / blockers)."),
  D("mentor_engagement_snapshots", "founder_user_id", "Founder engagement snapshots."),
  D("mentor_notes", "founder_user_id", "Mentor notes ABOUT this founder — personal information about the individual → removed."),
  D("notifications", "user_id", "In-app notifications."),
  D("nurture_email_queue", "user_id", "Nurture email queue."),
  D("pitchdeck_analyses", "user_id", "Pitch-deck analyses (extracted text, storage_url)."),
  D("positioning_statements", "user_id", "Positioning statements."),
  D("pricing_tiers", "user_id", "Pricing tier drafts."),
  D("project_members", "user_id", "Memberships of other people's projects (user_email) — removed; the projects stay."),
  D("published_analyses", "user_id", "Public startup profile listing."),
  D("roadmap_milestones", "user_id", "Roadmap milestones."),
  D("secondary_offers", "account_id", "Secondary-sale offers the user listed (EOIs cascade)."),
  D("secondary_sim_orders", "user_id", "Sandbox order-book orders the user placed (S27-B, 0366) — a simulation, no securities; the trades tape keeps its labels with the order refs SET NULL."),
  D("startup_listings", "startup_id", "Public index listing."),
  D("startup_package_interview", "user_id", "Startup Package interview answers."),
  D("startup_score_history", "user_id", "SVI score history (inputs, startup_name)."),
  D("subscription_trial_state", "user_id", "Trial state (Stripe keeps the subscription record)."),
  D("svi_readiness_snapshots", "user_id", "Readiness snapshots."),
  D("fundraise_rounds", "account_id", "Fundraise rounds — FK repointed from svi_accounts to app_users by 0384 (live QA 2026-09-13: the 0043 FK made every insert fail); commitments cascade."),
  D("connector_snapshots", "user_id", "Stripe/Xero connector metric snapshots (MRR, customers, bank balance) — user data (S25-A, 0349)."),
  D("tech_analyses", "user_id", "Tech analyses (website / GitHub signals)."),
  D("transfer_whitelist", "user_id", "Wallet whitelist (wallet_address)."),
  D("user_source_folders", "user_id", "Drive source folders (email, folder ids) — after dataroom_files."),
  D("watchlist", "account_id", "Watchlist (notes)."),
  D("watchlist_digest", "account_id", "Watchlist digests."),

  // ── 40 · parents whose cascades fan out (project-scoped tables, data-room documents, evidence vault)
  D("projects", "user_id", "Owned projects — cascades to every project-scoped table; NO ACTION children are detached first (PROJECT_DETACHES). Shared projects block self-service deletion (409) until transferred or archived.", 40),
  D("data_rooms", "user_id", "Data rooms — documents, views, engagement and NDA acceptances cascade (NDA tail is the room's own policy, clause 4).", 40),
  D("evidence", "owner_user_id", "Evidence vault rows (sha256, Drive link); versions cascade.", 40),

  // ── 50 · ledgers and legal records: kept on the tombstone (or with the ref nulled when telemetry)
  A("ai_runs", "user_id", "AI cost ledger (tokens, cost_usd) — pseudonymised.", { nullRef: true }),
  A("analytics_events", "user_id", "Product analytics — pseudonymised.", { nullRef: true }),
  A("churn_events", "user_id", "Churn telemetry (exit survey is product data) — pseudonymised.", { nullRef: true }),
  A("conversion_events", "user_id", "Conversion telemetry — pseudonymised.", { nullRef: true }),
  A("pricing_experiment_events", "user_id", "Pricing experiment telemetry — pseudonymised.", { nullRef: true }),
  A("onchain_documents", "user_id", "Blockchain-anchored document hashes are immutable on-chain — row kept, ref nulled.", { nullRef: true }),
  A("guest_analyses", "user_id", "A$3 guest analysis claimed by the user: Stripe ids + amount are a financial record (7 y); email pseudonymised, ref nulled.", {
    nullRef: true,
    scrub: "email = {anon_email}",
  }),
  A("user_feedback", "user_id", "Legacy feedback — correspondence (3 y); email removed, ref nulled.", { nullRef: true, scrub: "email = NULL" }),
  A("app_user_audit_log", "user_id", "Append-only user-action ledger (RESTRICT, no UPDATE/DELETE) — counted only.", { immutable: true }),
  A("reseller_audit_log", "actor_user_id", "Append-only reseller ledger (RESTRICT) — counted only.", { immutable: true }),
  A("reseller_audit_log", "subject_user_id", "Append-only reseller ledger (RESTRICT) — counted only.", { immutable: true }),
  A("checkout_session_reseller_commissions", "founder_id", "Reseller commission ledger — financial record, 7 y."),
  A("consent_events", "user_id", "Consent / disclaimer acknowledgements — life of account + 7 y; network address and browser string scrubbed.", {
    scrub: "ip_address = NULL, user_agent = NULL",
  }),
  A("consents", "grantor_user_id", "Data-sharing consents (legal basis for share packages) — kept."),
  A("coupon_redemptions", "user_id", "Coupon redemption ledger — financial record."),
  A("credit_transactions", "user_id", "Credit ledger — financial record, 7 y."),
  A("equity_requests", "user_id", "Equity request lifecycle (consent-linked legal record) — kept."),
  A("mentor_access_grants", "granted_by", "Grantor of mentor access on a reseller's grant row (NOT NULL) — stays on the tombstone."),
  A("mentor_check_ins", "mentor_id", "Mentor on a founder's check-in (NOT NULL) — the founder keeps their check-ins."),
  A("mentor_notes", "mentor_id", "Author of notes a founder may have been shown (NOT NULL) — the founder's copy stays."),
  A("referral_events", "referred_id", "Referral credit ledger — financial record."),
  A("referral_events", "referrer_id", "Referral credit ledger — financial record."),
  A("referrals", "referrer_id", "Referral ledger — referrer's email pseudonymised; the referee's stays theirs.", { scrub: "referrer_email = {anon_email}" }),
  A("report_orders", "user_id", "Paid report orders (Stripe session / payment intent) — financial record."),
  A("pilot_orders", "user_id", "Paid Cohort Validation Pilot orders (Stripe session / payment intent, 0416) — financial record, 7 y; buyer e-mail pseudonymised.", { scrub: "buyer_email = {anon_email}" }),
  A("reseller_admins", "user_id", "Reseller admin seat (RESTRICT) — revoked, kept for the reseller's audit trail.", {
    scrub: "status = 'revoked', revoked_at = coalesce(revoked_at, now())",
  }),
  A("reseller_attributions", "subject_user_id", "Reseller attribution (commission basis, RESTRICT) — kept on the tombstone."),
  A("reseller_credit_grants", "target_user_id", "Reseller credit grants — financial record."),
  A("reseller_requests", "requested_by", "Reseller requests linked to credit transactions (RESTRICT) — kept."),
  A("revenue_events", "user_id", "Revenue ledger — financial record, 7 y."),
  A("share_packages", "owner_user_id", "Investor share packages are consent-linked records — kept; the shared evidence itself is deleted."),
  A("startup_package_purchases", "user_id", "Startup Package purchase (Stripe session) — financial record."),
  A("upload_scans", "user_id", "Malware-scan log (security log class) — kept."),
  A("usage_logs", "user_id", "Credit usage ledger — financial record."),
  // reseller_customers: the reseller's CRM record about this customer — removed (stage notes are about the person)
  D("reseller_customers", "customer_user_id", "Reseller CRM record about this customer (stage_note) — removed; the commission ledger keeps the money trail.", 30),
]);

/**
 * Children that are NOT `ON DELETE CASCADE` of a parent the run deletes —
 * they would block the parent's DELETE (NO ACTION / RESTRICT). Their pointer
 * is nulled for the user's rows before the `projects` step runs.
 *
 *   parent "projects"      → `col IN (SELECT id FROM projects WHERE user_id = <uid>)`
 *   parent "svi_accounts"  → legacy SVI accounts cascade from projects
 *                            (svi_accounts.project_id CASCADE) and are also
 *                            keyed by the user's email; their own NO ACTION
 *                            children are detached the same way.
 *
 * Rows on other users' parents are untouched.
 */
export interface ProjectDetach {
  table: string;
  column: string;
  parent: "projects" | "svi_accounts";
  note: string;
}
export const PROJECT_DETACHES: readonly ProjectDetach[] = Object.freeze([
  { table: "reseller_attributions", column: "subject_project_id", parent: "projects", note: "RESTRICT — attribution row (commission basis) kept, project pointer cleared." },
  { table: "credit_transactions", column: "project_id", parent: "projects", note: "NO ACTION — ledger kept, project pointer cleared." },
  { table: "usage_logs", column: "project_id", parent: "projects", note: "NO ACTION — ledger kept, project pointer cleared." },
  { table: "ai_runs", column: "business_id", parent: "projects", note: "NO ACTION — AI cost ledger kept." },
  { table: "reseller_credit_grants", column: "sandbox_project_id", parent: "projects", note: "NO ACTION — grant ledger kept." },
  { table: "advisor_client_roster", column: "project_id", parent: "projects", note: "NO ACTION — another advisor's roster row keeps its client name, project pointer cleared." },
  { table: "data_rooms", column: "project_id", parent: "projects", note: "NO ACTION — the user's own rooms are deleted in the same run; a room another owner attached to this project is detached." },
  { table: "funding_reports", column: "project_id", parent: "projects", note: "NO ACTION — guest / other users' reports attached to this project are detached." },
  { table: "pitchdeck_analyses", column: "project_id", parent: "projects", note: "NO ACTION — other users' analyses on this project are detached." },
  { table: "user_actions", column: "account_id", parent: "svi_accounts", note: "NO ACTION child of the legacy svi_accounts row that cascades from projects — legacy action log kept (email pseudonymised in NON_FK_EXTRAS), pointer cleared." },
  { table: "cohort_members", column: "svi_account_id", parent: "svi_accounts", note: "NO ACTION child of svi_accounts — cohort membership row kept, pointer cleared." },
]);

/**
 * Tables that hold the user's email or id WITHOUT a foreign key (legacy or
 * intentionally unconstrained). `by: "email"` rows match the pre-erasure
 * email address; `by: "user_id"` rows match the id.
 */
export interface ExtraEntry {
  table: string;
  column: string;
  /**
   * How the column is matched: the user's email, their app_users id, or
   * `account` — a legacy `account_id` column that holds EITHER the app_users
   * id (rows written since the S17/S18 scope work) OR a legacy svi_accounts
   * id (rows from the 2026-06/07 cap-table era). The RPC matches both
   * (`col = p_user_id OR col IN (owner's svi_accounts)`).
   */
  by: "email" | "user_id" | "account";
  mode: "delete" | "anonymise";
  scrub?: string;
  note: string;
}
export const NON_FK_EXTRAS: readonly ExtraEntry[] = Object.freeze([
  { table: "magic_links", column: "email", by: "email", mode: "delete", note: "Outstanding magic-link tokens for the address." },
  { table: "email_drips", column: "email", by: "email", mode: "delete", note: "Radar / onboarding drips (90 d class) — removed now." },
  { table: "oauth_connections", column: "user_email", by: "email", mode: "delete", note: "Legacy OAuth connections keyed by email (provider tokens)." },
  { table: "oauth_connections_v2", column: "user_id", by: "user_id", mode: "delete", note: "OAuth connections (provider tokens)." },
  { table: "founder_notifications", column: "user_id", by: "user_id", mode: "delete", note: "Founder notifications." },
  { table: "founder_digest_sends", column: "user_id", by: "user_id", mode: "delete", note: "Weekly digest send log." },
  { table: "svi_action_plans", column: "user_id", by: "user_id", mode: "delete", note: "SVI action plans." },
  { table: "analyzer_runs", column: "user_id", by: "user_id", mode: "delete", note: "Analyzer runs." },
  { table: "financial_models", column: "user_id", by: "user_id", mode: "delete", note: "Financial models." },
  { table: "equity_plans", column: "user_id", by: "user_id", mode: "delete", note: "Equity plans." },
  { table: "investor_pack_shares", column: "user_id", by: "user_id", mode: "delete", note: "Investor pack share links." },
  { table: "report_sections", column: "user_id", by: "user_id", mode: "delete", note: "Report sections." },
  { table: "svi_deck_cache", column: "user_id", by: "user_id", mode: "delete", note: "Cached deck extractions." },
  { table: "svi_signals", column: "user_id", by: "user_id", mode: "delete", note: "SVI signals." },
  // Cap table + dividend register (live QA 2026-09-13, lane 2 P1-2): keyed on
  // `account_id` with NO foreign key — mixed app_users / svi_accounts ids —
  // so neither the FK walk nor the project cascade reached them and a
  // third party's name + email survived erasure. Dependency order: share
  // transactions reference shareholders and share classes with NO ACTION.
  { table: "dividend_records", column: "account_id", by: "account", mode: "delete", note: "Dividend declarations (payout names) — statements/DRIP cascade from them." },
  { table: "share_transactions", column: "account_id", by: "account", mode: "delete", note: "Share register movements — NO ACTION FKs to shareholders/share_classes, so removed first." },
  { table: "shareholders", column: "account_id", by: "account", mode: "delete", note: "Cap-table holders (third-party name + email) — drip_elections cascade, statements SET NULL." },
  { table: "share_classes", column: "account_id", by: "account", mode: "delete", note: "Share classes of the founder's register." },
  { table: "user_insights", column: "user_id", by: "user_id", mode: "delete", note: "Generated insights." },
  { table: "data_room_checklist", column: "user_id", by: "user_id", mode: "delete", note: "Data-room checklist state." },
  { table: "term_sheet_analyses", column: "user_id", by: "user_id", mode: "delete", note: "Term-sheet analyses (email column)." },
  { table: "nps_responses", column: "email", by: "email", mode: "anonymise", scrub: "email = NULL, user_email = NULL, user_id = NULL", note: "NPS scores are product telemetry — identifiers removed." },
  { table: "leads", column: "email", by: "email", mode: "anonymise", scrub: "email = {anon_email}", note: "Lead capture rows — address pseudonymised." },
  // G14 S35 (0405): a founder's application into an evaluator's intake link
  // is the evaluator's record (like evaluations.founder_email) — the row
  // stays, the founder's address + name are pseudonymised.
  { table: "intake_submissions", column: "founder_email", by: "email", mode: "anonymise", scrub: "founder_email = {anon_email}, founder_name = NULL", note: "Program-intake applications keyed by the founder's email — pseudonymised, the evaluator keeps the scored row." },
  { table: "user_actions", column: "email", by: "email", mode: "anonymise", scrub: "email = {anon_email}", note: "Legacy action log keyed by email — pseudonymised." },
  { table: "svi_accounts", column: "email", by: "email", mode: "anonymise", scrub: "email = {anon_email}", note: "Legacy SVI account keyed by email — pseudonymised (svi_* children key on its id)." },
  // G25-C (0438): the free-allowance ledger is keyed by the address, no FK.
  // Removed outright — the row is the person's own record (which free
  // reports they took, where they went); the aggregate counts on
  // /admin/funnel are telemetry we can afford to lose for one person.
  { table: "free_report_grants", column: "email", by: "email", mode: "delete", note: "Free-report grants keyed by the address (email, email_hash, ip_hash) — removed." },
]);

/**
 * `app_users` columns nulled on the tombstone (everything that is or could
 * hold personal information or a credential). Set in the RPC's final step
 * together with email / display_name / erased_at.
 */
export const TOMBSTONE_NULL_COLUMNS: readonly string[] = Object.freeze([
  "google_id",
  "avatar_url",
  "stripe_customer_id",
  "password_hash",
  "coupon_code",
  "cancel_reason",
  "referral_code",
  "startup_name",
  "startup_stage",
  "industry",
  "startup_goals",
  "investor_firm",
  "investor_url",
  "custom_role",
  "calendar_token",
  "investor_prefs",
  "dashboard_layout",
  "onboarding_state",
  "jurisdiction",
  "jurisdiction_source",
  "segment",
  "deletion_reason",
  "deletion_cancel_token_hash",
  "deletion_reauth_token_hash",
  "deletion_reauth_expires_at",
  "deletion_requested_at",
]);

export function entryKey(e: { table: string; column: string }): string {
  return `${e.table}.${e.column}`;
}

export interface ErasureMapSummary {
  entries: number;
  tables: number;
  delete: number;
  anonymise: number;
  detach: number;
  immutable: number;
  project_detaches: number;
  non_fk_extras: number;
}

export function summariseErasureMap(map: readonly ErasureEntry[] = ERASURE_MAP): ErasureMapSummary {
  const s: ErasureMapSummary = {
    entries: map.length,
    tables: new Set(map.map((e) => e.table)).size,
    delete: 0,
    anonymise: 0,
    detach: 0,
    immutable: 0,
    project_detaches: PROJECT_DETACHES.length,
    non_fk_extras: NON_FK_EXTRAS.length,
  };
  for (const e of map) {
    s[e.mode]++;
    if (e.immutable) s.immutable++;
  }
  return s;
}

/** Entries in the order the RPC executes them (stable: order, table, column). */
export function orderedEntries(map: readonly ErasureEntry[] = ERASURE_MAP): ErasureEntry[] {
  return [...map].sort((a, b) => a.order - b.order || a.table.localeCompare(b.table) || a.column.localeCompare(b.column));
}
