// DOCX generator for SVI Enhanced Reports.
//
// Converts an AssembledReport into a professional Word document with
// branded styling, section-level structure, optional embedded images,
// and legal disclaimers in the footer.

import "server-only";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  ImageRun,
  Header,
  Footer,
  PageNumber,
  AlignmentType,
  BorderStyle,
  ShadingType,
} from "docx";
import type { AssembledReport } from "@/lib/report-pipeline/types";

// ── Brand Constants ───────────────────────────────────────────────────────────

const BRAND_BLUE = "2563EB";
const BRAND_DARK = "1E293B";
const BRAND_GRAY = "64748B";
const BRAND_LIGHT = "F8FAFC";
const FONT_HEADING = "Calibri";
const FONT_BODY = "Calibri";

// ── Main Export ───────────────────────────────────────────────────────────────

export async function generateSVIDocx(
  report: AssembledReport,
  images?: Map<string, { base64: string; mimeType: string }>,
): Promise<Buffer> {
  const children: Paragraph[] = [];

  // ── Cover Page ──────────────────────────────────────────────────────────
  children.push(...buildCoverPage(report));

  // ── Table of Contents (manual) ──────────────────────────────────────────
  children.push(
    new Paragraph({ pageBreakBefore: true }),
    new Paragraph({
      text: "Table of Contents",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 300 },
      run: { font: FONT_HEADING, color: BRAND_BLUE },
    }),
  );

  for (let i = 0; i < report.sections.length; i++) {
    const section = report.sections[i];
    const scoreText = section.score !== undefined ? `  (${section.score}/100)` : "";
    children.push(
      new Paragraph({
        spacing: { after: 80 },
        children: [
          new TextRun({
            text: `${i + 1}. ${section.title}${scoreText}`,
            font: FONT_BODY,
            size: 22,
            color: BRAND_DARK,
          }),
          new TextRun({
            text: `   ............   p.${i + 3}`,
            font: FONT_BODY,
            size: 20,
            color: BRAND_GRAY,
          }),
        ],
      }),
    );
  }

  // ── Executive Summary (dedicated page) ──────────────────────────────────
  if (report.executiveSummary) {
    children.push(new Paragraph({ pageBreakBefore: true }));
    children.push(
      new Paragraph({
        text: "Executive Summary",
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 200 },
        run: { font: FONT_HEADING, color: BRAND_BLUE },
      }),
    );
    children.push(...markdownToParagraphs(report.executiveSummary));
  }

  // ── Report Sections ─────────────────────────────────────────────────────
  for (const section of report.sections) {
    if (section.id === "executive") continue; // already rendered above

    children.push(new Paragraph({ pageBreakBefore: true }));

    // Section heading
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 100 },
        run: { font: FONT_HEADING, color: BRAND_BLUE },
      }),
    );

    // Score badge
    if (section.score !== undefined) {
      children.push(buildScoreBadge(section.score, section.agentRole));
    }

    // Section content (markdown → paragraphs)
    children.push(...markdownToParagraphs(section.content));

    // Embedded image if available
    const imageData = images?.get(section.id);
    if (imageData) {
      try {
        children.push(buildImageParagraph(imageData.base64, imageData.mimeType));
      } catch (err) {
        console.warn(`[docx] Failed to embed image for section ${section.id}:`, err);
      }
    }
  }

  // ── Quality Score Summary ───────────────────────────────────────────────
  children.push(new Paragraph({ pageBreakBefore: true }));
  children.push(
    new Paragraph({
      text: "Report Quality Summary",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
      run: { font: FONT_HEADING, color: BRAND_BLUE },
    }),
  );
  children.push(buildQualitySummary(report));

  // ── Disclaimer ──────────────────────────────────────────────────────────
  children.push(
    new Paragraph({ spacing: { before: 400 } }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Disclaimer: ",
          bold: true,
          font: FONT_BODY,
          size: 18,
          color: BRAND_GRAY,
        }),
        new TextRun({
          text: "This report is generated by BlockID.au using AI-powered analysis. It is for informational purposes only and does not constitute financial, legal, or investment advice. All data is based on user-submitted evidence and publicly available information. Auschain PTY LTD (ACN 659 615 111) accepts no liability for decisions made based on this report.",
          font: FONT_BODY,
          size: 18,
          color: BRAND_GRAY,
          italics: true,
        }),
      ],
    }),
  );

  // ── Build Document ──────────────────────────────────────────────────────
  const doc = new Document({
    styles: {
      paragraphStyles: [
        {
          id: "Normal",
          name: "Normal",
          run: {
            font: FONT_BODY,
            size: 22, // 11pt
            color: BRAND_DARK,
          },
          paragraph: {
            spacing: { after: 120, line: 276 },
          },
        },
        {
          id: "Heading1",
          name: "heading 1",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: FONT_HEADING,
            size: 32, // 16pt
            bold: true,
            color: BRAND_BLUE,
          },
          paragraph: {
            spacing: { before: 240, after: 120 },
          },
        },
        {
          id: "Heading2",
          name: "heading 2",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: FONT_HEADING,
            size: 28, // 14pt
            bold: true,
            color: BRAND_DARK,
          },
          paragraph: {
            spacing: { before: 200, after: 80 },
          },
        },
        {
          id: "Heading3",
          name: "heading 3",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: FONT_HEADING,
            size: 24, // 12pt
            bold: true,
            color: BRAND_DARK,
          },
          paragraph: {
            spacing: { before: 160, after: 60 },
          },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,    // 1 inch
              bottom: 1440,
              left: 1440,
              right: 1440,
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "BlockID.au",
                    font: FONT_HEADING,
                    size: 16,
                    color: BRAND_BLUE,
                    bold: true,
                  }),
                  new TextRun({
                    text: `  |  ${report.title}`,
                    font: FONT_BODY,
                    size: 16,
                    color: BRAND_GRAY,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "Generated by BlockID.au — Not financial advice",
                    font: FONT_BODY,
                    size: 16,
                    color: BRAND_GRAY,
                    italics: true,
                  }),
                  new TextRun({
                    text: "    |    Page ",
                    font: FONT_BODY,
                    size: 16,
                    color: BRAND_GRAY,
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    font: FONT_BODY,
                    size: 16,
                    color: BRAND_GRAY,
                  }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

// ── Cover Page Builder ────────────────────────────────────────────────────────

function buildCoverPage(report: AssembledReport): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  // Spacer
  paragraphs.push(new Paragraph({ spacing: { before: 2400 } }));

  // Logo placeholder
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "BLOCKID.AU",
          font: FONT_HEADING,
          size: 52,
          bold: true,
          color: BRAND_BLUE,
        }),
      ],
    }),
  );

  // Subtitle
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: "Startup Value Index — Enhanced Report",
          font: FONT_BODY,
          size: 24,
          color: BRAND_GRAY,
        }),
      ],
    }),
  );

  // Horizontal line
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400, after: 400 },
      border: {
        bottom: { color: BRAND_BLUE, size: 3, style: BorderStyle.SINGLE, space: 1 },
      },
    }),
  );

  // Report title
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: report.title,
          font: FONT_HEADING,
          size: 36,
          bold: true,
          color: BRAND_DARK,
        }),
      ],
    }),
  );

  // Tier badge
  const tierLabels: Record<string, string> = {
    standard: "Standard Report",
    premium: "Premium Report",
    investor_memo: "Investor Memo",
  };
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: tierLabels[report.tier] ?? "Report",
          font: FONT_BODY,
          size: 24,
          color: BRAND_BLUE,
          bold: true,
        }),
      ],
    }),
  );

  // SVI Score
  const sviScoreText = report.sections.find((s) => s.score !== undefined)?.score;
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: `Quality Score: ${report.qualityScore}/100`,
          font: FONT_BODY,
          size: 28,
          bold: true,
          color: BRAND_DARK,
        }),
      ],
    }),
  );

  // Word count
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: `${report.totalWords.toLocaleString()} words  |  ${report.sections.length} sections`,
          font: FONT_BODY,
          size: 22,
          color: BRAND_GRAY,
        }),
      ],
    }),
  );

  // Date
  const reportDate = new Date(report.createdAt).toLocaleDateString("en-AU", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 },
      children: [
        new TextRun({
          text: reportDate,
          font: FONT_BODY,
          size: 22,
          color: BRAND_GRAY,
        }),
      ],
    }),
  );

  // Company
  paragraphs.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 800 },
      children: [
        new TextRun({
          text: "Auschain PTY LTD  |  ACN 659 615 111",
          font: FONT_BODY,
          size: 18,
          color: BRAND_GRAY,
        }),
      ],
    }),
  );

  return paragraphs;
}

// ── Score Badge ───────────────────────────────────────────────────────────────

function buildScoreBadge(score: number, agentRole: string): Paragraph {
  const scoreColor = score >= 70 ? "10B981" : score >= 40 ? "F59E0B" : "EF4444";
  const roleLabel = agentRole.toUpperCase();

  return new Paragraph({
    spacing: { after: 200 },
    children: [
      new TextRun({
        text: `Score: ${score}/100`,
        font: FONT_BODY,
        size: 22,
        bold: true,
        color: scoreColor,
      }),
      new TextRun({
        text: `    Analyst: ${roleLabel}`,
        font: FONT_BODY,
        size: 20,
        color: BRAND_GRAY,
      }),
    ],
  });
}

// ── Image Embedding ───────────────────────────────────────────────────────────

function buildImageParagraph(base64Data: string, mimeType: string): Paragraph {
  const imageBuffer = Buffer.from(base64Data, "base64");

  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 200, after: 200 },
    children: [
      new ImageRun({
        data: imageBuffer,
        transformation: {
          width: 580,
          height: 400,
        },
        type: mimeType === "image/png" ? "png" : mimeType === "image/jpeg" ? "jpg" : "png",
      }),
    ],
  });
}

// ── Quality Summary Table ─────────────────────────────────────────────────────

function buildQualitySummary(report: AssembledReport): Paragraph {
  const lines: string[] = [
    `Overall Quality Score: ${report.qualityScore}/100`,
    `Total Word Count: ${report.totalWords.toLocaleString()}`,
    `Sections: ${report.sections.length}`,
    `Tier: ${report.tier}`,
    `Consistency Issues: ${report.consistencyIssues.length}`,
  ];

  // Agent contributions summary
  const agentSummary = Object.entries(report.agentContributions)
    .filter(([, v]) => v.wordCount > 0)
    .map(([role, v]) => `${role.toUpperCase()}: ${v.wordCount} words (${v.criteria.length} criteria)`)
    .join(", ");

  if (agentSummary) {
    lines.push(`Agent Contributions: ${agentSummary}`);
  }

  return new Paragraph({
    spacing: { after: 200 },
    children: lines.map(
      (line, i) =>
        new TextRun({
          text: (i > 0 ? "\n" : "") + line,
          font: FONT_BODY,
          size: 22,
          color: BRAND_DARK,
          break: i > 0 ? 1 : undefined,
        }),
    ),
  });
}

// ── Markdown → DOCX Paragraph Converter ───────────────────────────────────────

function markdownToParagraphs(markdown: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const lines = markdown.split("\n");

  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    // Empty line → skip
    if (trimmed === "") {
      i++;
      continue;
    }

    // Horizontal rule or page break
    if (/^---+$/.test(trimmed) || /^\*\*\*+$/.test(trimmed)) {
      paragraphs.push(
        new Paragraph({
          border: {
            bottom: { color: BRAND_GRAY, size: 1, style: BorderStyle.SINGLE, space: 4 },
          },
          spacing: { before: 200, after: 200 },
        }),
      );
      i++;
      continue;
    }

    // Heading 3
    if (trimmed.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.slice(4),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 160, after: 60 },
          run: { font: FONT_HEADING, color: BRAND_DARK },
        }),
      );
      i++;
      continue;
    }

    // Heading 2
    if (trimmed.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.slice(3),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 80 },
          run: { font: FONT_HEADING, color: BRAND_DARK },
        }),
      );
      i++;
      continue;
    }

    // Heading 1
    if (trimmed.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.slice(2),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 240, after: 120 },
          run: { font: FONT_HEADING, color: BRAND_BLUE },
        }),
      );
      i++;
      continue;
    }

    // Blockquote
    if (trimmed.startsWith("> ")) {
      const quoteText = trimmed.slice(2);
      paragraphs.push(
        new Paragraph({
          indent: { left: 720 },
          spacing: { before: 100, after: 100 },
          border: {
            left: { color: BRAND_BLUE, size: 3, style: BorderStyle.SINGLE, space: 8 },
          },
          children: parseInlineFormatting(quoteText),
        }),
      );
      i++;
      continue;
    }

    // Unordered list item
    if (/^[-*+]\s/.test(trimmed)) {
      const listText = trimmed.replace(/^[-*+]\s+/, "");
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 60 },
          children: parseInlineFormatting(listText),
        }),
      );
      i++;
      continue;
    }

    // Nested list (2+ spaces or tab prefix)
    if (/^\s{2,}[-*+]\s/.test(line)) {
      const listText = trimmed.replace(/^[-*+]\s+/, "");
      paragraphs.push(
        new Paragraph({
          bullet: { level: 1 },
          spacing: { after: 40 },
          children: parseInlineFormatting(listText),
        }),
      );
      i++;
      continue;
    }

    // Ordered list item
    if (/^\d+\.\s/.test(trimmed)) {
      const listText = trimmed.replace(/^\d+\.\s+/, "");
      paragraphs.push(
        new Paragraph({
          numbering: { reference: "default-numbering", level: 0 },
          spacing: { after: 60 },
          children: parseInlineFormatting(listText),
        }),
      );
      i++;
      continue;
    }

    // Markdown table detection
    if (trimmed.startsWith("|") && trimmed.endsWith("|")) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].trim().startsWith("|") && lines[i].trim().endsWith("|")) {
        tableLines.push(lines[i].trim());
        i++;
      }
      if (tableLines.length >= 2) {
        const tableParagraphs = parseMarkdownTable(tableLines);
        paragraphs.push(...tableParagraphs);
      }
      continue;
    }

    // Regular paragraph — parse inline formatting
    paragraphs.push(
      new Paragraph({
        spacing: { after: 120 },
        children: parseInlineFormatting(trimmed),
      }),
    );
    i++;
  }

  return paragraphs;
}

// ── Inline Formatting Parser ──────────────────────────────────────────────────

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = [];
  // Regex to match **bold**, *italic*, `code`, and plain text
  const pattern = /(\*\*(.+?)\*\*)|(\*(.+?)\*)|(`(.+?)`)|([^*`]+)/g;
  let match;

  while ((match = pattern.exec(text)) !== null) {
    if (match[2]) {
      // **bold**
      runs.push(
        new TextRun({
          text: match[2],
          bold: true,
          font: FONT_BODY,
          size: 22,
          color: BRAND_DARK,
        }),
      );
    } else if (match[4]) {
      // *italic*
      runs.push(
        new TextRun({
          text: match[4],
          italics: true,
          font: FONT_BODY,
          size: 22,
          color: BRAND_DARK,
        }),
      );
    } else if (match[6]) {
      // `code`
      runs.push(
        new TextRun({
          text: match[6],
          font: "Consolas",
          size: 20,
          color: BRAND_BLUE,
          shading: {
            type: ShadingType.CLEAR,
            fill: "F1F5F9",
          },
        }),
      );
    } else if (match[7]) {
      // plain text
      runs.push(
        new TextRun({
          text: match[7],
          font: FONT_BODY,
          size: 22,
          color: BRAND_DARK,
        }),
      );
    }
  }

  if (runs.length === 0) {
    runs.push(
      new TextRun({
        text: text,
        font: FONT_BODY,
        size: 22,
        color: BRAND_DARK,
      }),
    );
  }

  return runs;
}

// ── Markdown Table Parser ─────────────────────────────────────────────────────

function parseMarkdownTable(tableLines: string[]): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  // Filter out separator lines (---|---|---)
  const dataLines = tableLines.filter((line) => !line.match(/^\|[\s-:|]+\|$/));

  if (dataLines.length === 0) return paragraphs;

  // Parse each row
  for (let rowIdx = 0; rowIdx < dataLines.length; rowIdx++) {
    const cells = dataLines[rowIdx]
      .split("|")
      .slice(1, -1) // remove empty first/last from leading/trailing |
      .map((c) => c.trim());

    const isHeader = rowIdx === 0;
    const cellTexts = cells.map((cell) => {
      const runs = parseInlineFormatting(cell);
      if (isHeader) {
        return runs.map(
          (r) =>
            new TextRun({
              text: (r as unknown as { options?: { text?: string } }).options?.text ?? cell,
              bold: true,
              font: FONT_BODY,
              size: 20,
              color: BRAND_BLUE,
            }),
        );
      }
      return runs;
    });

    // Render table row as a paragraph with tab-separated cells
    const rowRuns: TextRun[] = [];
    for (let c = 0; c < cellTexts.length; c++) {
      if (c > 0) {
        rowRuns.push(
          new TextRun({
            text: "  |  ",
            font: FONT_BODY,
            size: 20,
            color: BRAND_GRAY,
          }),
        );
      }
      rowRuns.push(...cellTexts[c]);
    }

    paragraphs.push(
      new Paragraph({
        spacing: { after: isHeader ? 40 : 40 },
        children: rowRuns,
        ...(isHeader
          ? {
              border: {
                bottom: { color: BRAND_BLUE, size: 1, style: BorderStyle.SINGLE, space: 2 },
              },
            }
          : {}),
      }),
    );
  }

  paragraphs.push(new Paragraph({ spacing: { after: 120 } }));
  return paragraphs;
}
