import type { CriterionKey } from "@/lib/evaluation-criteria";

/** Diligence guidance, not generated findings or independently verified facts. */
const guidance: Record<CriterionKey, [string, string, string, string]> = {
  idea: [
    "Demand depends on a costly, repeated customer problem and a buyer willing to pay. A broad promise to save time does not establish either.",
    "Nhu cầu phụ thuộc vào vấn đề gây tổn thất, lặp lại và người sẵn sàng trả tiền. Lời hứa tiết kiệm thời gian chưa chứng minh những yếu tố này.",
    "Identify the user and payer, one before/after workflow, frequency and measured cost of the problem. Ask for dated customer interviews or paid-pilot outcomes and the current alternative.",
    "Xác định người dùng và người trả tiền, một quy trình trước/sau, tần suất và chi phí đo được của vấn đề. Cần phỏng vấn khách hàng có ngày hoặc kết quả thử nghiệm trả phí và giải pháp họ đang dùng.",
  ],
  market: [
    "Industry spending is not automatically this business’s market. TAM needs relevant buyers × annual spend; SAM narrows serviceable segments and geography; SOM needs a timeframe, sales capacity and conversion assumptions.",
    "Chi tiêu toàn ngành không tự trở thành thị trường của doanh nghiệp. TAM cần số người mua phù hợp × chi tiêu năm; SAM lọc phân khúc và địa bàn phục vụ; SOM cần thời hạn, năng lực bán và giả định chuyển đổi.",
    "Request sources and dates for buyer counts and annual spend, scope exclusions, sales-channel capacity and conversion. Identify comparable alternatives from product/pricing pages actually read; do not assume a fixed percentage of TAM.",
    "Cần nguồn và ngày cho số người mua, chi tiêu năm, phạm vi loại trừ, năng lực kênh bán và chuyển đổi. Đối chiếu lựa chọn tương tự từ trang sản phẩm/giá thực sự đã đọc; không mặc định lấy một tỷ lệ TAM.",
  ],
  founder_profile: ["Relevant delivery history helps assess execution risk; titles alone do not establish results.", "Lịch sử thực thi liên quan giúp đánh giá rủi ro; chức danh chưa chứng minh kết quả.", "Which comparable outcomes did each founder own? Request dates, responsibilities, references and current time commitment.", "Mỗi nhà sáng lập chịu trách nhiệm kết quả tương tự nào? Cần thời gian, vai trò, người xác nhận và mức cam kết hiện tại."],
  code_git: ["Technical evidence should show maintainability, ownership and delivery dependencies; repository activity alone does not prove a working product.", "Bằng chứng kỹ thuật cần làm rõ khả năng bảo trì, sở hữu và phụ thuộc; hoạt động repository chưa chứng minh sản phẩm vận hành.", "Request an authorized repository or equivalent technical evidence, a working demonstration, deployment ownership and unresolved critical dependencies. Explain when code is not applicable to this business.", "Cần repository được cấp quyền hoặc bằng chứng kỹ thuật tương đương, demo vận hành, người phụ trách triển khai và phụ thuộc trọng yếu. Giải thích khi code không phù hợp mô hình kinh doanh."],
  website: ["A website can support distribution and product clarity; its existence does not establish demand or paying customers.", "Website có thể hỗ trợ phân phối và giải thích sản phẩm; sự tồn tại của trang chưa chứng minh nhu cầu hay khách trả tiền.", "Can the intended buyer understand the offer and complete the main action? Request dated funnel outcomes, a working product path and evidence behind public claims.", "Người mua mục tiêu có hiểu đề nghị và hoàn tất thao tác chính không? Cần kết quả funnel có kỳ, đường dùng sản phẩm hoạt động và bằng chứng cho tuyên bố công khai."],
  team: ["Delivery capacity depends on role coverage, availability and comparable experience rather than headcount alone.", "Năng lực thực thi phụ thuộc vai trò, thời gian và kinh nghiệm tương tự, không chỉ số người.", "Map named owners to the next milestones. Which essential skill is missing, and what hiring or contractor cost and lead time closes it?", "Gắn người phụ trách với mốc tiếp theo. Thiếu kỹ năng thiết yếu nào, cần chi phí và thời gian tuyển dụng hoặc thuê ngoài bao lâu?"],
  customer_size: ["Paid, active and retained customers answer different questions; registered accounts should not be presented as recurring demand.", "Khách trả tiền, đang hoạt động và được giữ lại phản ánh những điều khác nhau; tài khoản đăng ký không nên được coi là nhu cầu lặp lại.", "Separate paid customers, active users, pilots and leads for the same period. Request retention cohorts, concentration, refunds and anonymized supporting records.", "Tách khách trả tiền, người dùng hoạt động, thử nghiệm và lead cùng kỳ. Cần cohort giữ chân, mức tập trung, hoàn tiền và hồ sơ hỗ trợ đã ẩn danh."],
  gtm_strategy: ["A repeatable route to customers requires evidence of channel economics and sales capacity, not just a list of marketing channels.", "Cách tiếp cận khách hàng có thể lặp lại cần bằng chứng hiệu quả kênh và năng lực bán, không chỉ danh sách kênh marketing.", "For each tested channel, request spend, qualified leads, conversion, sales cycle and attributable revenue over the same period; separate observed results from planned targets.", "Với từng kênh đã thử, cần chi tiêu, lead phù hợp, chuyển đổi, chu kỳ bán và doanh thu cùng kỳ; tách kết quả quan sát với mục tiêu dự kiến."],
  documents: ["Consistent, current documents let an investor test the business’s claims and obligations; document presence alone does not confirm their substance.", "Tài liệu nhất quán và cập nhật giúp nhà đầu tư kiểm tra tuyên bố và nghĩa vụ; có tài liệu chưa xác nhận nội dung đúng.", "Which decision-relevant records are current and signed where needed? Reconcile entity names, dates, amounts and obligations across the deck, accounts and agreements.", "Hồ sơ ảnh hưởng quyết định nào đã cập nhật và ký khi cần? Đối chiếu pháp nhân, ngày, số tiền và nghĩa vụ giữa deck, sổ sách và hợp đồng."],
  dataroom: ["A traceable data room reduces diligence uncertainty only when records are complete, permissioned and internally consistent.", "Data room truy xuất được chỉ giảm bất định khi hồ sơ đầy đủ, đúng quyền và nhất quán.", "Request an indexed document list with owners, dates and access permissions. Identify missing items and conflicting versions without exposing private links publicly.", "Cần danh mục tài liệu với người phụ trách, ngày và quyền truy cập. Chỉ rõ phần thiếu và phiên bản mâu thuẫn, không công khai liên kết riêng tư."],
  team_structure: ["Clear authority and accountability affect execution, oversight and key-person dependency.", "Thẩm quyền và trách nhiệm rõ ảnh hưởng thực thi, giám sát và phụ thuộc người chủ chốt.", "Who approves spending, product priorities and legal commitments? Request decision rights, reporting lines and cover for critical roles.", "Ai duyệt chi tiêu, ưu tiên sản phẩm và cam kết pháp lý? Cần quyền quyết định, tuyến báo cáo và người thay thế vai trò trọng yếu."],
  roadmap: ["A fundable roadmap connects customer outcomes to measurable milestones, resources and dependencies; dates alone do not establish feasibility.", "Lộ trình phù hợp gọi vốn nối kết quả khách hàng với mốc đo được, nguồn lực và phụ thuộc; ngày dự kiến chưa chứng minh khả thi.", "For the next milestones, request acceptance measures, owners, cost, dependencies and evidence from prior delivery. What changes if the milestone slips?", "Với mốc tiếp theo, cần tiêu chí nghiệm thu, người phụ trách, chi phí, phụ thuộc và bằng chứng thực thi trước đó. Điều gì thay đổi nếu chậm mốc?"],
  revenue: ["Recurring, collectible revenue and retention affect repeatability and valuation. Bookings, GMV, cash receipts and revenue are not interchangeable.", "Doanh thu lặp lại, thu được và giữ chân ảnh hưởng khả năng lặp lại và định giá. Booking, GMV, tiền thu và doanh thu không thay thế nhau.", "Reconcile revenue to dated records for the correct entity, currency and period; separate recurring/one-off sales, refunds, churn and matching costs. Missing verification must not become a zero-revenue conclusion.", "Đối chiếu doanh thu với hồ sơ có ngày, đúng pháp nhân, tiền tệ và kỳ; tách lặp lại/một lần, hoàn tiền, churn và chi phí cùng kỳ. Chưa xác minh không được trở thành kết luận doanh thu bằng không."],
};
export function criterionDiligence(key: CriterionKey, locale: "en" | "vi") {
  const row = guidance[key];
  return { implication: row[locale === "vi" ? 1 : 0], question: row[locale === "vi" ? 3 : 2] };
}
