// G34 BT3 — page-1 "dashboard v4" labels (EN / VI; ES / JA read EN).
// Spec docs/design/tbr-v4-dashboard-spec.md §1 + G31 microcopy
// (docs/design/investor-lens-report-spec.md §10: meeting.A–D, the
// why / stop / ask triptych, degraded banner, cap-table line). Never-say safe:
// labels point to further diligence, never to an investment decision (D21),
// and show emphasis BANDS only, never a numeric weight (D24-f).

import type { EmphasisBand } from "@/lib/screening/registry";
import type { InvestmentBand } from "./schema";

export type DashboardV4Locale = "en" | "vi";

const EN = {
  kicker: "Investor dashboard",
  tileValuation: "Indicative pre-money (A$)",
  tileSvi: "SVI index",
  tileInvestor: "Investor Score",
  tileEvidence: "Evidence confidence",
  tileVerification: "Verification",
  valuationUnavailable: "Not enough evidence to estimate a range",
  unlockMissing: (inputs: string) => `Add ${inputs} to unlock a valuation method`,
  unlockRevenue: "Connect Stripe or Xero → revenue-multiple method",
  unlockEvidence: "Add documents or connected sources to lift confidence above 30 %",
  sviUncapped: "uncapped index, not a score out of 100",
  investorOf: (n: number) => `composite of ${n} of 8 dimensions`,
  investorPending: "composite pending: no dimension assessed",
  verificationCovers: ["No business identifier on file", "Business ID entered, e-mail verified", "ABN Active on the ABR, domain verified", "Financials attested through a connected source", "Independent audit or accountant attestation on file", "Connectors resyncing on schedule"] as readonly string[],
  verificationLevel: ["Unverified", "Self-declared", "Evidence-checked", "Trust", "Trust with attestations", "Continuous monitoring"] as readonly string[],
  meeting: { A: "Strong case to investigate", B: "Worth investigating", C: "Major issues to resolve", D: "Evidence incomplete" } as Record<InvestmentBand, string>,
  meetingRule: (band: string) => `Rule: ${band}`,
  metricsTitle: "Key metrics",
  metricsCaption: "Key metrics with the evidence behind each figure. Not evidenced = no connector or document supplies it yet.",
  metric: { arr: "ARR", growth: "Growth", nrr: "NRR", gross_margin: "Gross margin", runway: "Runway", burn_multiple: "Burn multiple" },
  metricStatus: { verified: "verified T1", company_stated: "company-stated T3", stated: "stated T4", observed: "observed", assumed: "Sector median assumed, not observed", not_evidenced: "Not evidenced" },
  perMonth: (pct: string) => `${pct}%/mo`,
  runwayValue: (months: number) => `${months} months`,
  scorecardTitle: "8-dimension scorecard",
  scorecardCaption: "Eight dimensions in chapter order: lead agent, stage emphasis, score, band, evidence confidence and trend.",
  thDimension: "Dimension · lead",
  thEmphasis: "Emphasis",
  thScore: "Score",
  thBand: "Band",
  thEvidence: "Evidence",
  thTrend: "Trend",
  thOpen: "Chapter",
  leadLine: (code: string) => `Lead · ${code}`,
  leadTitle: (code: string) => `${code} agent`,
  leadFootnote: "Lead = AI agent role that drafted and scored the chapter (saved provenance, not a model claim or human sign-off).",
  emphasis: { VeryHigh: "Very high", High: "High", Medium: "Medium", Low: "Low" } as Record<EmphasisBand, string>,
  emphasisNote: (stage: string) => `Emphasis = how much this dimension matters at ${stage} (band only).`,
  pending: "Pending",
  pendingNoEvidence: "Pending: no evidence",
  writtenUnavailable: "Written analysis unavailable",
  inFullReport: "In full report",
  openChapter: "Open chapter",
  trendNone: "—",
  trendUnavailable: "No same-method revision to compare",
  scoreAria: (name: string, score: number | null, band: string, ev: number | null) =>
    `${name}: ${score === null ? "pending, no score" : `score ${score}`}, ${band}${ev === null ? "" : `, evidence ${ev} percent`}`,
  meterAria: (ev: number) => `Evidence confidence ${ev} percent`,
  redFlagsTitle: "Red flags (rule-derived)",
  redFlagsNone: "No rule-derived red flag triggered. This does not establish an absence of risk.",
  redFlagsMore: (n: number) => `+${n} more`,
  viewAllRisks: "View all risks",
  flag: {
    ask: (pct: number) => `Ask ${pct} % above the valuation range`,
    capTable: "No cap table on file — upload to assess",
    unverified: (n: number) => `${n} material claim${n === 1 ? "" : "s"} founder-stated only`,
    consistencyLocked: (n: number) => `${n} consistency issue${n === 1 ? "" : "s"} — details in full report`,
    stale: (n: number) => `${n} evidence item${n === 1 ? "" : "s"} past freshness`,
    degraded: (n: number) => `${n} section${n === 1 ? "" : "s"}: written analysis unavailable`,
  },
  signalsTitle: "Investor signals",
  signalsNote: "Status only — no signal score until each question is scored.",
  why: "Why investigate",
  stop: "What could stop the deal",
  ask: "Ask before the meeting",
  whyEmpty: "Insufficient linked evidence to highlight supported strengths.",
  stopEmpty: "No cited deal-breaker recorded; this does not establish an absence of risk.",
  askEmpty: "Review the criteria in the full report.",
  lockedMore: (n: number) => `+${n} dimension${n === 1 ? "" : "s"} detailed in the full report`,
  degradedBanner: (n: number, names: string) => `Written analysis is unavailable for ${n} section${n === 1 ? "" : "s"} (${names}); results below rely on recorded scores and evidence.`,
  topRedFlag: "Top red flag",
  questions: "Questions to ask",
  source: { stripe: "Stripe", xero: "Xero", upload: "Uploaded document", connector_other: "Connected source", url: "Public URL", ga4: "GA4", github: "GitHub", linkedin: "LinkedIn", self_declared: "Self-declared", founder_profile: "Founder profile", external: "Public register" } as Record<string, string>,
  // G34 BT6 — peer position (RQ19), stage ladder (RQ20), calibration (RQ21), round readiness (RQ27), spike (RQ28).
  peerTitle: "Peer position",
  peerCohort: (stage: string) => `${stage} cohort`,
  peerPublished: (pct: number, cohort: string, n: number, indicative: boolean) => `p${pct} of ${cohort} (n = ${n}${indicative ? ", indicative" : ""})`,
  peerTooSmall: (n: number) => `Peer set too small (n = ${n})`,
  ladderTitle: "Stage ladder",
  ladderSteps: ["Idea", "Validating", "Early revenue", "Scaling", "Established"] as readonly string[],
  ladderNote: "Commercial maturity from verified evidence only — separate from the quality scores.",
  ladderBasisNone: "no verified customer or revenue evidence on file",
  ladderBasisCustomer: (source: string) => `customer evidence · ${source}`,
  ladderBasisRevenue: (source: string) => `revenue evidence · ${source}`,
  ladderAria: (step: number, label: string) => `Stage ladder: step ${step} of 5, ${label}`,
  spikeTitle: "Spike",
  spike: (names: string) => `${names} (top 10% of stage)`,
  roundTitle: "Round readiness",
  round: (date: string, months: string, source: string) => `Last round: ${date} · runway: ${months} months (${source})`,
  calibrationPublished: (rho: string, n: number, date: string) => `Calibration: SVI backtest ρ ${rho} vs round size (n = ${n}, ${date}). Rank calibration only — not a substitute for diligence.`,
  calibrationPending: (n: number | null) => `Calibration pending${n ? ` (backtest n = ${n})` : ""} — not a substitute for diligence.`,
  calibrationUnknown: "Calibration: the SVI backtest and its limits are published — not a substitute for diligence.",
  calibrationLink: "How the SVI is calibrated",
};

export type DashboardV4Strings = typeof EN;

const VI: DashboardV4Strings = {
  ...EN,
  kicker: "Bảng tổng quan cho nhà đầu tư",
  tileValuation: "Định giá tham khảo trước vốn (A$)",
  tileSvi: "Chỉ số SVI",
  tileInvestor: "Điểm nhà đầu tư",
  tileEvidence: "Độ tin cậy bằng chứng",
  tileVerification: "Mức xác minh",
  valuationUnavailable: "Chưa đủ bằng chứng để ước tính khoảng giá trị",
  unlockMissing: (inputs) => `Bổ sung ${inputs} để mở một phương pháp định giá`,
  unlockRevenue: "Kết nối Stripe hoặc Xero → phương pháp bội số doanh thu",
  unlockEvidence: "Bổ sung tài liệu hoặc nguồn kết nối để nâng độ tin cậy trên 30 %",
  sviUncapped: "chỉ số không giới hạn, không phải điểm trên 100",
  investorOf: (n) => `tổng hợp ${n}/8 khía cạnh`,
  investorPending: "tổng hợp đang chờ: chưa khía cạnh nào được đánh giá",
  verificationCovers: ["Chưa có mã doanh nghiệp", "Đã nhập mã doanh nghiệp, xác minh e-mail", "ABN đang hoạt động trên ABR, xác minh tên miền", "Tài chính được xác nhận qua nguồn kết nối", "Có kiểm toán độc lập hoặc xác nhận của kế toán", "Kết nối đồng bộ định kỳ"],
  verificationLevel: ["Chưa xác minh", "Tự khai", "Đã kiểm tra bằng chứng", "Tin cậy", "Tin cậy có xác nhận", "Giám sát liên tục"],
  meeting: { A: "Rất đáng tìm hiểu", B: "Đáng tìm hiểu", C: "Có vấn đề lớn cần giải quyết", D: "Chưa đủ bằng chứng" },
  meetingRule: (band) => `Quy tắc: ${band}`,
  metricsTitle: "Chỉ số chính",
  metricsCaption: "Chỉ số chính kèm bằng chứng cho từng con số. Chưa có bằng chứng = chưa có nguồn kết nối hoặc tài liệu cung cấp.",
  metric: { arr: "ARR", growth: "Tăng trưởng", nrr: "NRR", gross_margin: "Biên lợi nhuận gộp", runway: "Runway", burn_multiple: "Bội số đốt tiền" },
  metricStatus: { verified: "đã xác minh T1", company_stated: "công ty cung cấp T3", stated: "tự khai T4", observed: "quan sát được", assumed: "Giả định trung vị ngành, không quan sát", not_evidenced: "Chưa có bằng chứng" },
  perMonth: (pct) => `${pct}%/tháng`,
  runwayValue: (months) => `${months} tháng`,
  scorecardTitle: "Bảng điểm 8 khía cạnh",
  scorecardCaption: "Tám khía cạnh theo thứ tự chương: agent phụ trách, mức nhấn mạnh theo giai đoạn, điểm, dải, độ tin cậy bằng chứng và xu hướng.",
  thDimension: "Khía cạnh · phụ trách",
  thEmphasis: "Nhấn mạnh",
  thScore: "Điểm",
  thBand: "Dải",
  thEvidence: "Bằng chứng",
  thTrend: "Xu hướng",
  thOpen: "Chương",
  leadLine: (code) => `Phụ trách · ${code}`,
  leadTitle: (code) => `Agent ${code}`,
  leadFootnote: "Phụ trách = vai trò agent AI đã soạn và chấm chương (thông tin xuất xứ đã lưu, không phải xác nhận model hay phê duyệt của con người).",
  emphasis: { VeryHigh: "Rất cao", High: "Cao", Medium: "Trung bình", Low: "Thấp" },
  emphasisNote: (stage) => `Nhấn mạnh = mức quan trọng của khía cạnh ở giai đoạn ${stage} (chỉ dải).`,
  pending: "Chưa đánh giá",
  pendingNoEvidence: "Chưa đánh giá: chưa có bằng chứng",
  writtenUnavailable: "Chưa có phân tích văn bản",
  inFullReport: "Trong báo cáo đầy đủ",
  openChapter: "Mở chương",
  trendUnavailable: "Chưa có bản cùng phương pháp để so sánh",
  scoreAria: (name, score, band, ev) => `${name}: ${score === null ? "chưa đánh giá" : `điểm ${score}`}, ${band}${ev === null ? "" : `, bằng chứng ${ev} phần trăm`}`,
  meterAria: (ev) => `Độ tin cậy bằng chứng ${ev} phần trăm`,
  redFlagsTitle: "Cờ đỏ (theo quy tắc)",
  redFlagsNone: "Không có cờ đỏ nào theo quy tắc. Điều này không đồng nghĩa với không có rủi ro.",
  redFlagsMore: (n) => `+${n} mục khác`,
  viewAllRisks: "Xem mọi rủi ro",
  flag: {
    ask: (pct) => `Mức gọi vốn cao hơn khoảng định giá ${pct} %`,
    capTable: "Chưa có cap table — tải lên để đánh giá",
    unverified: (n) => `${n} tuyên bố trọng yếu chỉ do founder cung cấp`,
    consistencyLocked: (n) => `${n} điểm chưa nhất quán — chi tiết trong báo cáo đầy đủ`,
    stale: (n) => `${n} bằng chứng đã quá hạn`,
    degraded: (n) => `${n} mục: chưa có phân tích văn bản`,
  },
  signalsTitle: "Tín hiệu nhà đầu tư",
  signalsNote: "Chỉ trạng thái — chưa có điểm tín hiệu cho đến khi từng câu hỏi được chấm.",
  why: "Vì sao đáng tìm hiểu",
  stop: "Điều có thể chặn thương vụ",
  ask: "Hỏi trước buổi gặp",
  whyEmpty: "Chưa đủ bằng chứng được liên kết để nêu bật điểm mạnh.",
  stopEmpty: "Chưa có điểm chặn có dẫn chứng; không có nghĩa là không có rủi ro.",
  askEmpty: "Xem các tiêu chí trong báo cáo đầy đủ.",
  lockedMore: (n) => `+${n} khía cạnh chi tiết trong báo cáo đầy đủ`,
  degradedBanner: (n, names) => `Chưa dựng được phân tích văn bản cho ${n} mục (${names}); kết quả dưới đây chỉ dựa trên điểm và bằng chứng đã ghi nhận.`,
  topRedFlag: "Cờ đỏ hàng đầu",
  questions: "Câu hỏi nên hỏi",
  source: { ...EN.source, upload: "Tài liệu tải lên", connector_other: "Nguồn kết nối", url: "URL công khai", self_declared: "Tự khai", founder_profile: "Hồ sơ founder", external: "Sổ đăng ký công khai" },
  peerTitle: "Vị trí so với nhóm",
  peerCohort: (stage) => `nhóm ${stage}`,
  peerPublished: (pct, cohort, n, indicative) => `p${pct} trong ${cohort} (n = ${n}${indicative ? ", tham khảo" : ""})`,
  peerTooSmall: (n) => `Nhóm so sánh quá nhỏ (n = ${n})`,
  ladderTitle: "Nấc giai đoạn",
  ladderSteps: ["Ý tưởng", "Đang kiểm chứng", "Doanh thu ban đầu", "Mở rộng", "Ổn định"],
  ladderNote: "Mức trưởng thành thương mại chỉ từ bằng chứng đã xác minh — tách khỏi điểm chất lượng.",
  ladderBasisNone: "chưa có bằng chứng khách hàng hoặc doanh thu đã xác minh",
  ladderBasisCustomer: (source) => `bằng chứng khách hàng · ${source}`,
  ladderBasisRevenue: (source) => `bằng chứng doanh thu · ${source}`,
  ladderAria: (step, label) => `Nấc giai đoạn: bậc ${step}/5, ${label}`,
  spikeTitle: "Điểm vượt trội",
  spike: (names) => `${names} (top 10% cùng giai đoạn)`,
  roundTitle: "Sẵn sàng gọi vốn",
  round: (date, months, source) => `Vòng gần nhất: ${date} · runway: ${months} tháng (${source})`,
  calibrationPublished: (rho, n, date) => `Hiệu chuẩn: backtest SVI ρ ${rho} so với quy mô vòng (n = ${n}, ${date}). Chỉ hiệu chuẩn thứ hạng — không thay thế thẩm định.`,
  calibrationPending: (n) => `Hiệu chuẩn đang chờ${n ? ` (backtest n = ${n})` : ""} — không thay thế thẩm định.`,
  calibrationUnknown: "Hiệu chuẩn: backtest SVI và giới hạn của nó được công bố — không thay thế thẩm định.",
  calibrationLink: "Cách SVI được hiệu chuẩn",
};

export function dashboardV4Strings(locale: string | undefined): DashboardV4Strings {
  return locale === "vi" ? VI : EN;
}
